// Code generated by abc. DO NOT EDIT.

package Testing

//line A.idl:2
//Struct Decl: A
//Usage Count: 0
type A struct {
	C Common
}

//Constructors
func NewADefaultPointer() (*A, error) {
	return &A{}, nil
}

func NewADefaultValue() (A, error) {
	return A{}, nil
}

func NewAValue(
	c Common) (A, error) {
	return A{
		C: c,
	}, nil
}
