// Code generated by abc. DO NOT EDIT.

package Testing

//line common.idl:4
//Struct Decl: Common
//Usage Count: 2
type Common struct {
}

//Constructors
func NewCommonDefaultPointer() (*Common, error) {
	return &Common{}, nil
}

func NewCommonDefaultValue() (Common, error) {
	return Common{}, nil
}
