// Code generated by abc. DO NOT EDIT.

package corbaFiles

//line BiDirPolicy.idl:22
type BiDirPolicy_BidirectionalPolicyValue uint16

//line BiDirPolicy.idl:28
//Interface Decl: BiDirPolicy_BidirectionalPolicy
//Usage Count: 0
type BiDirPolicy_BidirectionalPolicy interface {

	//line BiDirPolicy.idl:29
	GetValue() BiDirPolicy_BidirectionalPolicyValue
}
