// Code generated by abc. DO NOT EDIT.

package corbaFiles

//line CONV_FRAME.idl:17
type CONV_FRAME_CodeSetId uint32

//line CONV_FRAME.idl:19
//Sequence Decl: Sequence_CodeSetId
type Sequence_CodeSetId interface{}

//line CONV_FRAME.idl:19
//Typedef Decl: CONV_FRAME_CodeSetIdSeq
type CONV_FRAME_CodeSetIdSeq Sequence_CodeSetId

//line CONV_FRAME.idl:21
//Struct Decl: CONV_FRAME_CodeSetComponent
//Usage Count: 2
type CONV_FRAME_CodeSetComponent struct {
	Native_code_set      CONV_FRAME_CodeSetId
	Conversion_code_sets CONV_FRAME_CodeSetIdSeq
}

//Constructors
func NewCONV_FRAME_CodeSetComponentDefaultPointer() (*CONV_FRAME_CodeSetComponent, error) {
	return &CONV_FRAME_CodeSetComponent{}, nil
}

func NewCONV_FRAME_CodeSetComponentDefaultValue() (CONV_FRAME_CodeSetComponent, error) {
	return CONV_FRAME_CodeSetComponent{}, nil
}

func NewCONV_FRAME_CodeSetComponentValue(
	native_code_set CONV_FRAME_CodeSetId,
	conversion_code_sets CONV_FRAME_CodeSetIdSeq) (CONV_FRAME_CodeSetComponent, error) {
	return CONV_FRAME_CodeSetComponent{
		Native_code_set:      native_code_set,
		Conversion_code_sets: conversion_code_sets,
	}, nil
}

//line CONV_FRAME.idl:25
//Struct Decl: CONV_FRAME_CodeSetComponentInfo
//Usage Count: 0
type CONV_FRAME_CodeSetComponentInfo struct {
	ForCharData  CONV_FRAME_CodeSetComponent
	ForWcharData CONV_FRAME_CodeSetComponent
}

//Constructors
func NewCONV_FRAME_CodeSetComponentInfoDefaultPointer() (*CONV_FRAME_CodeSetComponentInfo, error) {
	return &CONV_FRAME_CodeSetComponentInfo{}, nil
}

func NewCONV_FRAME_CodeSetComponentInfoDefaultValue() (CONV_FRAME_CodeSetComponentInfo, error) {
	return CONV_FRAME_CodeSetComponentInfo{}, nil
}

func NewCONV_FRAME_CodeSetComponentInfoValue(
	forCharData CONV_FRAME_CodeSetComponent,
	forWcharData CONV_FRAME_CodeSetComponent) (CONV_FRAME_CodeSetComponentInfo, error) {
	return CONV_FRAME_CodeSetComponentInfo{
		ForCharData:  forCharData,
		ForWcharData: forWcharData,
	}, nil
}

//line CONV_FRAME.idl:32
//Struct Decl: CONV_FRAME_CodeSetContext
//Usage Count: 0
type CONV_FRAME_CodeSetContext struct {
	Char_data  CONV_FRAME_CodeSetId
	Wchar_data CONV_FRAME_CodeSetId
}

//Constructors
func NewCONV_FRAME_CodeSetContextDefaultPointer() (*CONV_FRAME_CodeSetContext, error) {
	return &CONV_FRAME_CodeSetContext{}, nil
}

func NewCONV_FRAME_CodeSetContextDefaultValue() (CONV_FRAME_CodeSetContext, error) {
	return CONV_FRAME_CodeSetContext{}, nil
}

func NewCONV_FRAME_CodeSetContextValue(
	char_data CONV_FRAME_CodeSetId,
	wchar_data CONV_FRAME_CodeSetId) (CONV_FRAME_CodeSetContext, error) {
	return CONV_FRAME_CodeSetContext{
		Char_data:  char_data,
		Wchar_data: wchar_data,
	}, nil
}
