// Code generated by abc. DO NOT EDIT.

package corbaFiles

//line CORBA_CustomMarshal.idl:5
//Interface Decl: CORBA_CustomMarshal
//Usage Count: 0
type CORBA_CustomMarshal interface {

	//line CORBA_CustomMarshal.idl:6
	Marshal(os CORBA_DataOutputStream) error

	//line CORBA_CustomMarshal.idl:7
	Unmarshal(is CORBA_DataInputStream) error
}
