package corbaFiles

//Code generated by  DO NOT EDIT.
//line CORBA_CustomMarshal.idl:5
//ValueAbsolute Decl: CustomMarshal
type CustomMarshal interface {
	//line CORBA_CustomMarshal.idl:6
	Marshal(os DataOutputStream) (void, error)
	//line CORBA_CustomMarshal.idl:7
	Unmarshal(is DataInputStream) (void, error)
}
