package corbaFiles

//Code generated by  DO NOT EDIT.
//line CORBA_StandardExceptions.idl:8
//Usage Count: 36
type CORBA_Completion_status int
//noinspection ALL
const (
	CORBA_Completion_status_COMPLETED_YES = iota
	CORBA_Completion_status_COMPLETED_NO
	CORBA_Completion_status_COMPLETED_MAYBE
)
//line CORBA_StandardExceptions.idl:11
//Usage Count: 0
type CORBA_Exception_type int
//noinspection ALL
const (
	CORBA_Exception_type_NO_EXCEPTION = iota
	CORBA_Exception_type_USER_EXCEPTION
	CORBA_Exception_type_SYSTEM_EXCEPTION
)
//line CORBA_StandardExceptions.idl:15
//Exception Decl: CORBA_UNKNOWN
//Usage Count: 0
type CORBA_UNKNOWN struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_UNKNOWNDefaultPointer() (*CORBA_UNKNOWN, error) {
	return &CORBA_UNKNOWN {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_UNKNOWNDefaultValue() (CORBA_UNKNOWN, error) {
	return CORBA_UNKNOWN {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_UNKNOWNValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_UNKNOWN, error) {
	return CORBA_UNKNOWN {
		Minor: minor,
		Completed: completed,
	}, nil
}
//line CORBA_StandardExceptions.idl:16
//Exception Decl: CORBA_BAD_PARAM
//Usage Count: 0
type CORBA_BAD_PARAM struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_BAD_PARAMDefaultPointer() (*CORBA_BAD_PARAM, error) {
	return &CORBA_BAD_PARAM {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_BAD_PARAMDefaultValue() (CORBA_BAD_PARAM, error) {
	return CORBA_BAD_PARAM {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_BAD_PARAMValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_BAD_PARAM, error) {
	return CORBA_BAD_PARAM {
		Minor: minor,
		Completed: completed,
	}, nil
}
//line CORBA_StandardExceptions.idl:18
//Exception Decl: CORBA_NO_MEMORY
//Usage Count: 0
type CORBA_NO_MEMORY struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_NO_MEMORYDefaultPointer() (*CORBA_NO_MEMORY, error) {
	return &CORBA_NO_MEMORY {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_NO_MEMORYDefaultValue() (CORBA_NO_MEMORY, error) {
	return CORBA_NO_MEMORY {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_NO_MEMORYValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_NO_MEMORY, error) {
	return CORBA_NO_MEMORY {
		Minor: minor,
		Completed: completed,
	}, nil
}
//line CORBA_StandardExceptions.idl:20
//Exception Decl: CORBA_IMP_LIMIT
//Usage Count: 0
type CORBA_IMP_LIMIT struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_IMP_LIMITDefaultPointer() (*CORBA_IMP_LIMIT, error) {
	return &CORBA_IMP_LIMIT {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_IMP_LIMITDefaultValue() (CORBA_IMP_LIMIT, error) {
	return CORBA_IMP_LIMIT {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_IMP_LIMITValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_IMP_LIMIT, error) {
	return CORBA_IMP_LIMIT {
		Minor: minor,
		Completed: completed,
	}, nil
}
//line CORBA_StandardExceptions.idl:22
//Exception Decl: CORBA_COMM_FAILURE
//Usage Count: 0
type CORBA_COMM_FAILURE struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_COMM_FAILUREDefaultPointer() (*CORBA_COMM_FAILURE, error) {
	return &CORBA_COMM_FAILURE {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_COMM_FAILUREDefaultValue() (CORBA_COMM_FAILURE, error) {
	return CORBA_COMM_FAILURE {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_COMM_FAILUREValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_COMM_FAILURE, error) {
	return CORBA_COMM_FAILURE {
		Minor: minor,
		Completed: completed,
	}, nil
}
//line CORBA_StandardExceptions.idl:23
//Exception Decl: CORBA_INV_OBJREF
//Usage Count: 0
type CORBA_INV_OBJREF struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_INV_OBJREFDefaultPointer() (*CORBA_INV_OBJREF, error) {
	return &CORBA_INV_OBJREF {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_INV_OBJREFDefaultValue() (CORBA_INV_OBJREF, error) {
	return CORBA_INV_OBJREF {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_INV_OBJREFValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_INV_OBJREF, error) {
	return CORBA_INV_OBJREF {
		Minor: minor,
		Completed: completed,
	}, nil
}
//line CORBA_StandardExceptions.idl:24
//Exception Decl: CORBA_NO_PERMISSION
//Usage Count: 0
type CORBA_NO_PERMISSION struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_NO_PERMISSIONDefaultPointer() (*CORBA_NO_PERMISSION, error) {
	return &CORBA_NO_PERMISSION {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_NO_PERMISSIONDefaultValue() (CORBA_NO_PERMISSION, error) {
	return CORBA_NO_PERMISSION {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_NO_PERMISSIONValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_NO_PERMISSION, error) {
	return CORBA_NO_PERMISSION {
		Minor: minor,
		Completed: completed,
	}, nil
}
//line CORBA_StandardExceptions.idl:26
//Exception Decl: CORBA_INTERNAL
//Usage Count: 0
type CORBA_INTERNAL struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_INTERNALDefaultPointer() (*CORBA_INTERNAL, error) {
	return &CORBA_INTERNAL {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_INTERNALDefaultValue() (CORBA_INTERNAL, error) {
	return CORBA_INTERNAL {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_INTERNALValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_INTERNAL, error) {
	return CORBA_INTERNAL {
		Minor: minor,
		Completed: completed,
	}, nil
}
//line CORBA_StandardExceptions.idl:27
//Exception Decl: CORBA_MARSHAL
//Usage Count: 0
type CORBA_MARSHAL struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_MARSHALDefaultPointer() (*CORBA_MARSHAL, error) {
	return &CORBA_MARSHAL {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_MARSHALDefaultValue() (CORBA_MARSHAL, error) {
	return CORBA_MARSHAL {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_MARSHALValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_MARSHAL, error) {
	return CORBA_MARSHAL {
		Minor: minor,
		Completed: completed,
	}, nil
}
//line CORBA_StandardExceptions.idl:29
//Exception Decl: CORBA_INITIALIZE
//Usage Count: 0
type CORBA_INITIALIZE struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_INITIALIZEDefaultPointer() (*CORBA_INITIALIZE, error) {
	return &CORBA_INITIALIZE {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_INITIALIZEDefaultValue() (CORBA_INITIALIZE, error) {
	return CORBA_INITIALIZE {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_INITIALIZEValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_INITIALIZE, error) {
	return CORBA_INITIALIZE {
		Minor: minor,
		Completed: completed,
	}, nil
}
//line CORBA_StandardExceptions.idl:30
//Exception Decl: CORBA_NO_IMPLEMENT
//Usage Count: 0
type CORBA_NO_IMPLEMENT struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_NO_IMPLEMENTDefaultPointer() (*CORBA_NO_IMPLEMENT, error) {
	return &CORBA_NO_IMPLEMENT {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_NO_IMPLEMENTDefaultValue() (CORBA_NO_IMPLEMENT, error) {
	return CORBA_NO_IMPLEMENT {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_NO_IMPLEMENTValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_NO_IMPLEMENT, error) {
	return CORBA_NO_IMPLEMENT {
		Minor: minor,
		Completed: completed,
	}, nil
}
//line CORBA_StandardExceptions.idl:32
//Exception Decl: CORBA_BAD_TYPECODE
//Usage Count: 0
type CORBA_BAD_TYPECODE struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_BAD_TYPECODEDefaultPointer() (*CORBA_BAD_TYPECODE, error) {
	return &CORBA_BAD_TYPECODE {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_BAD_TYPECODEDefaultValue() (CORBA_BAD_TYPECODE, error) {
	return CORBA_BAD_TYPECODE {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_BAD_TYPECODEValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_BAD_TYPECODE, error) {
	return CORBA_BAD_TYPECODE {
		Minor: minor,
		Completed: completed,
	}, nil
}
//line CORBA_StandardExceptions.idl:33
//Exception Decl: CORBA_BAD_OPERATION
//Usage Count: 0
type CORBA_BAD_OPERATION struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_BAD_OPERATIONDefaultPointer() (*CORBA_BAD_OPERATION, error) {
	return &CORBA_BAD_OPERATION {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_BAD_OPERATIONDefaultValue() (CORBA_BAD_OPERATION, error) {
	return CORBA_BAD_OPERATION {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_BAD_OPERATIONValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_BAD_OPERATION, error) {
	return CORBA_BAD_OPERATION {
		Minor: minor,
		Completed: completed,
	}, nil
}
//line CORBA_StandardExceptions.idl:34
//Exception Decl: CORBA_NO_RESOURCES
//Usage Count: 0
type CORBA_NO_RESOURCES struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_NO_RESOURCESDefaultPointer() (*CORBA_NO_RESOURCES, error) {
	return &CORBA_NO_RESOURCES {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_NO_RESOURCESDefaultValue() (CORBA_NO_RESOURCES, error) {
	return CORBA_NO_RESOURCES {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_NO_RESOURCESValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_NO_RESOURCES, error) {
	return CORBA_NO_RESOURCES {
		Minor: minor,
		Completed: completed,
	}, nil
}
//line CORBA_StandardExceptions.idl:36
//Exception Decl: CORBA_NO_RESPONSE
//Usage Count: 0
type CORBA_NO_RESPONSE struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_NO_RESPONSEDefaultPointer() (*CORBA_NO_RESPONSE, error) {
	return &CORBA_NO_RESPONSE {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_NO_RESPONSEDefaultValue() (CORBA_NO_RESPONSE, error) {
	return CORBA_NO_RESPONSE {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_NO_RESPONSEValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_NO_RESPONSE, error) {
	return CORBA_NO_RESPONSE {
		Minor: minor,
		Completed: completed,
	}, nil
}
//line CORBA_StandardExceptions.idl:38
//Exception Decl: CORBA_PERSIST_STORE
//Usage Count: 0
type CORBA_PERSIST_STORE struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_PERSIST_STOREDefaultPointer() (*CORBA_PERSIST_STORE, error) {
	return &CORBA_PERSIST_STORE {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_PERSIST_STOREDefaultValue() (CORBA_PERSIST_STORE, error) {
	return CORBA_PERSIST_STORE {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_PERSIST_STOREValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_PERSIST_STORE, error) {
	return CORBA_PERSIST_STORE {
		Minor: minor,
		Completed: completed,
	}, nil
}
//line CORBA_StandardExceptions.idl:39
//Exception Decl: CORBA_BAD_INV_ORDER
//Usage Count: 0
type CORBA_BAD_INV_ORDER struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_BAD_INV_ORDERDefaultPointer() (*CORBA_BAD_INV_ORDER, error) {
	return &CORBA_BAD_INV_ORDER {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_BAD_INV_ORDERDefaultValue() (CORBA_BAD_INV_ORDER, error) {
	return CORBA_BAD_INV_ORDER {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_BAD_INV_ORDERValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_BAD_INV_ORDER, error) {
	return CORBA_BAD_INV_ORDER {
		Minor: minor,
		Completed: completed,
	}, nil
}
//line CORBA_StandardExceptions.idl:41
//Exception Decl: CORBA_TRANSIENT
//Usage Count: 0
type CORBA_TRANSIENT struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_TRANSIENTDefaultPointer() (*CORBA_TRANSIENT, error) {
	return &CORBA_TRANSIENT {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_TRANSIENTDefaultValue() (CORBA_TRANSIENT, error) {
	return CORBA_TRANSIENT {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_TRANSIENTValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_TRANSIENT, error) {
	return CORBA_TRANSIENT {
		Minor: minor,
		Completed: completed,
	}, nil
}
//line CORBA_StandardExceptions.idl:43
//Exception Decl: CORBA_FREE_MEM
//Usage Count: 0
type CORBA_FREE_MEM struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_FREE_MEMDefaultPointer() (*CORBA_FREE_MEM, error) {
	return &CORBA_FREE_MEM {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_FREE_MEMDefaultValue() (CORBA_FREE_MEM, error) {
	return CORBA_FREE_MEM {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_FREE_MEMValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_FREE_MEM, error) {
	return CORBA_FREE_MEM {
		Minor: minor,
		Completed: completed,
	}, nil
}
//line CORBA_StandardExceptions.idl:44
//Exception Decl: CORBA_INV_IDENT
//Usage Count: 0
type CORBA_INV_IDENT struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_INV_IDENTDefaultPointer() (*CORBA_INV_IDENT, error) {
	return &CORBA_INV_IDENT {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_INV_IDENTDefaultValue() (CORBA_INV_IDENT, error) {
	return CORBA_INV_IDENT {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_INV_IDENTValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_INV_IDENT, error) {
	return CORBA_INV_IDENT {
		Minor: minor,
		Completed: completed,
	}, nil
}
//line CORBA_StandardExceptions.idl:45
//Exception Decl: CORBA_INV_FLAG
//Usage Count: 0
type CORBA_INV_FLAG struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_INV_FLAGDefaultPointer() (*CORBA_INV_FLAG, error) {
	return &CORBA_INV_FLAG {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_INV_FLAGDefaultValue() (CORBA_INV_FLAG, error) {
	return CORBA_INV_FLAG {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_INV_FLAGValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_INV_FLAG, error) {
	return CORBA_INV_FLAG {
		Minor: minor,
		Completed: completed,
	}, nil
}
//line CORBA_StandardExceptions.idl:46
//Exception Decl: CORBA_INTF_REPOS
//Usage Count: 0
type CORBA_INTF_REPOS struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_INTF_REPOSDefaultPointer() (*CORBA_INTF_REPOS, error) {
	return &CORBA_INTF_REPOS {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_INTF_REPOSDefaultValue() (CORBA_INTF_REPOS, error) {
	return CORBA_INTF_REPOS {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_INTF_REPOSValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_INTF_REPOS, error) {
	return CORBA_INTF_REPOS {
		Minor: minor,
		Completed: completed,
	}, nil
}
//line CORBA_StandardExceptions.idl:48
//Exception Decl: CORBA_BAD_CONTEXT
//Usage Count: 0
type CORBA_BAD_CONTEXT struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_BAD_CONTEXTDefaultPointer() (*CORBA_BAD_CONTEXT, error) {
	return &CORBA_BAD_CONTEXT {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_BAD_CONTEXTDefaultValue() (CORBA_BAD_CONTEXT, error) {
	return CORBA_BAD_CONTEXT {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_BAD_CONTEXTValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_BAD_CONTEXT, error) {
	return CORBA_BAD_CONTEXT {
		Minor: minor,
		Completed: completed,
	}, nil
}
//line CORBA_StandardExceptions.idl:50
//Exception Decl: CORBA_OBJ_ADAPTER
//Usage Count: 0
type CORBA_OBJ_ADAPTER struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_OBJ_ADAPTERDefaultPointer() (*CORBA_OBJ_ADAPTER, error) {
	return &CORBA_OBJ_ADAPTER {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_OBJ_ADAPTERDefaultValue() (CORBA_OBJ_ADAPTER, error) {
	return CORBA_OBJ_ADAPTER {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_OBJ_ADAPTERValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_OBJ_ADAPTER, error) {
	return CORBA_OBJ_ADAPTER {
		Minor: minor,
		Completed: completed,
	}, nil
}
//line CORBA_StandardExceptions.idl:52
//Exception Decl: CORBA_DATA_CONVERSION
//Usage Count: 0
type CORBA_DATA_CONVERSION struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_DATA_CONVERSIONDefaultPointer() (*CORBA_DATA_CONVERSION, error) {
	return &CORBA_DATA_CONVERSION {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_DATA_CONVERSIONDefaultValue() (CORBA_DATA_CONVERSION, error) {
	return CORBA_DATA_CONVERSION {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_DATA_CONVERSIONValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_DATA_CONVERSION, error) {
	return CORBA_DATA_CONVERSION {
		Minor: minor,
		Completed: completed,
	}, nil
}
//line CORBA_StandardExceptions.idl:53
//Exception Decl: CORBA_OBJECT_NOT_EXIST
//Usage Count: 0
type CORBA_OBJECT_NOT_EXIST struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_OBJECT_NOT_EXISTDefaultPointer() (*CORBA_OBJECT_NOT_EXIST, error) {
	return &CORBA_OBJECT_NOT_EXIST {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_OBJECT_NOT_EXISTDefaultValue() (CORBA_OBJECT_NOT_EXIST, error) {
	return CORBA_OBJECT_NOT_EXIST {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_OBJECT_NOT_EXISTValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_OBJECT_NOT_EXIST, error) {
	return CORBA_OBJECT_NOT_EXIST {
		Minor: minor,
		Completed: completed,
	}, nil
}
//line CORBA_StandardExceptions.idl:55
//Exception Decl: CORBA_TRANSACTION_REQUIRED
//Usage Count: 0
type CORBA_TRANSACTION_REQUIRED struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_TRANSACTION_REQUIREDDefaultPointer() (*CORBA_TRANSACTION_REQUIRED, error) {
	return &CORBA_TRANSACTION_REQUIRED {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_TRANSACTION_REQUIREDDefaultValue() (CORBA_TRANSACTION_REQUIRED, error) {
	return CORBA_TRANSACTION_REQUIRED {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_TRANSACTION_REQUIREDValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_TRANSACTION_REQUIRED, error) {
	return CORBA_TRANSACTION_REQUIRED {
		Minor: minor,
		Completed: completed,
	}, nil
}
//line CORBA_StandardExceptions.idl:57
//Exception Decl: CORBA_TRANSACTION_ROLLEDBACK
//Usage Count: 0
type CORBA_TRANSACTION_ROLLEDBACK struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_TRANSACTION_ROLLEDBACKDefaultPointer() (*CORBA_TRANSACTION_ROLLEDBACK, error) {
	return &CORBA_TRANSACTION_ROLLEDBACK {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_TRANSACTION_ROLLEDBACKDefaultValue() (CORBA_TRANSACTION_ROLLEDBACK, error) {
	return CORBA_TRANSACTION_ROLLEDBACK {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_TRANSACTION_ROLLEDBACKValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_TRANSACTION_ROLLEDBACK, error) {
	return CORBA_TRANSACTION_ROLLEDBACK {
		Minor: minor,
		Completed: completed,
	}, nil
}
//line CORBA_StandardExceptions.idl:59
//Exception Decl: CORBA_INVALID_TRANSACTION
//Usage Count: 0
type CORBA_INVALID_TRANSACTION struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_INVALID_TRANSACTIONDefaultPointer() (*CORBA_INVALID_TRANSACTION, error) {
	return &CORBA_INVALID_TRANSACTION {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_INVALID_TRANSACTIONDefaultValue() (CORBA_INVALID_TRANSACTION, error) {
	return CORBA_INVALID_TRANSACTION {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_INVALID_TRANSACTIONValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_INVALID_TRANSACTION, error) {
	return CORBA_INVALID_TRANSACTION {
		Minor: minor,
		Completed: completed,
	}, nil
}
//line CORBA_StandardExceptions.idl:61
//Exception Decl: CORBA_INV_POLICY
//Usage Count: 0
type CORBA_INV_POLICY struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_INV_POLICYDefaultPointer() (*CORBA_INV_POLICY, error) {
	return &CORBA_INV_POLICY {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_INV_POLICYDefaultValue() (CORBA_INV_POLICY, error) {
	return CORBA_INV_POLICY {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_INV_POLICYValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_INV_POLICY, error) {
	return CORBA_INV_POLICY {
		Minor: minor,
		Completed: completed,
	}, nil
}
//line CORBA_StandardExceptions.idl:62
//Exception Decl: CORBA_CODESET_INCOMPATIBLE
//Usage Count: 0
type CORBA_CODESET_INCOMPATIBLE struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_CODESET_INCOMPATIBLEDefaultPointer() (*CORBA_CODESET_INCOMPATIBLE, error) {
	return &CORBA_CODESET_INCOMPATIBLE {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_CODESET_INCOMPATIBLEDefaultValue() (CORBA_CODESET_INCOMPATIBLE, error) {
	return CORBA_CODESET_INCOMPATIBLE {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_CODESET_INCOMPATIBLEValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_CODESET_INCOMPATIBLE, error) {
	return CORBA_CODESET_INCOMPATIBLE {
		Minor: minor,
		Completed: completed,
	}, nil
}
//line CORBA_StandardExceptions.idl:64
//Exception Decl: CORBA_REBIND
//Usage Count: 0
type CORBA_REBIND struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_REBINDDefaultPointer() (*CORBA_REBIND, error) {
	return &CORBA_REBIND {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_REBINDDefaultValue() (CORBA_REBIND, error) {
	return CORBA_REBIND {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_REBINDValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_REBIND, error) {
	return CORBA_REBIND {
		Minor: minor,
		Completed: completed,
	}, nil
}
//line CORBA_StandardExceptions.idl:65
//Exception Decl: CORBA_TIMEOUT
//Usage Count: 0
type CORBA_TIMEOUT struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_TIMEOUTDefaultPointer() (*CORBA_TIMEOUT, error) {
	return &CORBA_TIMEOUT {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_TIMEOUTDefaultValue() (CORBA_TIMEOUT, error) {
	return CORBA_TIMEOUT {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_TIMEOUTValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_TIMEOUT, error) {
	return CORBA_TIMEOUT {
		Minor: minor,
		Completed: completed,
	}, nil
}
//line CORBA_StandardExceptions.idl:66
//Exception Decl: CORBA_TRANSACTION_UNAVAILABLE
//Usage Count: 0
type CORBA_TRANSACTION_UNAVAILABLE struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_TRANSACTION_UNAVAILABLEDefaultPointer() (*CORBA_TRANSACTION_UNAVAILABLE, error) {
	return &CORBA_TRANSACTION_UNAVAILABLE {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_TRANSACTION_UNAVAILABLEDefaultValue() (CORBA_TRANSACTION_UNAVAILABLE, error) {
	return CORBA_TRANSACTION_UNAVAILABLE {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_TRANSACTION_UNAVAILABLEValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_TRANSACTION_UNAVAILABLE, error) {
	return CORBA_TRANSACTION_UNAVAILABLE {
		Minor: minor,
		Completed: completed,
	}, nil
}
//line CORBA_StandardExceptions.idl:68
//Exception Decl: CORBA_TRANSACTION_MODE
//Usage Count: 0
type CORBA_TRANSACTION_MODE struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_TRANSACTION_MODEDefaultPointer() (*CORBA_TRANSACTION_MODE, error) {
	return &CORBA_TRANSACTION_MODE {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_TRANSACTION_MODEDefaultValue() (CORBA_TRANSACTION_MODE, error) {
	return CORBA_TRANSACTION_MODE {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_TRANSACTION_MODEValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_TRANSACTION_MODE, error) {
	return CORBA_TRANSACTION_MODE {
		Minor: minor,
		Completed: completed,
	}, nil
}
//line CORBA_StandardExceptions.idl:69
//Exception Decl: CORBA_BAD_QOS
//Usage Count: 0
type CORBA_BAD_QOS struct {
	Minor uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_BAD_QOSDefaultPointer() (*CORBA_BAD_QOS, error) {
	return &CORBA_BAD_QOS {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_BAD_QOSDefaultValue() (CORBA_BAD_QOS, error) {
	return CORBA_BAD_QOS {
		Minor: 0,
		Completed: place holder,
	}, nil
}

func NewCORBA_BAD_QOSValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_BAD_QOS, error) {
	return CORBA_BAD_QOS {
		Minor: minor,
		Completed: completed,
	}, nil
}
