package corbaFiles

//Code generated by  DO NOT EDIT.
//line CORBA_Pollable.idl:8
//ValueAbsolute Decl: Pollable
//Usage Count: 0
type Pollable interface {
	//line CORBA_Pollable.idl:9
	Is_ready(timeout uint32) (bool, error)
	//line CORBA_Pollable.idl:13
	Create_pollable_set() (PollableSet, error)
}

//line CORBA_Pollable.idl:16
//ValueAbsolute Decl: DIIPollable
//Usage Count: 0
type DIIPollable interface {
}

//line CORBA_Pollable.idl:20
//Exception Decl: CORBA_PollableSet_NoPossiblePollable
//Usage Count: 0
type CORBA_PollableSet_NoPossiblePollable struct {
}

//Constructors
func NewCORBA_PollableSet_NoPossiblePollableDefaultPointer() (*CORBA_PollableSet_NoPossiblePollable, error) {
}

func NewCORBA_PollableSet_NoPossiblePollableDefaultValue() (CORBA_PollableSet_NoPossiblePollable, error) {
}

//line CORBA_Pollable.idl:21
//Exception Decl: CORBA_PollableSet_UnknownPollable
//Usage Count: 0
type CORBA_PollableSet_UnknownPollable struct {
}

//Constructors
func NewCORBA_PollableSet_UnknownPollableDefaultPointer() (*CORBA_PollableSet_UnknownPollable, error) {
}

func NewCORBA_PollableSet_UnknownPollableDefaultValue() (CORBA_PollableSet_UnknownPollable, error) {
}

//line CORBA_Pollable.idl:18
//Interface Decl: PollableSet
//Usage Count: 0
type PollableSet interface {
	//line CORBA_Pollable.idl:23
	Create_dii_pollable() (DIIPollable, error)
	//line CORBA_Pollable.idl:25
	Add_pollable(potential Pollable) (void, error)
	//line CORBA_Pollable.idl:29
	Get_ready_pollable(timeout uint32) (Pollable, error)
	//line CORBA_Pollable.idl:33
	Remove(potential Pollable) (void, error)
	//line CORBA_Pollable.idl:37
	Number_left() (uint16, error)
}
