// Code generated by abc. DO NOT EDIT.

package corbaFiles

//line CORBA_ServerRequest.idl:4
//Interface Decl: ServerRequest
//Usage Count: 0
type ServerRequest interface {

	//line CORBA_ServerRequest.idl:5
	GetOperation() Identifier

	//line CORBA_ServerRequest.idl:6
	Arguments(nv NVList) error

	//line CORBA_ServerRequest.idl:7
	Ctx() (Context, error)

	//line CORBA_ServerRequest.idl:8
	Set_result(val CorbaAny) error

	//line CORBA_ServerRequest.idl:9
	Set_exception(val CorbaAny) error
}
