// Code generated by abc. DO NOT EDIT.

package corbaFiles

//line CORBA_Context.idl:4
//Interface Decl: Context
//Usage Count: 1
type Context interface {

	//line CORBA_Context.idl:5
	Set_one_value(prop_name Identifier, value AnsiString) error

	//line CORBA_Context.idl:9
	Set_values(values NVList) error

	//line CORBA_Context.idl:12
	Get_values(start_scope Identifier, values NVList) error

	//line CORBA_Context.idl:18
	Delete_values(prop_name Identifier) error

	//line CORBA_Context.idl:21
	Create_child(ctx_name Identifier, child_ctx Context) error

	//line CORBA_Context.idl:25
	Delete(del_flags Flags) error
}
