package corbaFiles

//Code generated by  DO NOT EDIT.
//line CORBA_InterfaceRepository.idl:8
//line CORBA_InterfaceRepository.idl:27
//Interface Decl: IRObject
type IRObject interface {
	//line CORBA_InterfaceRepository.idl:29
	//line CORBA_InterfaceRepository.idl:31
	Destroy() (void, error)
}
//line CORBA_InterfaceRepository.idl:46
//Struct Decl: CORBA_Contained_Description
type CORBA_Contained_Description struct {
	Kind DefinitionKind
	Value CorbaAny
}

//Constructors
func NewCORBA_Contained_DescriptionDefaultPointer() (*CORBA_Contained_Description, error) {
	return &CORBA_Contained_Description {
		Kind: need default value for ''
,
		Value: nil,
	}, nil
}

func NewCORBA_Contained_DescriptionDefaultValue() (CORBA_Contained_Description, error) {
	return CORBA_Contained_Description {
		Kind: need default value for ''
,
		Value: nil,
	}, nil
}

func NewCORBA_Contained_DescriptionValue(
	kind DefinitionKind,
	value CorbaAny) (CORBA_Contained_Description, error) {
	return CORBA_Contained_Description {
		Kind: kind,
		Value: value,
	}, nil
}
//line CORBA_InterfaceRepository.idl:36
//Interface Decl: Contained
type Contained interface {
	//line CORBA_InterfaceRepository.idl:39
	//line CORBA_InterfaceRepository.idl:40
	//line CORBA_InterfaceRepository.idl:41
	//line CORBA_InterfaceRepository.idl:43
	//line CORBA_InterfaceRepository.idl:44
	//line CORBA_InterfaceRepository.idl:45
	//line CORBA_InterfaceRepository.idl:50
	Describe() (Description, error)
	//line CORBA_InterfaceRepository.idl:52
	Move(new_container Container,new_version VersionSpec) (void, error)
}
//line CORBA_InterfaceRepository.idl:58
//Forward Interface Decl: ModuleDef
//line CORBA_InterfaceRepository.idl:59
//Forward Interface Decl: ConstantDef
//line CORBA_InterfaceRepository.idl:60
//Forward Interface Decl: IDLType
//line CORBA_InterfaceRepository.idl:61
//Forward Interface Decl: StructDef
//line CORBA_InterfaceRepository.idl:62
//Forward Interface Decl: UnionDef
//line CORBA_InterfaceRepository.idl:63
//Forward Interface Decl: EnumDef
//line CORBA_InterfaceRepository.idl:64
//Forward Interface Decl: AliasDef
//line CORBA_InterfaceRepository.idl:65
//Forward Interface Decl: ExceptionDef
//line CORBA_InterfaceRepository.idl:66
//Forward Interface Decl: NativeDef
//line CORBA_InterfaceRepository.idl:67
//Forward Interface Decl: InterfaceDef
//line CORBA_InterfaceRepository.idl:69
//Forward Interface Decl: ValueDef
//line CORBA_InterfaceRepository.idl:71
//Forward Interface Decl: ValueBoxDef
//line CORBA_InterfaceRepository.idl:72
//Forward Interface Decl: AbstractInterfaceDef
//line CORBA_InterfaceRepository.idl:74
//Forward Interface Decl: LocalInterfaceDef
//line CORBA_InterfaceRepository.idl:76
//Forward Interface Decl: ExtInterfaceDef
//line CORBA_InterfaceRepository.idl:78
//Forward Interface Decl: ExtValueDef
//line CORBA_InterfaceRepository.idl:80
//Forward Interface Decl: ExtAbstractInterfaceDef
//line CORBA_InterfaceRepository.idl:82
//Forward Interface Decl: ExtLocalInterfaceDef
//line CORBA_InterfaceRepository.idl:86
//Struct Decl: CORBA_StructMember
type CORBA_StructMember struct {
	Name Identifier
	Type TypeCode
	Type_def IDLType
}

//Constructors
func NewCORBA_StructMemberDefaultPointer() (*CORBA_StructMember, error) {
	return &CORBA_StructMember {
		Name: need default value for ''
,
		Type: need default value for ''
,
		Type_def: need default value for ''
,
	}, nil
}

func NewCORBA_StructMemberDefaultValue() (CORBA_StructMember, error) {
	return CORBA_StructMember {
		Name: need default value for ''
,
		Type: need default value for ''
,
		Type_def: need default value for ''
,
	}, nil
}

func NewCORBA_StructMemberValue(
	name Identifier,
	type TypeCode,
	type_def IDLType) (CORBA_StructMember, error) {
	return CORBA_StructMember {
		Name: name,
		Type: type,
		Type_def: type_def,
	}, nil
}
//line CORBA_InterfaceRepository.idl:92
//Struct Decl: CORBA_Initializer
type CORBA_Initializer struct {
	Members StructMemberSeq
	Name Identifier
}

//Constructors
func NewCORBA_InitializerDefaultPointer() (*CORBA_Initializer, error) {
	return &CORBA_Initializer {
		Members: need default value for ''
,
		Name: need default value for ''
,
	}, nil
}

func NewCORBA_InitializerDefaultValue() (CORBA_Initializer, error) {
	return CORBA_Initializer {
		Members: need default value for ''
,
		Name: need default value for ''
,
	}, nil
}

func NewCORBA_InitializerValue(
	members StructMemberSeq,
	name Identifier) (CORBA_Initializer, error) {
	return CORBA_Initializer {
		Members: members,
		Name: name,
	}, nil
}
//line CORBA_InterfaceRepository.idl:97
//Struct Decl: CORBA_UnionMember
type CORBA_UnionMember struct {
	Name Identifier
	Label CorbaAny
	Type TypeCode
	Type_def IDLType
}

//Constructors
func NewCORBA_UnionMemberDefaultPointer() (*CORBA_UnionMember, error) {
	return &CORBA_UnionMember {
		Name: need default value for ''
,
		Label: nil,
		Type: need default value for ''
,
		Type_def: need default value for ''
,
	}, nil
}

func NewCORBA_UnionMemberDefaultValue() (CORBA_UnionMember, error) {
	return CORBA_UnionMember {
		Name: need default value for ''
,
		Label: nil,
		Type: need default value for ''
,
		Type_def: need default value for ''
,
	}, nil
}

func NewCORBA_UnionMemberValue(
	name Identifier,
	label CorbaAny,
	type TypeCode,
	type_def IDLType) (CORBA_UnionMember, error) {
	return CORBA_UnionMember {
		Name: name,
		Label: label,
		Type: type,
		Type_def: type_def,
	}, nil
}
//line CORBA_InterfaceRepository.idl:104
//Struct Decl: CORBA_ExceptionDescription
type CORBA_ExceptionDescription struct {
	Name Identifier
	Id RepositoryId
	Defined_in RepositoryId
	Version VersionSpec
	Type TypeCode
}

//Constructors
func NewCORBA_ExceptionDescriptionDefaultPointer() (*CORBA_ExceptionDescription, error) {
	return &CORBA_ExceptionDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Type: need default value for ''
,
	}, nil
}

func NewCORBA_ExceptionDescriptionDefaultValue() (CORBA_ExceptionDescription, error) {
	return CORBA_ExceptionDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Type: need default value for ''
,
	}, nil
}

func NewCORBA_ExceptionDescriptionValue(
	name Identifier,
	id RepositoryId,
	defined_in RepositoryId,
	version VersionSpec,
	type TypeCode) (CORBA_ExceptionDescription, error) {
	return CORBA_ExceptionDescription {
		Name: name,
		Id: id,
		Defined_in: defined_in,
		Version: version,
		Type: type,
	}, nil
}
//line CORBA_InterfaceRepository.idl:114
//Struct Decl: CORBA_ExtInitializer
type CORBA_ExtInitializer struct {
	Members StructMemberSeq
	Exceptions ExcDescriptionSeq
	Name Identifier
}

//Constructors
func NewCORBA_ExtInitializerDefaultPointer() (*CORBA_ExtInitializer, error) {
	return &CORBA_ExtInitializer {
		Members: need default value for ''
,
		Exceptions: need default value for ''
,
		Name: need default value for ''
,
	}, nil
}

func NewCORBA_ExtInitializerDefaultValue() (CORBA_ExtInitializer, error) {
	return CORBA_ExtInitializer {
		Members: need default value for ''
,
		Exceptions: need default value for ''
,
		Name: need default value for ''
,
	}, nil
}

func NewCORBA_ExtInitializerValue(
	members StructMemberSeq,
	exceptions ExcDescriptionSeq,
	name Identifier) (CORBA_ExtInitializer, error) {
	return CORBA_ExtInitializer {
		Members: members,
		Exceptions: exceptions,
		Name: name,
	}, nil
}
//line CORBA_InterfaceRepository.idl:138
//Struct Decl: CORBA_Container_Description
type CORBA_Container_Description struct {
	Contained_object Contained
	Kind DefinitionKind
	Value CorbaAny
}

//Constructors
func NewCORBA_Container_DescriptionDefaultPointer() (*CORBA_Container_Description, error) {
	return &CORBA_Container_Description {
		Contained_object: need default value for ''
,
		Kind: need default value for ''
,
		Value: nil,
	}, nil
}

func NewCORBA_Container_DescriptionDefaultValue() (CORBA_Container_Description, error) {
	return CORBA_Container_Description {
		Contained_object: need default value for ''
,
		Kind: need default value for ''
,
		Value: nil,
	}, nil
}

func NewCORBA_Container_DescriptionValue(
	contained_object Contained,
	kind DefinitionKind,
	value CorbaAny) (CORBA_Container_Description, error) {
	return CORBA_Container_Description {
		Contained_object: contained_object,
		Kind: kind,
		Value: value,
	}, nil
}
//line CORBA_InterfaceRepository.idl:124
//Interface Decl: Container
type Container interface {
	//line CORBA_InterfaceRepository.idl:126
	Lookup(search_name ScopedName) (Contained, error)
	//line CORBA_InterfaceRepository.idl:128
	Contents(limit_type DefinitionKind,exclude_inherited bool) (ContainedSeq, error)
	//line CORBA_InterfaceRepository.idl:132
	Lookup_name(search_name Identifier,exclude_inherited bool) (ContainedSeq, error)
	//line CORBA_InterfaceRepository.idl:143
	//line CORBA_InterfaceRepository.idl:144
	Describe_contents(limit_type DefinitionKind,max_returned_objs int32) (DescriptionSeq, error)
	//line CORBA_InterfaceRepository.idl:150
	Create_module(id RepositoryId,version VersionSpec) (ModuleDef, error)
	//line CORBA_InterfaceRepository.idl:155
	Create_constant(id RepositoryId,value CorbaAny) (ConstantDef, error)
	//line CORBA_InterfaceRepository.idl:162
	Create_struct(id RepositoryId,members StructMemberSeq) (StructDef, error)
	//line CORBA_InterfaceRepository.idl:168
	Create_union(id RepositoryId,members UnionMemberSeq) (UnionDef, error)
	//line CORBA_InterfaceRepository.idl:175
	Create_enum(id RepositoryId,members EnumMemberSeq) (EnumDef, error)
	//line CORBA_InterfaceRepository.idl:181
	Create_alias(id RepositoryId,original_type IDLType) (AliasDef, error)
	//line CORBA_InterfaceRepository.idl:187
	Create_interface(id RepositoryId,is_abstract bool) (InterfaceDef, error)
	//line CORBA_InterfaceRepository.idl:194
	Create_value(id RepositoryId,initializers InitializerSeq) (ValueDef, error)
	//line CORBA_InterfaceRepository.idl:206
	Create_value_box(id RepositoryId,original_type_def IDLType) (ValueBoxDef, error)
	//line CORBA_InterfaceRepository.idl:212
	Create_exception(id RepositoryId,members StructMemberSeq) (ExceptionDef, error)
	//line CORBA_InterfaceRepository.idl:218
	Create_native(id RepositoryId,version VersionSpec) (NativeDef, error)
	//line CORBA_InterfaceRepository.idl:223
	Create_abstract_interface(id RepositoryId,base_interfaces AbstractInterfaceDefSeq) (AbstractInterfaceDef, error)
	//line CORBA_InterfaceRepository.idl:229
	Create_local_interface(id RepositoryId,base_interfaces InterfaceDefSeq) (LocalInterfaceDef, error)
	//line CORBA_InterfaceRepository.idl:235
	Create_ext_value(id RepositoryId,initializers ExtInitializerSeq) (ExtValueDef, error)
}
//line CORBA_InterfaceRepository.idl:248
//Interface Decl: IDLType
type IDLType interface {
	//line CORBA_InterfaceRepository.idl:249
}
//line CORBA_InterfaceRepository.idl:252
//line CORBA_InterfaceRepository.idl:260
//Interface Decl: Repository
type Repository interface {
	//line CORBA_InterfaceRepository.idl:262
	Lookup_id(search_id RepositoryId) (Contained, error)
	//line CORBA_InterfaceRepository.idl:263
	Get_canonical_typecode(tc TypeCode) (TypeCode, error)
	//line CORBA_InterfaceRepository.idl:264
	Get_primitive(kind PrimitiveKind) (PrimitiveDef, error)
	//line CORBA_InterfaceRepository.idl:266
	Create_string(bound uint32) (StringDef, error)
	//line CORBA_InterfaceRepository.idl:267
	Create_wstring(bound uint32) (WstringDef, error)
	//line CORBA_InterfaceRepository.idl:268
	Create_sequence(bound uint32,element_type IDLType) (SequenceDef, error)
	//line CORBA_InterfaceRepository.idl:271
	Create_array(length uint32,element_type IDLType) (ArrayDef, error)
	//line CORBA_InterfaceRepository.idl:274
	Create_fixed(digits uint16,scale int16) (FixedDef, error)
}
//line CORBA_InterfaceRepository.idl:278
//Interface Decl: ModuleDef
type ModuleDef interface {
}
//line CORBA_InterfaceRepository.idl:281
//Struct Decl: CORBA_ModuleDescription
type CORBA_ModuleDescription struct {
	Name Identifier
	Id RepositoryId
	Defined_in RepositoryId
	Version VersionSpec
}

//Constructors
func NewCORBA_ModuleDescriptionDefaultPointer() (*CORBA_ModuleDescription, error) {
	return &CORBA_ModuleDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
	}, nil
}

func NewCORBA_ModuleDescriptionDefaultValue() (CORBA_ModuleDescription, error) {
	return CORBA_ModuleDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
	}, nil
}

func NewCORBA_ModuleDescriptionValue(
	name Identifier,
	id RepositoryId,
	defined_in RepositoryId,
	version VersionSpec) (CORBA_ModuleDescription, error) {
	return CORBA_ModuleDescription {
		Name: name,
		Id: id,
		Defined_in: defined_in,
		Version: version,
	}, nil
}
//line CORBA_InterfaceRepository.idl:288
//Interface Decl: ConstantDef
type ConstantDef interface {
	//line CORBA_InterfaceRepository.idl:289
	//line CORBA_InterfaceRepository.idl:290
	//line CORBA_InterfaceRepository.idl:291
}
//line CORBA_InterfaceRepository.idl:293
//Struct Decl: CORBA_ConstantDescription
type CORBA_ConstantDescription struct {
	Name Identifier
	Id RepositoryId
	Defined_in RepositoryId
	Version VersionSpec
	Type TypeCode
	Value CorbaAny
}

//Constructors
func NewCORBA_ConstantDescriptionDefaultPointer() (*CORBA_ConstantDescription, error) {
	return &CORBA_ConstantDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Type: need default value for ''
,
		Value: nil,
	}, nil
}

func NewCORBA_ConstantDescriptionDefaultValue() (CORBA_ConstantDescription, error) {
	return CORBA_ConstantDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Type: need default value for ''
,
		Value: nil,
	}, nil
}

func NewCORBA_ConstantDescriptionValue(
	name Identifier,
	id RepositoryId,
	defined_in RepositoryId,
	version VersionSpec,
	type TypeCode,
	value CorbaAny) (CORBA_ConstantDescription, error) {
	return CORBA_ConstantDescription {
		Name: name,
		Id: id,
		Defined_in: defined_in,
		Version: version,
		Type: type,
		Value: value,
	}, nil
}
//line CORBA_InterfaceRepository.idl:302
//Interface Decl: TypedefDef
type TypedefDef interface {
}
//line CORBA_InterfaceRepository.idl:305
//Struct Decl: CORBA_TypeDescription
type CORBA_TypeDescription struct {
	Name Identifier
	Id RepositoryId
	Defined_in RepositoryId
	Version VersionSpec
	Type TypeCode
}

//Constructors
func NewCORBA_TypeDescriptionDefaultPointer() (*CORBA_TypeDescription, error) {
	return &CORBA_TypeDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Type: need default value for ''
,
	}, nil
}

func NewCORBA_TypeDescriptionDefaultValue() (CORBA_TypeDescription, error) {
	return CORBA_TypeDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Type: need default value for ''
,
	}, nil
}

func NewCORBA_TypeDescriptionValue(
	name Identifier,
	id RepositoryId,
	defined_in RepositoryId,
	version VersionSpec,
	type TypeCode) (CORBA_TypeDescription, error) {
	return CORBA_TypeDescription {
		Name: name,
		Id: id,
		Defined_in: defined_in,
		Version: version,
		Type: type,
	}, nil
}
//line CORBA_InterfaceRepository.idl:313
//Interface Decl: StructDef
type StructDef interface {
	//line CORBA_InterfaceRepository.idl:314
}
//line CORBA_InterfaceRepository.idl:317
//Interface Decl: UnionDef
type UnionDef interface {
	//line CORBA_InterfaceRepository.idl:318
	//line CORBA_InterfaceRepository.idl:319
	//line CORBA_InterfaceRepository.idl:320
}
//line CORBA_InterfaceRepository.idl:323
//Interface Decl: EnumDef
type EnumDef interface {
	//line CORBA_InterfaceRepository.idl:324
}
//line CORBA_InterfaceRepository.idl:326
//Interface Decl: AliasDef
type AliasDef interface {
	//line CORBA_InterfaceRepository.idl:327
}
//line CORBA_InterfaceRepository.idl:329
//Interface Decl: NativeDef
type NativeDef interface {
}
//line CORBA_InterfaceRepository.idl:331
//Interface Decl: PrimitiveDef
type PrimitiveDef interface {
	//line CORBA_InterfaceRepository.idl:332
}
//line CORBA_InterfaceRepository.idl:334
//Interface Decl: StringDef
type StringDef interface {
	//line CORBA_InterfaceRepository.idl:335
}
//line CORBA_InterfaceRepository.idl:337
//Interface Decl: WstringDef
type WstringDef interface {
	//line CORBA_InterfaceRepository.idl:338
}
//line CORBA_InterfaceRepository.idl:340
//Interface Decl: FixedDef
type FixedDef interface {
	//line CORBA_InterfaceRepository.idl:341
	//line CORBA_InterfaceRepository.idl:342
}
//line CORBA_InterfaceRepository.idl:344
//Interface Decl: SequenceDef
type SequenceDef interface {
	//line CORBA_InterfaceRepository.idl:345
	//line CORBA_InterfaceRepository.idl:346
	//line CORBA_InterfaceRepository.idl:347
}
//line CORBA_InterfaceRepository.idl:349
//Interface Decl: ArrayDef
type ArrayDef interface {
	//line CORBA_InterfaceRepository.idl:350
	//line CORBA_InterfaceRepository.idl:351
	//line CORBA_InterfaceRepository.idl:352
}
//line CORBA_InterfaceRepository.idl:354
//Interface Decl: ExceptionDef
type ExceptionDef interface {
	//line CORBA_InterfaceRepository.idl:355
	//line CORBA_InterfaceRepository.idl:356
}
//line CORBA_InterfaceRepository.idl:358
//line CORBA_InterfaceRepository.idl:359
//Interface Decl: AttributeDef
type AttributeDef interface {
	//line CORBA_InterfaceRepository.idl:360
	//line CORBA_InterfaceRepository.idl:361
	//line CORBA_InterfaceRepository.idl:362
}
//line CORBA_InterfaceRepository.idl:364
//Struct Decl: CORBA_AttributeDescription
type CORBA_AttributeDescription struct {
	Name Identifier
	Id RepositoryId
	Defined_in RepositoryId
	Version VersionSpec
	Type TypeCode
	Mode AttributeMode
}

//Constructors
func NewCORBA_AttributeDescriptionDefaultPointer() (*CORBA_AttributeDescription, error) {
	return &CORBA_AttributeDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Type: need default value for ''
,
		Mode: need default value for ''
,
	}, nil
}

func NewCORBA_AttributeDescriptionDefaultValue() (CORBA_AttributeDescription, error) {
	return CORBA_AttributeDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Type: need default value for ''
,
		Mode: need default value for ''
,
	}, nil
}

func NewCORBA_AttributeDescriptionValue(
	name Identifier,
	id RepositoryId,
	defined_in RepositoryId,
	version VersionSpec,
	type TypeCode,
	mode AttributeMode) (CORBA_AttributeDescription, error) {
	return CORBA_AttributeDescription {
		Name: name,
		Id: id,
		Defined_in: defined_in,
		Version: version,
		Type: type,
		Mode: mode,
	}, nil
}
//line CORBA_InterfaceRepository.idl:372
//Struct Decl: CORBA_ExtAttributeDescription
type CORBA_ExtAttributeDescription struct {
	Name Identifier
	Id RepositoryId
	Defined_in RepositoryId
	Version VersionSpec
	Type TypeCode
	Mode AttributeMode
	Get_exceptions ExcDescriptionSeq
	Put_exceptions ExcDescriptionSeq
}

//Constructors
func NewCORBA_ExtAttributeDescriptionDefaultPointer() (*CORBA_ExtAttributeDescription, error) {
	return &CORBA_ExtAttributeDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Type: need default value for ''
,
		Mode: need default value for ''
,
		Get_exceptions: need default value for ''
,
		Put_exceptions: need default value for ''
,
	}, nil
}

func NewCORBA_ExtAttributeDescriptionDefaultValue() (CORBA_ExtAttributeDescription, error) {
	return CORBA_ExtAttributeDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Type: need default value for ''
,
		Mode: need default value for ''
,
		Get_exceptions: need default value for ''
,
		Put_exceptions: need default value for ''
,
	}, nil
}

func NewCORBA_ExtAttributeDescriptionValue(
	name Identifier,
	id RepositoryId,
	defined_in RepositoryId,
	version VersionSpec,
	type TypeCode,
	mode AttributeMode,
	get_exceptions ExcDescriptionSeq,
	put_exceptions ExcDescriptionSeq) (CORBA_ExtAttributeDescription, error) {
	return CORBA_ExtAttributeDescription {
		Name: name,
		Id: id,
		Defined_in: defined_in,
		Version: version,
		Type: type,
		Mode: mode,
		Get_exceptions: get_exceptions,
		Put_exceptions: put_exceptions,
	}, nil
}
//line CORBA_InterfaceRepository.idl:382
//Interface Decl: CORBA_ExtAttributeDef
type CORBA_ExtAttributeDef interface {
	//line CORBA_InterfaceRepository.idl:384
	//line CORBA_InterfaceRepository.idl:385
	//line CORBA_InterfaceRepository.idl:387
	Describe_attribute() (ExtAttributeDescription, error)
}
//line CORBA_InterfaceRepository.idl:389
//line CORBA_InterfaceRepository.idl:390
//line CORBA_InterfaceRepository.idl:391
//Struct Decl: CORBA_ParameterDescription
type CORBA_ParameterDescription struct {
	Name Identifier
	Type TypeCode
	Type_def IDLType
	Mode ParameterMode
}

//Constructors
func NewCORBA_ParameterDescriptionDefaultPointer() (*CORBA_ParameterDescription, error) {
	return &CORBA_ParameterDescription {
		Name: need default value for ''
,
		Type: need default value for ''
,
		Type_def: need default value for ''
,
		Mode: need default value for ''
,
	}, nil
}

func NewCORBA_ParameterDescriptionDefaultValue() (CORBA_ParameterDescription, error) {
	return CORBA_ParameterDescription {
		Name: need default value for ''
,
		Type: need default value for ''
,
		Type_def: need default value for ''
,
		Mode: need default value for ''
,
	}, nil
}

func NewCORBA_ParameterDescriptionValue(
	name Identifier,
	type TypeCode,
	type_def IDLType,
	mode ParameterMode) (CORBA_ParameterDescription, error) {
	return CORBA_ParameterDescription {
		Name: name,
		Type: type,
		Type_def: type_def,
		Mode: mode,
	}, nil
}
//line CORBA_InterfaceRepository.idl:402
//Interface Decl: OperationDef
type OperationDef interface {
	//line CORBA_InterfaceRepository.idl:403
	//line CORBA_InterfaceRepository.idl:404
	//line CORBA_InterfaceRepository.idl:405
	//line CORBA_InterfaceRepository.idl:406
	//line CORBA_InterfaceRepository.idl:407
	//line CORBA_InterfaceRepository.idl:408
}
//line CORBA_InterfaceRepository.idl:411
//Struct Decl: CORBA_OperationDescription
type CORBA_OperationDescription struct {
	Name Identifier
	Id RepositoryId
	Defined_in RepositoryId
	Version VersionSpec
	Result TypeCode
	Mode OperationMode
	Contexts ContextIdSeq
	Parameters ParDescriptionSeq
	Exceptions ExcDescriptionSeq
}

//Constructors
func NewCORBA_OperationDescriptionDefaultPointer() (*CORBA_OperationDescription, error) {
	return &CORBA_OperationDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Result: need default value for ''
,
		Mode: need default value for ''
,
		Contexts: need default value for ''
,
		Parameters: need default value for ''
,
		Exceptions: need default value for ''
,
	}, nil
}

func NewCORBA_OperationDescriptionDefaultValue() (CORBA_OperationDescription, error) {
	return CORBA_OperationDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Result: need default value for ''
,
		Mode: need default value for ''
,
		Contexts: need default value for ''
,
		Parameters: need default value for ''
,
		Exceptions: need default value for ''
,
	}, nil
}

func NewCORBA_OperationDescriptionValue(
	name Identifier,
	id RepositoryId,
	defined_in RepositoryId,
	version VersionSpec,
	result TypeCode,
	mode OperationMode,
	contexts ContextIdSeq,
	parameters ParDescriptionSeq,
	exceptions ExcDescriptionSeq) (CORBA_OperationDescription, error) {
	return CORBA_OperationDescription {
		Name: name,
		Id: id,
		Defined_in: defined_in,
		Version: version,
		Result: result,
		Mode: mode,
		Contexts: contexts,
		Parameters: parameters,
		Exceptions: exceptions,
	}, nil
}
//line CORBA_InterfaceRepository.idl:434
//Struct Decl: CORBA_InterfaceDef_FullInterfaceDescription
type CORBA_InterfaceDef_FullInterfaceDescription struct {
	Name Identifier
	Id RepositoryId
	Defined_in RepositoryId
	Version VersionSpec
	Operations OpDescriptionSeq
	Attributes AttrDescriptionSeq
	Base_interfaces RepositoryIdSeq
	Type TypeCode
	Is_abstract bool
}

//Constructors
func NewCORBA_InterfaceDef_FullInterfaceDescriptionDefaultPointer() (*CORBA_InterfaceDef_FullInterfaceDescription, error) {
	return &CORBA_InterfaceDef_FullInterfaceDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Operations: need default value for ''
,
		Attributes: need default value for ''
,
		Base_interfaces: need default value for ''
,
		Type: need default value for ''
,
		Is_abstract: false,
	}, nil
}

func NewCORBA_InterfaceDef_FullInterfaceDescriptionDefaultValue() (CORBA_InterfaceDef_FullInterfaceDescription, error) {
	return CORBA_InterfaceDef_FullInterfaceDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Operations: need default value for ''
,
		Attributes: need default value for ''
,
		Base_interfaces: need default value for ''
,
		Type: need default value for ''
,
		Is_abstract: false,
	}, nil
}

func NewCORBA_InterfaceDef_FullInterfaceDescriptionValue(
	name Identifier,
	id RepositoryId,
	defined_in RepositoryId,
	version VersionSpec,
	operations OpDescriptionSeq,
	attributes AttrDescriptionSeq,
	base_interfaces RepositoryIdSeq,
	type TypeCode,
	is_abstract bool) (CORBA_InterfaceDef_FullInterfaceDescription, error) {
	return CORBA_InterfaceDef_FullInterfaceDescription {
		Name: name,
		Id: id,
		Defined_in: defined_in,
		Version: version,
		Operations: operations,
		Attributes: attributes,
		Base_interfaces: base_interfaces,
		Type: type,
		Is_abstract: is_abstract,
	}, nil
}
//line CORBA_InterfaceRepository.idl:427
//Interface Decl: InterfaceDef
type InterfaceDef interface {
	//line CORBA_InterfaceRepository.idl:429
	//line CORBA_InterfaceRepository.idl:430
	//line CORBA_InterfaceRepository.idl:432
	Is_a(interface_id RepositoryId) (bool, error)
	//line CORBA_InterfaceRepository.idl:445
	Describe_interface() (FullInterfaceDescription, error)
	//line CORBA_InterfaceRepository.idl:447
	Create_attribute(id RepositoryId,mode AttributeMode) (AttributeDef, error)
	//line CORBA_InterfaceRepository.idl:454
	Create_operation(id RepositoryId,contexts ContextIdSeq) (OperationDef, error)
}
//line CORBA_InterfaceRepository.idl:465
//Struct Decl: CORBA_InterfaceDescription
type CORBA_InterfaceDescription struct {
	Name Identifier
	Id RepositoryId
	Defined_in RepositoryId
	Version VersionSpec
	Base_interfaces RepositoryIdSeq
	Is_abstract bool
}

//Constructors
func NewCORBA_InterfaceDescriptionDefaultPointer() (*CORBA_InterfaceDescription, error) {
	return &CORBA_InterfaceDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Base_interfaces: need default value for ''
,
		Is_abstract: false,
	}, nil
}

func NewCORBA_InterfaceDescriptionDefaultValue() (CORBA_InterfaceDescription, error) {
	return CORBA_InterfaceDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Base_interfaces: need default value for ''
,
		Is_abstract: false,
	}, nil
}

func NewCORBA_InterfaceDescriptionValue(
	name Identifier,
	id RepositoryId,
	defined_in RepositoryId,
	version VersionSpec,
	base_interfaces RepositoryIdSeq,
	is_abstract bool) (CORBA_InterfaceDescription, error) {
	return CORBA_InterfaceDescription {
		Name: name,
		Id: id,
		Defined_in: defined_in,
		Version: version,
		Base_interfaces: base_interfaces,
		Is_abstract: is_abstract,
	}, nil
}
//line CORBA_InterfaceRepository.idl:476
//Struct Decl: CORBA_InterfaceAttrExtension_ExtFullInterfaceDescription
type CORBA_InterfaceAttrExtension_ExtFullInterfaceDescription struct {
	Name Identifier
	Id RepositoryId
	Defined_in RepositoryId
	Version VersionSpec
	Operations OpDescriptionSeq
	Attributes ExtAttrDescriptionSeq
	Base_interfaces RepositoryIdSeq
	Type TypeCode
}

//Constructors
func NewCORBA_InterfaceAttrExtension_ExtFullInterfaceDescriptionDefaultPointer() (*CORBA_InterfaceAttrExtension_ExtFullInterfaceDescription, error) {
	return &CORBA_InterfaceAttrExtension_ExtFullInterfaceDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Operations: need default value for ''
,
		Attributes: need default value for ''
,
		Base_interfaces: need default value for ''
,
		Type: need default value for ''
,
	}, nil
}

func NewCORBA_InterfaceAttrExtension_ExtFullInterfaceDescriptionDefaultValue() (CORBA_InterfaceAttrExtension_ExtFullInterfaceDescription, error) {
	return CORBA_InterfaceAttrExtension_ExtFullInterfaceDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Operations: need default value for ''
,
		Attributes: need default value for ''
,
		Base_interfaces: need default value for ''
,
		Type: need default value for ''
,
	}, nil
}

func NewCORBA_InterfaceAttrExtension_ExtFullInterfaceDescriptionValue(
	name Identifier,
	id RepositoryId,
	defined_in RepositoryId,
	version VersionSpec,
	operations OpDescriptionSeq,
	attributes ExtAttrDescriptionSeq,
	base_interfaces RepositoryIdSeq,
	type TypeCode) (CORBA_InterfaceAttrExtension_ExtFullInterfaceDescription, error) {
	return CORBA_InterfaceAttrExtension_ExtFullInterfaceDescription {
		Name: name,
		Id: id,
		Defined_in: defined_in,
		Version: version,
		Operations: operations,
		Attributes: attributes,
		Base_interfaces: base_interfaces,
		Type: type,
	}, nil
}
//line CORBA_InterfaceRepository.idl:474
//Interface Decl: CORBA_InterfaceAttrExtension
type CORBA_InterfaceAttrExtension interface {
	//line CORBA_InterfaceRepository.idl:486
	Describe_ext_interface() (ExtFullInterfaceDescription, error)
	//line CORBA_InterfaceRepository.idl:488
	Create_ext_attribute(id RepositoryId,set_exceptions ExceptionDefSeq) (ExtAttributeDef, error)
}
//line CORBA_InterfaceRepository.idl:499
//Interface Decl: ExtInterfaceDef
type ExtInterfaceDef interface {
}
//line CORBA_InterfaceRepository.idl:505
//Struct Decl: CORBA_ValueMember
type CORBA_ValueMember struct {
	Name Identifier
	Id RepositoryId
	Defined_in RepositoryId
	Version VersionSpec
	Type TypeCode
	Type_def IDLType
	Access Visibility
}

//Constructors
func NewCORBA_ValueMemberDefaultPointer() (*CORBA_ValueMember, error) {
	return &CORBA_ValueMember {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Type: need default value for ''
,
		Type_def: need default value for ''
,
		Access: need default value for ''
,
	}, nil
}

func NewCORBA_ValueMemberDefaultValue() (CORBA_ValueMember, error) {
	return CORBA_ValueMember {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Type: need default value for ''
,
		Type_def: need default value for ''
,
		Access: need default value for ''
,
	}, nil
}

func NewCORBA_ValueMemberValue(
	name Identifier,
	id RepositoryId,
	defined_in RepositoryId,
	version VersionSpec,
	type TypeCode,
	type_def IDLType,
	access Visibility) (CORBA_ValueMember, error) {
	return CORBA_ValueMember {
		Name: name,
		Id: id,
		Defined_in: defined_in,
		Version: version,
		Type: type,
		Type_def: type_def,
		Access: access,
	}, nil
}
//line CORBA_InterfaceRepository.idl:515
//Interface Decl: ValueMemberDef
type ValueMemberDef interface {
	//line CORBA_InterfaceRepository.idl:516
	//line CORBA_InterfaceRepository.idl:517
	//line CORBA_InterfaceRepository.idl:518
}
//line CORBA_InterfaceRepository.idl:531
//Struct Decl: CORBA_ValueDef_FullValueDescription
type CORBA_ValueDef_FullValueDescription struct {
	Name Identifier
	Id RepositoryId
	Is_abstract bool
	Is_custom bool
	Defined_in RepositoryId
	Version VersionSpec
	Operations OpDescriptionSeq
	Attributes AttrDescriptionSeq
	Members ValueMemberSeq
	Initializers InitializerSeq
	Supported_interfaces RepositoryIdSeq
	Abstract_base_values RepositoryIdSeq
	Is_truncatable bool
	Base_value RepositoryId
	Type TypeCode
}

//Constructors
func NewCORBA_ValueDef_FullValueDescriptionDefaultPointer() (*CORBA_ValueDef_FullValueDescription, error) {
	return &CORBA_ValueDef_FullValueDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Is_abstract: false,
		Is_custom: false,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Operations: need default value for ''
,
		Attributes: need default value for ''
,
		Members: need default value for ''
,
		Initializers: need default value for ''
,
		Supported_interfaces: need default value for ''
,
		Abstract_base_values: need default value for ''
,
		Is_truncatable: false,
		Base_value: need default value for ''
,
		Type: need default value for ''
,
	}, nil
}

func NewCORBA_ValueDef_FullValueDescriptionDefaultValue() (CORBA_ValueDef_FullValueDescription, error) {
	return CORBA_ValueDef_FullValueDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Is_abstract: false,
		Is_custom: false,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Operations: need default value for ''
,
		Attributes: need default value for ''
,
		Members: need default value for ''
,
		Initializers: need default value for ''
,
		Supported_interfaces: need default value for ''
,
		Abstract_base_values: need default value for ''
,
		Is_truncatable: false,
		Base_value: need default value for ''
,
		Type: need default value for ''
,
	}, nil
}

func NewCORBA_ValueDef_FullValueDescriptionValue(
	name Identifier,
	id RepositoryId,
	is_abstract bool,
	is_custom bool,
	defined_in RepositoryId,
	version VersionSpec,
	operations OpDescriptionSeq,
	attributes AttrDescriptionSeq,
	members ValueMemberSeq,
	initializers InitializerSeq,
	supported_interfaces RepositoryIdSeq,
	abstract_base_values RepositoryIdSeq,
	is_truncatable bool,
	base_value RepositoryId,
	type TypeCode) (CORBA_ValueDef_FullValueDescription, error) {
	return CORBA_ValueDef_FullValueDescription {
		Name: name,
		Id: id,
		Is_abstract: is_abstract,
		Is_custom: is_custom,
		Defined_in: defined_in,
		Version: version,
		Operations: operations,
		Attributes: attributes,
		Members: members,
		Initializers: initializers,
		Supported_interfaces: supported_interfaces,
		Abstract_base_values: abstract_base_values,
		Is_truncatable: is_truncatable,
		Base_value: base_value,
		Type: type,
	}, nil
}
//line CORBA_InterfaceRepository.idl:520
//Interface Decl: ValueDef
type ValueDef interface {
	//line CORBA_InterfaceRepository.idl:522
	//line CORBA_InterfaceRepository.idl:523
	//line CORBA_InterfaceRepository.idl:524
	//line CORBA_InterfaceRepository.idl:525
	//line CORBA_InterfaceRepository.idl:526
	//line CORBA_InterfaceRepository.idl:527
	//line CORBA_InterfaceRepository.idl:528
	//line CORBA_InterfaceRepository.idl:530
	Is_a(id RepositoryId) (bool, error)
	//line CORBA_InterfaceRepository.idl:548
	Describe_value() (FullValueDescription, error)
	//line CORBA_InterfaceRepository.idl:549
	Create_value_member(id RepositoryId,access Visibility) (ValueMemberDef, error)
	//line CORBA_InterfaceRepository.idl:556
	Create_attribute(id RepositoryId,mode AttributeMode) (AttributeDef, error)
	//line CORBA_InterfaceRepository.idl:563
	Create_operation(id RepositoryId,contexts ContextIdSeq) (OperationDef, error)
}
//line CORBA_InterfaceRepository.idl:574
//Struct Decl: CORBA_ValueDescription
type CORBA_ValueDescription struct {
	Name Identifier
	Id RepositoryId
	Is_abstract bool
	Is_custom bool
	Defined_in RepositoryId
	Version VersionSpec
	Supported_interfaces RepositoryIdSeq
	Abstract_base_values RepositoryIdSeq
	Is_truncatable bool
	Base_value RepositoryId
}

//Constructors
func NewCORBA_ValueDescriptionDefaultPointer() (*CORBA_ValueDescription, error) {
	return &CORBA_ValueDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Is_abstract: false,
		Is_custom: false,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Supported_interfaces: need default value for ''
,
		Abstract_base_values: need default value for ''
,
		Is_truncatable: false,
		Base_value: need default value for ''
,
	}, nil
}

func NewCORBA_ValueDescriptionDefaultValue() (CORBA_ValueDescription, error) {
	return CORBA_ValueDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Is_abstract: false,
		Is_custom: false,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Supported_interfaces: need default value for ''
,
		Abstract_base_values: need default value for ''
,
		Is_truncatable: false,
		Base_value: need default value for ''
,
	}, nil
}

func NewCORBA_ValueDescriptionValue(
	name Identifier,
	id RepositoryId,
	is_abstract bool,
	is_custom bool,
	defined_in RepositoryId,
	version VersionSpec,
	supported_interfaces RepositoryIdSeq,
	abstract_base_values RepositoryIdSeq,
	is_truncatable bool,
	base_value RepositoryId) (CORBA_ValueDescription, error) {
	return CORBA_ValueDescription {
		Name: name,
		Id: id,
		Is_abstract: is_abstract,
		Is_custom: is_custom,
		Defined_in: defined_in,
		Version: version,
		Supported_interfaces: supported_interfaces,
		Abstract_base_values: abstract_base_values,
		Is_truncatable: is_truncatable,
		Base_value: base_value,
	}, nil
}
//line CORBA_InterfaceRepository.idl:591
//Struct Decl: CORBA_ExtValueDef_ExtFullValueDescription
type CORBA_ExtValueDef_ExtFullValueDescription struct {
	Name Identifier
	Id RepositoryId
	Is_abstract bool
	Is_custom bool
	Defined_in RepositoryId
	Version VersionSpec
	Operations OpDescriptionSeq
	Attributes ExtAttrDescriptionSeq
	Members ValueMemberSeq
	Initializers ExtInitializerSeq
	Supported_interfaces RepositoryIdSeq
	Abstract_base_values RepositoryIdSeq
	Is_truncatable bool
	Base_value RepositoryId
	Type TypeCode
}

//Constructors
func NewCORBA_ExtValueDef_ExtFullValueDescriptionDefaultPointer() (*CORBA_ExtValueDef_ExtFullValueDescription, error) {
	return &CORBA_ExtValueDef_ExtFullValueDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Is_abstract: false,
		Is_custom: false,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Operations: need default value for ''
,
		Attributes: need default value for ''
,
		Members: need default value for ''
,
		Initializers: need default value for ''
,
		Supported_interfaces: need default value for ''
,
		Abstract_base_values: need default value for ''
,
		Is_truncatable: false,
		Base_value: need default value for ''
,
		Type: need default value for ''
,
	}, nil
}

func NewCORBA_ExtValueDef_ExtFullValueDescriptionDefaultValue() (CORBA_ExtValueDef_ExtFullValueDescription, error) {
	return CORBA_ExtValueDef_ExtFullValueDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Is_abstract: false,
		Is_custom: false,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Operations: need default value for ''
,
		Attributes: need default value for ''
,
		Members: need default value for ''
,
		Initializers: need default value for ''
,
		Supported_interfaces: need default value for ''
,
		Abstract_base_values: need default value for ''
,
		Is_truncatable: false,
		Base_value: need default value for ''
,
		Type: need default value for ''
,
	}, nil
}

func NewCORBA_ExtValueDef_ExtFullValueDescriptionValue(
	name Identifier,
	id RepositoryId,
	is_abstract bool,
	is_custom bool,
	defined_in RepositoryId,
	version VersionSpec,
	operations OpDescriptionSeq,
	attributes ExtAttrDescriptionSeq,
	members ValueMemberSeq,
	initializers ExtInitializerSeq,
	supported_interfaces RepositoryIdSeq,
	abstract_base_values RepositoryIdSeq,
	is_truncatable bool,
	base_value RepositoryId,
	type TypeCode) (CORBA_ExtValueDef_ExtFullValueDescription, error) {
	return CORBA_ExtValueDef_ExtFullValueDescription {
		Name: name,
		Id: id,
		Is_abstract: is_abstract,
		Is_custom: is_custom,
		Defined_in: defined_in,
		Version: version,
		Operations: operations,
		Attributes: attributes,
		Members: members,
		Initializers: initializers,
		Supported_interfaces: supported_interfaces,
		Abstract_base_values: abstract_base_values,
		Is_truncatable: is_truncatable,
		Base_value: base_value,
		Type: type,
	}, nil
}
//line CORBA_InterfaceRepository.idl:587
//Interface Decl: ExtValueDef
type ExtValueDef interface {
	//line CORBA_InterfaceRepository.idl:589
	//line CORBA_InterfaceRepository.idl:608
	Describe_ext_value() (ExtFullValueDescription, error)
	//line CORBA_InterfaceRepository.idl:610
	Create_ext_attribute(id RepositoryId,set_exceptions ExceptionDefSeq) (ExtAttributeDef, error)
}
//line CORBA_InterfaceRepository.idl:621
//Interface Decl: ValueBoxDef
type ValueBoxDef interface {
	//line CORBA_InterfaceRepository.idl:622
}
//line CORBA_InterfaceRepository.idl:624
//Interface Decl: AbstractInterfaceDef
type AbstractInterfaceDef interface {
}
//line CORBA_InterfaceRepository.idl:626
//Interface Decl: ExtAbstractInterfaceDef
type ExtAbstractInterfaceDef interface {
}
//line CORBA_InterfaceRepository.idl:629
//Interface Decl: LocalInterfaceDef
type LocalInterfaceDef interface {
}
//line CORBA_InterfaceRepository.idl:631
//Interface Decl: ExtLocalInterfaceDef
type ExtLocalInterfaceDef interface {
}
//line CORBA_InterfaceRepository.idl:639
//Forward Interface Decl: CORBA_ComponentIR_ComponentDef
//line CORBA_InterfaceRepository.idl:640
//Forward Interface Decl: CORBA_ComponentIR_HomeDef
//line CORBA_InterfaceRepository.idl:641
//Interface Decl: CORBA_ComponentIR_EventDef
type CORBA_ComponentIR_EventDef interface {
}
//line CORBA_InterfaceRepository.idl:642
//Interface Decl: Container
type Container interface {
	//line CORBA_InterfaceRepository.idl:643
	Create_component(id RepositoryId,supports_interfaces InterfaceDefSeq) (ComponentDef, error)
	//line CORBA_InterfaceRepository.idl:650
	Create_home(id RepositoryId,primary_key ValueDef) (HomeDef, error)
	//line CORBA_InterfaceRepository.idl:659
	Create_event(id RepositoryId,initializers ExtInitializerSeq) (EventDef, error)
}
//line CORBA_InterfaceRepository.idl:672
//Interface Decl: ModuleDef
type ModuleDef interface {
}
//line CORBA_InterfaceRepository.idl:673
//Interface Decl: Repository
type Repository interface {
}
//line CORBA_InterfaceRepository.idl:674
//Interface Decl: CORBA_ComponentIR_ProvidesDef
type CORBA_ComponentIR_ProvidesDef interface {
	//line CORBA_InterfaceRepository.idl:675
}
//line CORBA_InterfaceRepository.idl:677
//Struct Decl: CORBA_ComponentIR_ProvidesDescription
type CORBA_ComponentIR_ProvidesDescription struct {
	Name Identifier
	Id RepositoryId
	Defined_in RepositoryId
	Version VersionSpec
	Interface_type RepositoryId
}

//Constructors
func NewCORBA_ComponentIR_ProvidesDescriptionDefaultPointer() (*CORBA_ComponentIR_ProvidesDescription, error) {
	return &CORBA_ComponentIR_ProvidesDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Interface_type: need default value for ''
,
	}, nil
}

func NewCORBA_ComponentIR_ProvidesDescriptionDefaultValue() (CORBA_ComponentIR_ProvidesDescription, error) {
	return CORBA_ComponentIR_ProvidesDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Interface_type: need default value for ''
,
	}, nil
}

func NewCORBA_ComponentIR_ProvidesDescriptionValue(
	name Identifier,
	id RepositoryId,
	defined_in RepositoryId,
	version VersionSpec,
	interface_type RepositoryId) (CORBA_ComponentIR_ProvidesDescription, error) {
	return CORBA_ComponentIR_ProvidesDescription {
		Name: name,
		Id: id,
		Defined_in: defined_in,
		Version: version,
		Interface_type: interface_type,
	}, nil
}
//line CORBA_InterfaceRepository.idl:684
//Interface Decl: CORBA_ComponentIR_UsesDef
type CORBA_ComponentIR_UsesDef interface {
	//line CORBA_InterfaceRepository.idl:685
	//line CORBA_InterfaceRepository.idl:686
}
//line CORBA_InterfaceRepository.idl:688
//Struct Decl: CORBA_ComponentIR_UsesDescription
type CORBA_ComponentIR_UsesDescription struct {
	Name Identifier
	Id RepositoryId
	Defined_in RepositoryId
	Version VersionSpec
	Interface_type RepositoryId
	Is_multiple bool
}

//Constructors
func NewCORBA_ComponentIR_UsesDescriptionDefaultPointer() (*CORBA_ComponentIR_UsesDescription, error) {
	return &CORBA_ComponentIR_UsesDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Interface_type: need default value for ''
,
		Is_multiple: false,
	}, nil
}

func NewCORBA_ComponentIR_UsesDescriptionDefaultValue() (CORBA_ComponentIR_UsesDescription, error) {
	return CORBA_ComponentIR_UsesDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Interface_type: need default value for ''
,
		Is_multiple: false,
	}, nil
}

func NewCORBA_ComponentIR_UsesDescriptionValue(
	name Identifier,
	id RepositoryId,
	defined_in RepositoryId,
	version VersionSpec,
	interface_type RepositoryId,
	is_multiple bool) (CORBA_ComponentIR_UsesDescription, error) {
	return CORBA_ComponentIR_UsesDescription {
		Name: name,
		Id: id,
		Defined_in: defined_in,
		Version: version,
		Interface_type: interface_type,
		Is_multiple: is_multiple,
	}, nil
}
//line CORBA_InterfaceRepository.idl:696
//Interface Decl: CORBA_ComponentIR_EventPortDef
type CORBA_ComponentIR_EventPortDef interface {
	//line CORBA_InterfaceRepository.idl:698
	//line CORBA_InterfaceRepository.idl:700
	Is_a(event_id RepositoryId) (bool, error)
}
//line CORBA_InterfaceRepository.idl:702
//Struct Decl: CORBA_ComponentIR_EventPortDescription
type CORBA_ComponentIR_EventPortDescription struct {
	Name Identifier
	Id RepositoryId
	Defined_in RepositoryId
	Version VersionSpec
	Event RepositoryId
}

//Constructors
func NewCORBA_ComponentIR_EventPortDescriptionDefaultPointer() (*CORBA_ComponentIR_EventPortDescription, error) {
	return &CORBA_ComponentIR_EventPortDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Event: need default value for ''
,
	}, nil
}

func NewCORBA_ComponentIR_EventPortDescriptionDefaultValue() (CORBA_ComponentIR_EventPortDescription, error) {
	return CORBA_ComponentIR_EventPortDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Event: need default value for ''
,
	}, nil
}

func NewCORBA_ComponentIR_EventPortDescriptionValue(
	name Identifier,
	id RepositoryId,
	defined_in RepositoryId,
	version VersionSpec,
	event RepositoryId) (CORBA_ComponentIR_EventPortDescription, error) {
	return CORBA_ComponentIR_EventPortDescription {
		Name: name,
		Id: id,
		Defined_in: defined_in,
		Version: version,
		Event: event,
	}, nil
}
//line CORBA_InterfaceRepository.idl:709
//Interface Decl: CORBA_ComponentIR_EmitsDef
type CORBA_ComponentIR_EmitsDef interface {
}
//line CORBA_InterfaceRepository.idl:710
//Interface Decl: CORBA_ComponentIR_PublishesDef
type CORBA_ComponentIR_PublishesDef interface {
}
//line CORBA_InterfaceRepository.idl:711
//Interface Decl: CORBA_ComponentIR_ConsumesDef
type CORBA_ComponentIR_ConsumesDef interface {
}
//line CORBA_InterfaceRepository.idl:712
//Interface Decl: ComponentDef
type ComponentDef interface {
	//line CORBA_InterfaceRepository.idl:714
	//line CORBA_InterfaceRepository.idl:715
	//line CORBA_InterfaceRepository.idl:717
	Create_provides(id RepositoryId,interface_type InterfaceDef) (ProvidesDef, error)
	//line CORBA_InterfaceRepository.idl:723
	Create_uses(id RepositoryId,is_multiple bool) (UsesDef, error)
	//line CORBA_InterfaceRepository.idl:730
	Create_emits(id RepositoryId,event EventDef) (EmitsDef, error)
	//line CORBA_InterfaceRepository.idl:736
	Create_publishes(id RepositoryId,event EventDef) (PublishesDef, error)
	//line CORBA_InterfaceRepository.idl:742
	Create_consumes(id RepositoryId,event EventDef) (ConsumesDef, error)
}
//line CORBA_InterfaceRepository.idl:754
//Struct Decl: CORBA_ComponentIR_ComponentDescription
type CORBA_ComponentIR_ComponentDescription struct {
	Name Identifier
	Id RepositoryId
	Defined_in RepositoryId
	Version VersionSpec
	Base_component RepositoryId
	Supported_interfaces RepositoryIdSeq
	Provided_interfaces ProvidesDescriptionSeq
	Used_interfaces UsesDescriptionSeq
	Emits_events EventPortDescriptionSeq
	Publishes_events EventPortDescriptionSeq
	Consumes_events EventPortDescriptionSeq
	Attributes ExtAttrDescriptionSeq
	Type TypeCode
}

//Constructors
func NewCORBA_ComponentIR_ComponentDescriptionDefaultPointer() (*CORBA_ComponentIR_ComponentDescription, error) {
	return &CORBA_ComponentIR_ComponentDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Base_component: need default value for ''
,
		Supported_interfaces: need default value for ''
,
		Provided_interfaces: need default value for ''
,
		Used_interfaces: need default value for ''
,
		Emits_events: need default value for ''
,
		Publishes_events: need default value for ''
,
		Consumes_events: need default value for ''
,
		Attributes: need default value for ''
,
		Type: need default value for ''
,
	}, nil
}

func NewCORBA_ComponentIR_ComponentDescriptionDefaultValue() (CORBA_ComponentIR_ComponentDescription, error) {
	return CORBA_ComponentIR_ComponentDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Base_component: need default value for ''
,
		Supported_interfaces: need default value for ''
,
		Provided_interfaces: need default value for ''
,
		Used_interfaces: need default value for ''
,
		Emits_events: need default value for ''
,
		Publishes_events: need default value for ''
,
		Consumes_events: need default value for ''
,
		Attributes: need default value for ''
,
		Type: need default value for ''
,
	}, nil
}

func NewCORBA_ComponentIR_ComponentDescriptionValue(
	name Identifier,
	id RepositoryId,
	defined_in RepositoryId,
	version VersionSpec,
	base_component RepositoryId,
	supported_interfaces RepositoryIdSeq,
	provided_interfaces ProvidesDescriptionSeq,
	used_interfaces UsesDescriptionSeq,
	emits_events EventPortDescriptionSeq,
	publishes_events EventPortDescriptionSeq,
	consumes_events EventPortDescriptionSeq,
	attributes ExtAttrDescriptionSeq,
	type TypeCode) (CORBA_ComponentIR_ComponentDescription, error) {
	return CORBA_ComponentIR_ComponentDescription {
		Name: name,
		Id: id,
		Defined_in: defined_in,
		Version: version,
		Base_component: base_component,
		Supported_interfaces: supported_interfaces,
		Provided_interfaces: provided_interfaces,
		Used_interfaces: used_interfaces,
		Emits_events: emits_events,
		Publishes_events: publishes_events,
		Consumes_events: consumes_events,
		Attributes: attributes,
		Type: type,
	}, nil
}
//line CORBA_InterfaceRepository.idl:769
//Interface Decl: CORBA_ComponentIR_FactoryDef
type CORBA_ComponentIR_FactoryDef interface {
}
//line CORBA_InterfaceRepository.idl:770
//Interface Decl: CORBA_ComponentIR_FinderDef
type CORBA_ComponentIR_FinderDef interface {
}
//line CORBA_InterfaceRepository.idl:771
//Interface Decl: HomeDef
type HomeDef interface {
	//line CORBA_InterfaceRepository.idl:773
	//line CORBA_InterfaceRepository.idl:774
	//line CORBA_InterfaceRepository.idl:775
	//line CORBA_InterfaceRepository.idl:776
	//line CORBA_InterfaceRepository.idl:778
	Create_factory(id RepositoryId,exceptions ExceptionDefSeq) (FactoryDef, error)
	//line CORBA_InterfaceRepository.idl:785
	Create_finder(id RepositoryId,exceptions ExceptionDefSeq) (FinderDef, error)
}
//line CORBA_InterfaceRepository.idl:793
//Struct Decl: CORBA_ComponentIR_HomeDescription
type CORBA_ComponentIR_HomeDescription struct {
	Name Identifier
	Id RepositoryId
	Defined_in RepositoryId
	Version VersionSpec
	Base_home RepositoryId
	Managed_component RepositoryId
	Primary_key ValueDescription
	Factories OpDescriptionSeq
	Finders OpDescriptionSeq
	Operations OpDescriptionSeq
	Attributes ExtAttrDescriptionSeq
	Type TypeCode
}

//Constructors
func NewCORBA_ComponentIR_HomeDescriptionDefaultPointer() (*CORBA_ComponentIR_HomeDescription, error) {
	return &CORBA_ComponentIR_HomeDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Base_home: need default value for ''
,
		Managed_component: need default value for ''
,
		Primary_key: need default value for ''
,
		Factories: need default value for ''
,
		Finders: need default value for ''
,
		Operations: need default value for ''
,
		Attributes: need default value for ''
,
		Type: need default value for ''
,
	}, nil
}

func NewCORBA_ComponentIR_HomeDescriptionDefaultValue() (CORBA_ComponentIR_HomeDescription, error) {
	return CORBA_ComponentIR_HomeDescription {
		Name: need default value for ''
,
		Id: need default value for ''
,
		Defined_in: need default value for ''
,
		Version: need default value for ''
,
		Base_home: need default value for ''
,
		Managed_component: need default value for ''
,
		Primary_key: need default value for ''
,
		Factories: need default value for ''
,
		Finders: need default value for ''
,
		Operations: need default value for ''
,
		Attributes: need default value for ''
,
		Type: need default value for ''
,
	}, nil
}

func NewCORBA_ComponentIR_HomeDescriptionValue(
	name Identifier,
	id RepositoryId,
	defined_in RepositoryId,
	version VersionSpec,
	base_home RepositoryId,
	managed_component RepositoryId,
	primary_key ValueDescription,
	factories OpDescriptionSeq,
	finders OpDescriptionSeq,
	operations OpDescriptionSeq,
	attributes ExtAttrDescriptionSeq,
	type TypeCode) (CORBA_ComponentIR_HomeDescription, error) {
	return CORBA_ComponentIR_HomeDescription {
		Name: name,
		Id: id,
		Defined_in: defined_in,
		Version: version,
		Base_home: base_home,
		Managed_component: managed_component,
		Primary_key: primary_key,
		Factories: factories,
		Finders: finders,
		Operations: operations,
		Attributes: attributes,
		Type: type,
	}, nil
}
