// Code generated by abc. DO NOT EDIT.

package corbaFiles

//line CORBA_DomainManager.idl:4
//Interface Decl: CORBA_DomainManager
//Usage Count: 0
type CORBA_DomainManager interface {

	//line CORBA_DomainManager.idl:5
	Get_domain_policy(policy_type CORBA_PolicyType) (CORBA_Policy, error)
}

//line CORBA_DomainManager.idl:12
//Interface Decl: CORBA_ConstructionPolicy
//Usage Count: 0
type CORBA_ConstructionPolicy interface {

	//line CORBA_DomainManager.idl:13
	Make_domain_manager(object_type CORBA_InterfaceDef, constr_policy bool) error
}

//line CORBA_DomainManager.idl:19
//Sequence Decl: Sequence_DomainManager
type Sequence_DomainManager interface{}

//line CORBA_DomainManager.idl:19
//Typedef Decl: CORBA_DomainManagersList
type CORBA_DomainManagersList Sequence_DomainManager
