// Code generated by abc. DO NOT EDIT.

package corbaFiles

//line CORBA_StandardExceptions.idl:8
//Usage Count: 36
type CORBA_Completion_status int

const (
	CORBA_Completion_status_COMPLETED_YES = iota
	CORBA_Completion_status_COMPLETED_NO
	CORBA_Completion_status_COMPLETED_MAYBE
)

//line CORBA_StandardExceptions.idl:11
//Usage Count: 0
type CORBA_Exception_type int

const (
	CORBA_Exception_type_NO_EXCEPTION = iota
	CORBA_Exception_type_USER_EXCEPTION
	CORBA_Exception_type_SYSTEM_EXCEPTION
)

//line CORBA_StandardExceptions.idl:15
//Exception Decl: CORBA_UNKNOWNException
//Usage Count: 0
type CORBA_UNKNOWNException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_UNKNOWNExceptionDefaultPointer() (*CORBA_UNKNOWNException, error) {
	return &CORBA_UNKNOWNException{}, nil
}

func NewCORBA_UNKNOWNExceptionDefaultValue() (CORBA_UNKNOWNException, error) {
	return CORBA_UNKNOWNException{}, nil
}

func NewCORBA_UNKNOWNExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_UNKNOWNException, error) {
	return CORBA_UNKNOWNException{
		Minor:     minor,
		Completed: completed,
	}, nil
}

//line CORBA_StandardExceptions.idl:16
//Exception Decl: CORBA_BAD_PARAMException
//Usage Count: 0
type CORBA_BAD_PARAMException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_BAD_PARAMExceptionDefaultPointer() (*CORBA_BAD_PARAMException, error) {
	return &CORBA_BAD_PARAMException{}, nil
}

func NewCORBA_BAD_PARAMExceptionDefaultValue() (CORBA_BAD_PARAMException, error) {
	return CORBA_BAD_PARAMException{}, nil
}

func NewCORBA_BAD_PARAMExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_BAD_PARAMException, error) {
	return CORBA_BAD_PARAMException{
		Minor:     minor,
		Completed: completed,
	}, nil
}

//line CORBA_StandardExceptions.idl:18
//Exception Decl: CORBA_NO_MEMORYException
//Usage Count: 0
type CORBA_NO_MEMORYException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_NO_MEMORYExceptionDefaultPointer() (*CORBA_NO_MEMORYException, error) {
	return &CORBA_NO_MEMORYException{}, nil
}

func NewCORBA_NO_MEMORYExceptionDefaultValue() (CORBA_NO_MEMORYException, error) {
	return CORBA_NO_MEMORYException{}, nil
}

func NewCORBA_NO_MEMORYExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_NO_MEMORYException, error) {
	return CORBA_NO_MEMORYException{
		Minor:     minor,
		Completed: completed,
	}, nil
}

//line CORBA_StandardExceptions.idl:20
//Exception Decl: CORBA_IMP_LIMITException
//Usage Count: 0
type CORBA_IMP_LIMITException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_IMP_LIMITExceptionDefaultPointer() (*CORBA_IMP_LIMITException, error) {
	return &CORBA_IMP_LIMITException{}, nil
}

func NewCORBA_IMP_LIMITExceptionDefaultValue() (CORBA_IMP_LIMITException, error) {
	return CORBA_IMP_LIMITException{}, nil
}

func NewCORBA_IMP_LIMITExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_IMP_LIMITException, error) {
	return CORBA_IMP_LIMITException{
		Minor:     minor,
		Completed: completed,
	}, nil
}

//line CORBA_StandardExceptions.idl:22
//Exception Decl: CORBA_COMM_FAILUREException
//Usage Count: 0
type CORBA_COMM_FAILUREException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_COMM_FAILUREExceptionDefaultPointer() (*CORBA_COMM_FAILUREException, error) {
	return &CORBA_COMM_FAILUREException{}, nil
}

func NewCORBA_COMM_FAILUREExceptionDefaultValue() (CORBA_COMM_FAILUREException, error) {
	return CORBA_COMM_FAILUREException{}, nil
}

func NewCORBA_COMM_FAILUREExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_COMM_FAILUREException, error) {
	return CORBA_COMM_FAILUREException{
		Minor:     minor,
		Completed: completed,
	}, nil
}

//line CORBA_StandardExceptions.idl:23
//Exception Decl: CORBA_INV_OBJREFException
//Usage Count: 0
type CORBA_INV_OBJREFException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_INV_OBJREFExceptionDefaultPointer() (*CORBA_INV_OBJREFException, error) {
	return &CORBA_INV_OBJREFException{}, nil
}

func NewCORBA_INV_OBJREFExceptionDefaultValue() (CORBA_INV_OBJREFException, error) {
	return CORBA_INV_OBJREFException{}, nil
}

func NewCORBA_INV_OBJREFExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_INV_OBJREFException, error) {
	return CORBA_INV_OBJREFException{
		Minor:     minor,
		Completed: completed,
	}, nil
}

//line CORBA_StandardExceptions.idl:24
//Exception Decl: CORBA_NO_PERMISSIONException
//Usage Count: 0
type CORBA_NO_PERMISSIONException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_NO_PERMISSIONExceptionDefaultPointer() (*CORBA_NO_PERMISSIONException, error) {
	return &CORBA_NO_PERMISSIONException{}, nil
}

func NewCORBA_NO_PERMISSIONExceptionDefaultValue() (CORBA_NO_PERMISSIONException, error) {
	return CORBA_NO_PERMISSIONException{}, nil
}

func NewCORBA_NO_PERMISSIONExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_NO_PERMISSIONException, error) {
	return CORBA_NO_PERMISSIONException{
		Minor:     minor,
		Completed: completed,
	}, nil
}

//line CORBA_StandardExceptions.idl:26
//Exception Decl: CORBA_INTERNALException
//Usage Count: 0
type CORBA_INTERNALException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_INTERNALExceptionDefaultPointer() (*CORBA_INTERNALException, error) {
	return &CORBA_INTERNALException{}, nil
}

func NewCORBA_INTERNALExceptionDefaultValue() (CORBA_INTERNALException, error) {
	return CORBA_INTERNALException{}, nil
}

func NewCORBA_INTERNALExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_INTERNALException, error) {
	return CORBA_INTERNALException{
		Minor:     minor,
		Completed: completed,
	}, nil
}

//line CORBA_StandardExceptions.idl:27
//Exception Decl: CORBA_MARSHALException
//Usage Count: 0
type CORBA_MARSHALException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_MARSHALExceptionDefaultPointer() (*CORBA_MARSHALException, error) {
	return &CORBA_MARSHALException{}, nil
}

func NewCORBA_MARSHALExceptionDefaultValue() (CORBA_MARSHALException, error) {
	return CORBA_MARSHALException{}, nil
}

func NewCORBA_MARSHALExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_MARSHALException, error) {
	return CORBA_MARSHALException{
		Minor:     minor,
		Completed: completed,
	}, nil
}

//line CORBA_StandardExceptions.idl:29
//Exception Decl: CORBA_INITIALIZEException
//Usage Count: 0
type CORBA_INITIALIZEException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_INITIALIZEExceptionDefaultPointer() (*CORBA_INITIALIZEException, error) {
	return &CORBA_INITIALIZEException{}, nil
}

func NewCORBA_INITIALIZEExceptionDefaultValue() (CORBA_INITIALIZEException, error) {
	return CORBA_INITIALIZEException{}, nil
}

func NewCORBA_INITIALIZEExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_INITIALIZEException, error) {
	return CORBA_INITIALIZEException{
		Minor:     minor,
		Completed: completed,
	}, nil
}

//line CORBA_StandardExceptions.idl:30
//Exception Decl: CORBA_NO_IMPLEMENTException
//Usage Count: 0
type CORBA_NO_IMPLEMENTException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_NO_IMPLEMENTExceptionDefaultPointer() (*CORBA_NO_IMPLEMENTException, error) {
	return &CORBA_NO_IMPLEMENTException{}, nil
}

func NewCORBA_NO_IMPLEMENTExceptionDefaultValue() (CORBA_NO_IMPLEMENTException, error) {
	return CORBA_NO_IMPLEMENTException{}, nil
}

func NewCORBA_NO_IMPLEMENTExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_NO_IMPLEMENTException, error) {
	return CORBA_NO_IMPLEMENTException{
		Minor:     minor,
		Completed: completed,
	}, nil
}

//line CORBA_StandardExceptions.idl:32
//Exception Decl: CORBA_BAD_TYPECODEException
//Usage Count: 0
type CORBA_BAD_TYPECODEException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_BAD_TYPECODEExceptionDefaultPointer() (*CORBA_BAD_TYPECODEException, error) {
	return &CORBA_BAD_TYPECODEException{}, nil
}

func NewCORBA_BAD_TYPECODEExceptionDefaultValue() (CORBA_BAD_TYPECODEException, error) {
	return CORBA_BAD_TYPECODEException{}, nil
}

func NewCORBA_BAD_TYPECODEExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_BAD_TYPECODEException, error) {
	return CORBA_BAD_TYPECODEException{
		Minor:     minor,
		Completed: completed,
	}, nil
}

//line CORBA_StandardExceptions.idl:33
//Exception Decl: CORBA_BAD_OPERATIONException
//Usage Count: 0
type CORBA_BAD_OPERATIONException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_BAD_OPERATIONExceptionDefaultPointer() (*CORBA_BAD_OPERATIONException, error) {
	return &CORBA_BAD_OPERATIONException{}, nil
}

func NewCORBA_BAD_OPERATIONExceptionDefaultValue() (CORBA_BAD_OPERATIONException, error) {
	return CORBA_BAD_OPERATIONException{}, nil
}

func NewCORBA_BAD_OPERATIONExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_BAD_OPERATIONException, error) {
	return CORBA_BAD_OPERATIONException{
		Minor:     minor,
		Completed: completed,
	}, nil
}

//line CORBA_StandardExceptions.idl:34
//Exception Decl: CORBA_NO_RESOURCESException
//Usage Count: 0
type CORBA_NO_RESOURCESException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_NO_RESOURCESExceptionDefaultPointer() (*CORBA_NO_RESOURCESException, error) {
	return &CORBA_NO_RESOURCESException{}, nil
}

func NewCORBA_NO_RESOURCESExceptionDefaultValue() (CORBA_NO_RESOURCESException, error) {
	return CORBA_NO_RESOURCESException{}, nil
}

func NewCORBA_NO_RESOURCESExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_NO_RESOURCESException, error) {
	return CORBA_NO_RESOURCESException{
		Minor:     minor,
		Completed: completed,
	}, nil
}

//line CORBA_StandardExceptions.idl:36
//Exception Decl: CORBA_NO_RESPONSEException
//Usage Count: 0
type CORBA_NO_RESPONSEException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_NO_RESPONSEExceptionDefaultPointer() (*CORBA_NO_RESPONSEException, error) {
	return &CORBA_NO_RESPONSEException{}, nil
}

func NewCORBA_NO_RESPONSEExceptionDefaultValue() (CORBA_NO_RESPONSEException, error) {
	return CORBA_NO_RESPONSEException{}, nil
}

func NewCORBA_NO_RESPONSEExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_NO_RESPONSEException, error) {
	return CORBA_NO_RESPONSEException{
		Minor:     minor,
		Completed: completed,
	}, nil
}

//line CORBA_StandardExceptions.idl:38
//Exception Decl: CORBA_PERSIST_STOREException
//Usage Count: 0
type CORBA_PERSIST_STOREException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_PERSIST_STOREExceptionDefaultPointer() (*CORBA_PERSIST_STOREException, error) {
	return &CORBA_PERSIST_STOREException{}, nil
}

func NewCORBA_PERSIST_STOREExceptionDefaultValue() (CORBA_PERSIST_STOREException, error) {
	return CORBA_PERSIST_STOREException{}, nil
}

func NewCORBA_PERSIST_STOREExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_PERSIST_STOREException, error) {
	return CORBA_PERSIST_STOREException{
		Minor:     minor,
		Completed: completed,
	}, nil
}

//line CORBA_StandardExceptions.idl:39
//Exception Decl: CORBA_BAD_INV_ORDERException
//Usage Count: 0
type CORBA_BAD_INV_ORDERException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_BAD_INV_ORDERExceptionDefaultPointer() (*CORBA_BAD_INV_ORDERException, error) {
	return &CORBA_BAD_INV_ORDERException{}, nil
}

func NewCORBA_BAD_INV_ORDERExceptionDefaultValue() (CORBA_BAD_INV_ORDERException, error) {
	return CORBA_BAD_INV_ORDERException{}, nil
}

func NewCORBA_BAD_INV_ORDERExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_BAD_INV_ORDERException, error) {
	return CORBA_BAD_INV_ORDERException{
		Minor:     minor,
		Completed: completed,
	}, nil
}

//line CORBA_StandardExceptions.idl:41
//Exception Decl: CORBA_TRANSIENTException
//Usage Count: 0
type CORBA_TRANSIENTException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_TRANSIENTExceptionDefaultPointer() (*CORBA_TRANSIENTException, error) {
	return &CORBA_TRANSIENTException{}, nil
}

func NewCORBA_TRANSIENTExceptionDefaultValue() (CORBA_TRANSIENTException, error) {
	return CORBA_TRANSIENTException{}, nil
}

func NewCORBA_TRANSIENTExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_TRANSIENTException, error) {
	return CORBA_TRANSIENTException{
		Minor:     minor,
		Completed: completed,
	}, nil
}

//line CORBA_StandardExceptions.idl:43
//Exception Decl: CORBA_FREE_MEMException
//Usage Count: 0
type CORBA_FREE_MEMException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_FREE_MEMExceptionDefaultPointer() (*CORBA_FREE_MEMException, error) {
	return &CORBA_FREE_MEMException{}, nil
}

func NewCORBA_FREE_MEMExceptionDefaultValue() (CORBA_FREE_MEMException, error) {
	return CORBA_FREE_MEMException{}, nil
}

func NewCORBA_FREE_MEMExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_FREE_MEMException, error) {
	return CORBA_FREE_MEMException{
		Minor:     minor,
		Completed: completed,
	}, nil
}

//line CORBA_StandardExceptions.idl:44
//Exception Decl: CORBA_INV_IDENTException
//Usage Count: 0
type CORBA_INV_IDENTException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_INV_IDENTExceptionDefaultPointer() (*CORBA_INV_IDENTException, error) {
	return &CORBA_INV_IDENTException{}, nil
}

func NewCORBA_INV_IDENTExceptionDefaultValue() (CORBA_INV_IDENTException, error) {
	return CORBA_INV_IDENTException{}, nil
}

func NewCORBA_INV_IDENTExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_INV_IDENTException, error) {
	return CORBA_INV_IDENTException{
		Minor:     minor,
		Completed: completed,
	}, nil
}

//line CORBA_StandardExceptions.idl:45
//Exception Decl: CORBA_INV_FLAGException
//Usage Count: 0
type CORBA_INV_FLAGException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_INV_FLAGExceptionDefaultPointer() (*CORBA_INV_FLAGException, error) {
	return &CORBA_INV_FLAGException{}, nil
}

func NewCORBA_INV_FLAGExceptionDefaultValue() (CORBA_INV_FLAGException, error) {
	return CORBA_INV_FLAGException{}, nil
}

func NewCORBA_INV_FLAGExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_INV_FLAGException, error) {
	return CORBA_INV_FLAGException{
		Minor:     minor,
		Completed: completed,
	}, nil
}

//line CORBA_StandardExceptions.idl:46
//Exception Decl: CORBA_INTF_REPOSException
//Usage Count: 0
type CORBA_INTF_REPOSException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_INTF_REPOSExceptionDefaultPointer() (*CORBA_INTF_REPOSException, error) {
	return &CORBA_INTF_REPOSException{}, nil
}

func NewCORBA_INTF_REPOSExceptionDefaultValue() (CORBA_INTF_REPOSException, error) {
	return CORBA_INTF_REPOSException{}, nil
}

func NewCORBA_INTF_REPOSExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_INTF_REPOSException, error) {
	return CORBA_INTF_REPOSException{
		Minor:     minor,
		Completed: completed,
	}, nil
}

//line CORBA_StandardExceptions.idl:48
//Exception Decl: CORBA_BAD_CONTEXTException
//Usage Count: 0
type CORBA_BAD_CONTEXTException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_BAD_CONTEXTExceptionDefaultPointer() (*CORBA_BAD_CONTEXTException, error) {
	return &CORBA_BAD_CONTEXTException{}, nil
}

func NewCORBA_BAD_CONTEXTExceptionDefaultValue() (CORBA_BAD_CONTEXTException, error) {
	return CORBA_BAD_CONTEXTException{}, nil
}

func NewCORBA_BAD_CONTEXTExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_BAD_CONTEXTException, error) {
	return CORBA_BAD_CONTEXTException{
		Minor:     minor,
		Completed: completed,
	}, nil
}

//line CORBA_StandardExceptions.idl:50
//Exception Decl: CORBA_OBJ_ADAPTERException
//Usage Count: 0
type CORBA_OBJ_ADAPTERException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_OBJ_ADAPTERExceptionDefaultPointer() (*CORBA_OBJ_ADAPTERException, error) {
	return &CORBA_OBJ_ADAPTERException{}, nil
}

func NewCORBA_OBJ_ADAPTERExceptionDefaultValue() (CORBA_OBJ_ADAPTERException, error) {
	return CORBA_OBJ_ADAPTERException{}, nil
}

func NewCORBA_OBJ_ADAPTERExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_OBJ_ADAPTERException, error) {
	return CORBA_OBJ_ADAPTERException{
		Minor:     minor,
		Completed: completed,
	}, nil
}

//line CORBA_StandardExceptions.idl:52
//Exception Decl: CORBA_DATA_CONVERSIONException
//Usage Count: 0
type CORBA_DATA_CONVERSIONException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_DATA_CONVERSIONExceptionDefaultPointer() (*CORBA_DATA_CONVERSIONException, error) {
	return &CORBA_DATA_CONVERSIONException{}, nil
}

func NewCORBA_DATA_CONVERSIONExceptionDefaultValue() (CORBA_DATA_CONVERSIONException, error) {
	return CORBA_DATA_CONVERSIONException{}, nil
}

func NewCORBA_DATA_CONVERSIONExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_DATA_CONVERSIONException, error) {
	return CORBA_DATA_CONVERSIONException{
		Minor:     minor,
		Completed: completed,
	}, nil
}

//line CORBA_StandardExceptions.idl:53
//Exception Decl: CORBA_OBJECT_NOT_EXISTException
//Usage Count: 0
type CORBA_OBJECT_NOT_EXISTException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_OBJECT_NOT_EXISTExceptionDefaultPointer() (*CORBA_OBJECT_NOT_EXISTException, error) {
	return &CORBA_OBJECT_NOT_EXISTException{}, nil
}

func NewCORBA_OBJECT_NOT_EXISTExceptionDefaultValue() (CORBA_OBJECT_NOT_EXISTException, error) {
	return CORBA_OBJECT_NOT_EXISTException{}, nil
}

func NewCORBA_OBJECT_NOT_EXISTExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_OBJECT_NOT_EXISTException, error) {
	return CORBA_OBJECT_NOT_EXISTException{
		Minor:     minor,
		Completed: completed,
	}, nil
}

//line CORBA_StandardExceptions.idl:55
//Exception Decl: CORBA_TRANSACTION_REQUIREDException
//Usage Count: 0
type CORBA_TRANSACTION_REQUIREDException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_TRANSACTION_REQUIREDExceptionDefaultPointer() (*CORBA_TRANSACTION_REQUIREDException, error) {
	return &CORBA_TRANSACTION_REQUIREDException{}, nil
}

func NewCORBA_TRANSACTION_REQUIREDExceptionDefaultValue() (CORBA_TRANSACTION_REQUIREDException, error) {
	return CORBA_TRANSACTION_REQUIREDException{}, nil
}

func NewCORBA_TRANSACTION_REQUIREDExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_TRANSACTION_REQUIREDException, error) {
	return CORBA_TRANSACTION_REQUIREDException{
		Minor:     minor,
		Completed: completed,
	}, nil
}

//line CORBA_StandardExceptions.idl:57
//Exception Decl: CORBA_TRANSACTION_ROLLEDBACKException
//Usage Count: 0
type CORBA_TRANSACTION_ROLLEDBACKException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_TRANSACTION_ROLLEDBACKExceptionDefaultPointer() (*CORBA_TRANSACTION_ROLLEDBACKException, error) {
	return &CORBA_TRANSACTION_ROLLEDBACKException{}, nil
}

func NewCORBA_TRANSACTION_ROLLEDBACKExceptionDefaultValue() (CORBA_TRANSACTION_ROLLEDBACKException, error) {
	return CORBA_TRANSACTION_ROLLEDBACKException{}, nil
}

func NewCORBA_TRANSACTION_ROLLEDBACKExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_TRANSACTION_ROLLEDBACKException, error) {
	return CORBA_TRANSACTION_ROLLEDBACKException{
		Minor:     minor,
		Completed: completed,
	}, nil
}

//line CORBA_StandardExceptions.idl:59
//Exception Decl: CORBA_INVALID_TRANSACTIONException
//Usage Count: 0
type CORBA_INVALID_TRANSACTIONException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_INVALID_TRANSACTIONExceptionDefaultPointer() (*CORBA_INVALID_TRANSACTIONException, error) {
	return &CORBA_INVALID_TRANSACTIONException{}, nil
}

func NewCORBA_INVALID_TRANSACTIONExceptionDefaultValue() (CORBA_INVALID_TRANSACTIONException, error) {
	return CORBA_INVALID_TRANSACTIONException{}, nil
}

func NewCORBA_INVALID_TRANSACTIONExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_INVALID_TRANSACTIONException, error) {
	return CORBA_INVALID_TRANSACTIONException{
		Minor:     minor,
		Completed: completed,
	}, nil
}

//line CORBA_StandardExceptions.idl:61
//Exception Decl: CORBA_INV_POLICYException
//Usage Count: 0
type CORBA_INV_POLICYException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_INV_POLICYExceptionDefaultPointer() (*CORBA_INV_POLICYException, error) {
	return &CORBA_INV_POLICYException{}, nil
}

func NewCORBA_INV_POLICYExceptionDefaultValue() (CORBA_INV_POLICYException, error) {
	return CORBA_INV_POLICYException{}, nil
}

func NewCORBA_INV_POLICYExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_INV_POLICYException, error) {
	return CORBA_INV_POLICYException{
		Minor:     minor,
		Completed: completed,
	}, nil
}

//line CORBA_StandardExceptions.idl:62
//Exception Decl: CORBA_CODESET_INCOMPATIBLEException
//Usage Count: 0
type CORBA_CODESET_INCOMPATIBLEException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_CODESET_INCOMPATIBLEExceptionDefaultPointer() (*CORBA_CODESET_INCOMPATIBLEException, error) {
	return &CORBA_CODESET_INCOMPATIBLEException{}, nil
}

func NewCORBA_CODESET_INCOMPATIBLEExceptionDefaultValue() (CORBA_CODESET_INCOMPATIBLEException, error) {
	return CORBA_CODESET_INCOMPATIBLEException{}, nil
}

func NewCORBA_CODESET_INCOMPATIBLEExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_CODESET_INCOMPATIBLEException, error) {
	return CORBA_CODESET_INCOMPATIBLEException{
		Minor:     minor,
		Completed: completed,
	}, nil
}

//line CORBA_StandardExceptions.idl:64
//Exception Decl: CORBA_REBINDException
//Usage Count: 0
type CORBA_REBINDException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_REBINDExceptionDefaultPointer() (*CORBA_REBINDException, error) {
	return &CORBA_REBINDException{}, nil
}

func NewCORBA_REBINDExceptionDefaultValue() (CORBA_REBINDException, error) {
	return CORBA_REBINDException{}, nil
}

func NewCORBA_REBINDExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_REBINDException, error) {
	return CORBA_REBINDException{
		Minor:     minor,
		Completed: completed,
	}, nil
}

//line CORBA_StandardExceptions.idl:65
//Exception Decl: CORBA_TIMEOUTException
//Usage Count: 0
type CORBA_TIMEOUTException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_TIMEOUTExceptionDefaultPointer() (*CORBA_TIMEOUTException, error) {
	return &CORBA_TIMEOUTException{}, nil
}

func NewCORBA_TIMEOUTExceptionDefaultValue() (CORBA_TIMEOUTException, error) {
	return CORBA_TIMEOUTException{}, nil
}

func NewCORBA_TIMEOUTExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_TIMEOUTException, error) {
	return CORBA_TIMEOUTException{
		Minor:     minor,
		Completed: completed,
	}, nil
}

//line CORBA_StandardExceptions.idl:66
//Exception Decl: CORBA_TRANSACTION_UNAVAILABLEException
//Usage Count: 0
type CORBA_TRANSACTION_UNAVAILABLEException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_TRANSACTION_UNAVAILABLEExceptionDefaultPointer() (*CORBA_TRANSACTION_UNAVAILABLEException, error) {
	return &CORBA_TRANSACTION_UNAVAILABLEException{}, nil
}

func NewCORBA_TRANSACTION_UNAVAILABLEExceptionDefaultValue() (CORBA_TRANSACTION_UNAVAILABLEException, error) {
	return CORBA_TRANSACTION_UNAVAILABLEException{}, nil
}

func NewCORBA_TRANSACTION_UNAVAILABLEExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_TRANSACTION_UNAVAILABLEException, error) {
	return CORBA_TRANSACTION_UNAVAILABLEException{
		Minor:     minor,
		Completed: completed,
	}, nil
}

//line CORBA_StandardExceptions.idl:68
//Exception Decl: CORBA_TRANSACTION_MODEException
//Usage Count: 0
type CORBA_TRANSACTION_MODEException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_TRANSACTION_MODEExceptionDefaultPointer() (*CORBA_TRANSACTION_MODEException, error) {
	return &CORBA_TRANSACTION_MODEException{}, nil
}

func NewCORBA_TRANSACTION_MODEExceptionDefaultValue() (CORBA_TRANSACTION_MODEException, error) {
	return CORBA_TRANSACTION_MODEException{}, nil
}

func NewCORBA_TRANSACTION_MODEExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_TRANSACTION_MODEException, error) {
	return CORBA_TRANSACTION_MODEException{
		Minor:     minor,
		Completed: completed,
	}, nil
}

//line CORBA_StandardExceptions.idl:69
//Exception Decl: CORBA_BAD_QOSException
//Usage Count: 0
type CORBA_BAD_QOSException struct {
	Minor     uint32
	Completed CORBA_Completion_status
}

//Constructors
func NewCORBA_BAD_QOSExceptionDefaultPointer() (*CORBA_BAD_QOSException, error) {
	return &CORBA_BAD_QOSException{}, nil
}

func NewCORBA_BAD_QOSExceptionDefaultValue() (CORBA_BAD_QOSException, error) {
	return CORBA_BAD_QOSException{}, nil
}

func NewCORBA_BAD_QOSExceptionValue(
	minor uint32,
	completed CORBA_Completion_status) (CORBA_BAD_QOSException, error) {
	return CORBA_BAD_QOSException{
		Minor:     minor,
		Completed: completed,
	}, nil
}
