package corbaFiles

//Code generated by  DO NOT EDIT.
//line CORBA_TypeCode.idl:10
//line CORBA_TypeCode.idl:33
//Exception Decl: CORBA_TypeCode_Bounds
type CORBA_TypeCode_Bounds struct {
}

//Constructors
func NewCORBA_TypeCode_BoundsDefaultPointer() (*CORBA_TypeCode_Bounds, error) {
}

func NewCORBA_TypeCode_BoundsDefaultValue() (CORBA_TypeCode_Bounds, error) {
}

//line CORBA_TypeCode.idl:34
//Exception Decl: CORBA_TypeCode_BadKind
type CORBA_TypeCode_BadKind struct {
}

//Constructors
func NewCORBA_TypeCode_BadKindDefaultPointer() (*CORBA_TypeCode_BadKind, error) {
}

func NewCORBA_TypeCode_BadKindDefaultValue() (CORBA_TypeCode_BadKind, error) {
}

//line CORBA_TypeCode.idl:32
//Interface Decl: TypeCode
type TypeCode interface {
	//line CORBA_TypeCode.idl:36
	Equal(tc TypeCode) (bool, error)
	//line CORBA_TypeCode.idl:37
	Equivalent(tc TypeCode) (bool, error)
	//line CORBA_TypeCode.idl:38
	Get_compact_typecode() (TypeCode, error)
	//line CORBA_TypeCode.idl:39
	Kind() (TCKind, error)
	//line CORBA_TypeCode.idl:43
	Id() (RepositoryId, error)
	//line CORBA_TypeCode.idl:47
	Name() (Identifier, error)
	//line CORBA_TypeCode.idl:50
	Member_count() (uint32, error)
	//line CORBA_TypeCode.idl:51
	Member_name(index uint32) (Identifier, error)
	//line CORBA_TypeCode.idl:54
	Member_type(index uint32) (TypeCode, error)
	//line CORBA_TypeCode.idl:57
	Member_label(index uint32) (CorbaAny, error)
	//line CORBA_TypeCode.idl:59
	Discriminator_type() (TypeCode, error)
	//line CORBA_TypeCode.idl:60
	Default_index() (int32, error)
	//line CORBA_TypeCode.idl:62
	Length() (uint32, error)
	//line CORBA_TypeCode.idl:64
	Content_type() (TypeCode, error)
	//line CORBA_TypeCode.idl:66
	Fixed_digits() (uint16, error)
	//line CORBA_TypeCode.idl:67
	Fixed_scale() (int16, error)
	//line CORBA_TypeCode.idl:69
	Member_visibility(index uint32) (Visibility, error)
	//line CORBA_TypeCode.idl:71
	Type_modifier() (ValueModifier, error)
	//line CORBA_TypeCode.idl:72
	Concrete_base_type() (TypeCode, error)
}
