// Code generated by abc. DO NOT EDIT.

package corbaFiles

//line CORBA_Policy.idl:4
type CORBA_PolicyType uint32

//line CORBA_Policy.idl:7
//Interface Decl: CORBA_Policy
//Usage Count: 2
type CORBA_Policy interface {

	//line CORBA_Policy.idl:8

	//line CORBA_Policy.idl:9
	Copy() (CORBA_Policy, error)

	//line CORBA_Policy.idl:10
	Destroy() error
}

//line CORBA_Policy.idl:13
//Sequence Decl: Sequence_Policy
type Sequence_Policy interface{}

//line CORBA_Policy.idl:13
//Typedef Decl: CORBA_PolicyList
type CORBA_PolicyList Sequence_Policy

//line CORBA_Policy.idl:14
//Sequence Decl: Sequence_PolicyType
type Sequence_PolicyType interface{}

//line CORBA_Policy.idl:14
//Typedef Decl: CORBA_PolicyTypeSeq
type CORBA_PolicyTypeSeq Sequence_PolicyType

//line CORBA_Policy.idl:16
type CORBA_PolicyErrorCode int16

//line CORBA_Policy.idl:17
//Exception Decl: CORBA_PolicyErrorException
//Usage Count: 0
type CORBA_PolicyErrorException struct {
	Reason CORBA_PolicyErrorCode
}

//Constructors
func NewCORBA_PolicyErrorExceptionDefaultPointer() (*CORBA_PolicyErrorException, error) {
	return &CORBA_PolicyErrorException{}, nil
}

func NewCORBA_PolicyErrorExceptionDefaultValue() (CORBA_PolicyErrorException, error) {
	return CORBA_PolicyErrorException{}, nil
}

func NewCORBA_PolicyErrorExceptionValue(
	reason CORBA_PolicyErrorCode) (CORBA_PolicyErrorException, error) {
	return CORBA_PolicyErrorException{
		Reason: reason,
	}, nil
}

//line CORBA_Policy.idl:25
//Usage Count: 1
type CORBA_SetOverrideType int

const (
	CORBA_SetOverrideType_SET_OVERRIDE = iota
	CORBA_SetOverrideType_ADD_OVERRIDE
)

//line CORBA_Policy.idl:28
//Sequence Decl: Sequence_uint16
type Sequence_uint16 interface{}

//line CORBA_Policy.idl:27
//Exception Decl: CORBA_InvalidPoliciesException
//Usage Count: 0
type CORBA_InvalidPoliciesException struct {
	Indicies Sequence_uint16
}

//Constructors
func NewCORBA_InvalidPoliciesExceptionDefaultPointer() (*CORBA_InvalidPoliciesException, error) {
	return &CORBA_InvalidPoliciesException{}, nil
}

func NewCORBA_InvalidPoliciesExceptionDefaultValue() (CORBA_InvalidPoliciesException, error) {
	return CORBA_InvalidPoliciesException{}, nil
}

func NewCORBA_InvalidPoliciesExceptionValue(
	indicies Sequence_uint16) (CORBA_InvalidPoliciesException, error) {
	return CORBA_InvalidPoliciesException{
		Indicies: indicies,
	}, nil
}

//line CORBA_Policy.idl:31
//Interface Decl: CORBA_PolicyManager
//Usage Count: 0
type CORBA_PolicyManager interface {

	//line CORBA_Policy.idl:32
	Get_policy_overrides(ts CORBA_PolicyTypeSeq) (CORBA_PolicyList, error)

	//line CORBA_Policy.idl:34
	Set_policy_overrides(policies CORBA_PolicyList, set_add CORBA_SetOverrideType) error
}

//line CORBA_Policy.idl:39
//Interface Decl: CORBA_PolicyCurrent
//Usage Count: 0
type CORBA_PolicyCurrent interface {
}
