// Code generated by abc. DO NOT EDIT.

package corbaFiles

//line CORBA_InterfaceRepository.idl:5
type CORBA_ScopedName AnsiString

//line CORBA_InterfaceRepository.idl:6
type CORBA_RepositoryId AnsiString

//line CORBA_InterfaceRepository.idl:8
//Usage Count: 5
type CORBA_DefinitionKind int

const (
	CORBA_DefinitionKind_dk_none = iota
	CORBA_DefinitionKind_dk_all
	CORBA_DefinitionKind_dk_Attribute
	CORBA_DefinitionKind_dk_Constant
	CORBA_DefinitionKind_dk_Exception
	CORBA_DefinitionKind_dk_Interface
	CORBA_DefinitionKind_dk_Module
	CORBA_DefinitionKind_dk_Operation
	CORBA_DefinitionKind_dk_Typedef
	CORBA_DefinitionKind_dk_Alias
	CORBA_DefinitionKind_dk_Struct
	CORBA_DefinitionKind_dk_Union
	CORBA_DefinitionKind_dk_Enum
	CORBA_DefinitionKind_dk_Primitive
	CORBA_DefinitionKind_dk_String
	CORBA_DefinitionKind_dk_Sequence
	CORBA_DefinitionKind_dk_Array
	CORBA_DefinitionKind_dk_Repository
	CORBA_DefinitionKind_dk_Wstring
	CORBA_DefinitionKind_dk_Fixed
	CORBA_DefinitionKind_dk_Value
	CORBA_DefinitionKind_dk_ValueBox
	CORBA_DefinitionKind_dk_ValueMember
	CORBA_DefinitionKind_dk_Native
	CORBA_DefinitionKind_dk_AbstractInterface
	CORBA_DefinitionKind_dk_LocalInterface
	CORBA_DefinitionKind_dk_Component
	CORBA_DefinitionKind_dk_Home
	CORBA_DefinitionKind_dk_Factory
	CORBA_DefinitionKind_dk_Finder
	CORBA_DefinitionKind_dk_Emits
	CORBA_DefinitionKind_dk_Publishes
	CORBA_DefinitionKind_dk_Consumes
	CORBA_DefinitionKind_dk_Provides
	CORBA_DefinitionKind_dk_Uses
	CORBA_DefinitionKind_dk_Event
)

//line CORBA_InterfaceRepository.idl:27
//Interface Decl: CORBA_IRObject
//Usage Count: 0
type CORBA_IRObject interface {

	//line CORBA_InterfaceRepository.idl:29
	GetDef_kind() CORBA_DefinitionKind

	//line CORBA_InterfaceRepository.idl:31
	Destroy() error
}

//line CORBA_InterfaceRepository.idl:34
type CORBA_VersionSpec AnsiString

//line CORBA_InterfaceRepository.idl:46
//Struct Decl: CORBA_Contained_Description
//Usage Count: 1
type CORBA_Contained_Description struct {
	Kind  CORBA_DefinitionKind
	Value CorbaAny
}

//Constructors
func NewCORBA_Contained_DescriptionDefaultPointer() (*CORBA_Contained_Description, error) {
	return &CORBA_Contained_Description{}, nil
}

func NewCORBA_Contained_DescriptionDefaultValue() (CORBA_Contained_Description, error) {
	return CORBA_Contained_Description{}, nil
}

func NewCORBA_Contained_DescriptionValue(
	kind CORBA_DefinitionKind,
	value CorbaAny) (CORBA_Contained_Description, error) {
	return CORBA_Contained_Description{
		Kind:  kind,
		Value: value,
	}, nil
}

//line CORBA_InterfaceRepository.idl:36
//Interface Decl: CORBA_Contained
//Usage Count: 3
type CORBA_Contained interface {

	//line CORBA_InterfaceRepository.idl:39
	GetId() CORBA_RepositoryId
	SetId(value CORBA_RepositoryId)

	//line CORBA_InterfaceRepository.idl:40
	GetName() CORBA_Identifier
	SetName(value CORBA_Identifier)

	//line CORBA_InterfaceRepository.idl:41
	GetVersion() CORBA_VersionSpec
	SetVersion(value CORBA_VersionSpec)

	//line CORBA_InterfaceRepository.idl:43
	GetDefined_in() CORBA_Container

	//line CORBA_InterfaceRepository.idl:44
	GetAbsolute_name() CORBA_ScopedName

	//line CORBA_InterfaceRepository.idl:45
	GetContaining_repository() CORBA_Repository

	//line CORBA_InterfaceRepository.idl:50
	Describe() (CORBA_Contained_Description, error)

	//line CORBA_InterfaceRepository.idl:52
	Move(new_container CORBA_Container, new_version CORBA_VersionSpec) error
}

//line CORBA_InterfaceRepository.idl:68
//Sequence Decl: Sequence_InterfaceDef
type Sequence_InterfaceDef interface{}

//line CORBA_InterfaceRepository.idl:68
//Typedef Decl: CORBA_InterfaceDefSeq
type CORBA_InterfaceDefSeq Sequence_InterfaceDef

//line CORBA_InterfaceRepository.idl:70
//Sequence Decl: Sequence_ValueDef
type Sequence_ValueDef interface{}

//line CORBA_InterfaceRepository.idl:70
//Typedef Decl: CORBA_ValueDefSeq
type CORBA_ValueDefSeq Sequence_ValueDef

//line CORBA_InterfaceRepository.idl:73
//Sequence Decl: Sequence_AbstractInterfaceDef
type Sequence_AbstractInterfaceDef interface{}

//line CORBA_InterfaceRepository.idl:73
//Typedef Decl: CORBA_AbstractInterfaceDefSeq
type CORBA_AbstractInterfaceDefSeq Sequence_AbstractInterfaceDef

//line CORBA_InterfaceRepository.idl:75
//Sequence Decl: Sequence_LocalInterfaceDef
type Sequence_LocalInterfaceDef interface{}

//line CORBA_InterfaceRepository.idl:75
//Typedef Decl: CORBA_LocalInterfaceDefSeq
type CORBA_LocalInterfaceDefSeq Sequence_LocalInterfaceDef

//line CORBA_InterfaceRepository.idl:77
//Sequence Decl: Sequence_ExtInterfaceDef
type Sequence_ExtInterfaceDef interface{}

//line CORBA_InterfaceRepository.idl:77
//Typedef Decl: CORBA_ExtInterfaceDefSeq
type CORBA_ExtInterfaceDefSeq Sequence_ExtInterfaceDef

//line CORBA_InterfaceRepository.idl:79
//Sequence Decl: Sequence_ExtValueDef
type Sequence_ExtValueDef interface{}

//line CORBA_InterfaceRepository.idl:79
//Typedef Decl: CORBA_ExtValueDefSeq
type CORBA_ExtValueDefSeq Sequence_ExtValueDef

//line CORBA_InterfaceRepository.idl:81
//Sequence Decl: Sequence_ExtAbstractInterfaceDef
type Sequence_ExtAbstractInterfaceDef interface{}

//line CORBA_InterfaceRepository.idl:81
//Typedef Decl: CORBA_ExtAbstractInterfaceDefSeq
type CORBA_ExtAbstractInterfaceDefSeq Sequence_ExtAbstractInterfaceDef

//line CORBA_InterfaceRepository.idl:83
//Sequence Decl: Sequence_ExtLocalInterfaceDef
type Sequence_ExtLocalInterfaceDef interface{}

//line CORBA_InterfaceRepository.idl:83
//Typedef Decl: CORBA_ExtLocalInterfaceDefSeq
type CORBA_ExtLocalInterfaceDefSeq Sequence_ExtLocalInterfaceDef

//line CORBA_InterfaceRepository.idl:84
//Sequence Decl: Sequence_Contained
type Sequence_Contained interface{}

//line CORBA_InterfaceRepository.idl:84
//Typedef Decl: CORBA_ContainedSeq
type CORBA_ContainedSeq Sequence_Contained

//line CORBA_InterfaceRepository.idl:86
//Struct Decl: CORBA_StructMember
//Usage Count: 0
type CORBA_StructMember struct {
	Name     CORBA_Identifier
	Type     CORBA_TypeCode
	Type_def CORBA_IDLType
}

//Constructors
func NewCORBA_StructMemberDefaultPointer() (*CORBA_StructMember, error) {
	return &CORBA_StructMember{}, nil
}

func NewCORBA_StructMemberDefaultValue() (CORBA_StructMember, error) {
	return CORBA_StructMember{}, nil
}

func NewCORBA_StructMemberValue(
	name CORBA_Identifier,
	type_ CORBA_TypeCode,
	type_def CORBA_IDLType) (CORBA_StructMember, error) {
	return CORBA_StructMember{
		Name:     name,
		Type:     type_,
		Type_def: type_def,
	}, nil
}

//line CORBA_InterfaceRepository.idl:91
//Sequence Decl: Sequence_StructMember
type Sequence_StructMember interface{}

//line CORBA_InterfaceRepository.idl:91
//Typedef Decl: CORBA_StructMemberSeq
type CORBA_StructMemberSeq Sequence_StructMember

//line CORBA_InterfaceRepository.idl:92
//Struct Decl: CORBA_Initializer
//Usage Count: 0
type CORBA_Initializer struct {
	Members CORBA_StructMemberSeq
	Name    CORBA_Identifier
}

//Constructors
func NewCORBA_InitializerDefaultPointer() (*CORBA_Initializer, error) {
	return &CORBA_Initializer{}, nil
}

func NewCORBA_InitializerDefaultValue() (CORBA_Initializer, error) {
	return CORBA_Initializer{}, nil
}

func NewCORBA_InitializerValue(
	members CORBA_StructMemberSeq,
	name CORBA_Identifier) (CORBA_Initializer, error) {
	return CORBA_Initializer{
		Members: members,
		Name:    name,
	}, nil
}

//line CORBA_InterfaceRepository.idl:96
//Sequence Decl: Sequence_Initializer
type Sequence_Initializer interface{}

//line CORBA_InterfaceRepository.idl:96
//Typedef Decl: CORBA_InitializerSeq
type CORBA_InitializerSeq Sequence_Initializer

//line CORBA_InterfaceRepository.idl:97
//Struct Decl: CORBA_UnionMember
//Usage Count: 0
type CORBA_UnionMember struct {
	Name     CORBA_Identifier
	Label    CorbaAny
	Type     CORBA_TypeCode
	Type_def CORBA_IDLType
}

//Constructors
func NewCORBA_UnionMemberDefaultPointer() (*CORBA_UnionMember, error) {
	return &CORBA_UnionMember{}, nil
}

func NewCORBA_UnionMemberDefaultValue() (CORBA_UnionMember, error) {
	return CORBA_UnionMember{}, nil
}

func NewCORBA_UnionMemberValue(
	name CORBA_Identifier,
	label CorbaAny,
	type_ CORBA_TypeCode,
	type_def CORBA_IDLType) (CORBA_UnionMember, error) {
	return CORBA_UnionMember{
		Name:     name,
		Label:    label,
		Type:     type_,
		Type_def: type_def,
	}, nil
}

//line CORBA_InterfaceRepository.idl:104
//Struct Decl: CORBA_ExceptionDescription
//Usage Count: 0
type CORBA_ExceptionDescription struct {
	Name       CORBA_Identifier
	Id         CORBA_RepositoryId
	Defined_in CORBA_RepositoryId
	Version    CORBA_VersionSpec
	Type       CORBA_TypeCode
}

//Constructors
func NewCORBA_ExceptionDescriptionDefaultPointer() (*CORBA_ExceptionDescription, error) {
	return &CORBA_ExceptionDescription{}, nil
}

func NewCORBA_ExceptionDescriptionDefaultValue() (CORBA_ExceptionDescription, error) {
	return CORBA_ExceptionDescription{}, nil
}

func NewCORBA_ExceptionDescriptionValue(
	name CORBA_Identifier,
	id CORBA_RepositoryId,
	defined_in CORBA_RepositoryId,
	version CORBA_VersionSpec,
	type_ CORBA_TypeCode) (CORBA_ExceptionDescription, error) {
	return CORBA_ExceptionDescription{
		Name:       name,
		Id:         id,
		Defined_in: defined_in,
		Version:    version,
		Type:       type_,
	}, nil
}

//line CORBA_InterfaceRepository.idl:112
//Sequence Decl: Sequence_ExceptionDescription
type Sequence_ExceptionDescription interface{}

//line CORBA_InterfaceRepository.idl:112
//Typedef Decl: CORBA_ExcDescriptionSeq
type CORBA_ExcDescriptionSeq Sequence_ExceptionDescription

//line CORBA_InterfaceRepository.idl:114
//Struct Decl: CORBA_ExtInitializer
//Usage Count: 0
type CORBA_ExtInitializer struct {
	Members    CORBA_StructMemberSeq
	Exceptions CORBA_ExcDescriptionSeq
	Name       CORBA_Identifier
}

//Constructors
func NewCORBA_ExtInitializerDefaultPointer() (*CORBA_ExtInitializer, error) {
	return &CORBA_ExtInitializer{}, nil
}

func NewCORBA_ExtInitializerDefaultValue() (CORBA_ExtInitializer, error) {
	return CORBA_ExtInitializer{}, nil
}

func NewCORBA_ExtInitializerValue(
	members CORBA_StructMemberSeq,
	exceptions CORBA_ExcDescriptionSeq,
	name CORBA_Identifier) (CORBA_ExtInitializer, error) {
	return CORBA_ExtInitializer{
		Members:    members,
		Exceptions: exceptions,
		Name:       name,
	}, nil
}

//line CORBA_InterfaceRepository.idl:120
//Sequence Decl: Sequence_ExtInitializer
type Sequence_ExtInitializer interface{}

//line CORBA_InterfaceRepository.idl:120
//Typedef Decl: CORBA_ExtInitializerSeq
type CORBA_ExtInitializerSeq Sequence_ExtInitializer

//line CORBA_InterfaceRepository.idl:122
//Sequence Decl: Sequence_UnionMember
type Sequence_UnionMember interface{}

//line CORBA_InterfaceRepository.idl:122
//Typedef Decl: CORBA_UnionMemberSeq
type CORBA_UnionMemberSeq Sequence_UnionMember

//line CORBA_InterfaceRepository.idl:123
//Sequence Decl: Sequence_Identifier
type Sequence_Identifier interface{}

//line CORBA_InterfaceRepository.idl:123
//Typedef Decl: CORBA_EnumMemberSeq
type CORBA_EnumMemberSeq Sequence_Identifier

//line CORBA_InterfaceRepository.idl:138
//Struct Decl: CORBA_Container_Description
//Usage Count: 0
type CORBA_Container_Description struct {
	Contained_object CORBA_Contained
	Kind             CORBA_DefinitionKind
	Value            CorbaAny
}

//Constructors
func NewCORBA_Container_DescriptionDefaultPointer() (*CORBA_Container_Description, error) {
	return &CORBA_Container_Description{}, nil
}

func NewCORBA_Container_DescriptionDefaultValue() (CORBA_Container_Description, error) {
	return CORBA_Container_Description{}, nil
}

func NewCORBA_Container_DescriptionValue(
	contained_object CORBA_Contained,
	kind CORBA_DefinitionKind,
	value CorbaAny) (CORBA_Container_Description, error) {
	return CORBA_Container_Description{
		Contained_object: contained_object,
		Kind:             kind,
		Value:            value,
	}, nil
}

//line CORBA_InterfaceRepository.idl:143
//Sequence Decl: Sequence_Description
type Sequence_Description interface{}

//line CORBA_InterfaceRepository.idl:143
//Typedef Decl: CORBA_Container_DescriptionSeq
type CORBA_Container_DescriptionSeq Sequence_Description

//line CORBA_InterfaceRepository.idl:124
//Interface Decl: CORBA_Container
//Usage Count: 2
type CORBA_Container interface {

	//line CORBA_InterfaceRepository.idl:126
	Lookup(search_name CORBA_ScopedName) (CORBA_Contained, error)

	//line CORBA_InterfaceRepository.idl:128
	Contents(limit_type CORBA_DefinitionKind, exclude_inherited bool) (CORBA_ContainedSeq, error)

	//line CORBA_InterfaceRepository.idl:132
	Lookup_name(search_name CORBA_Identifier, exclude_inherited bool) (CORBA_ContainedSeq, error)

	//line CORBA_InterfaceRepository.idl:144
	Describe_contents(limit_type CORBA_DefinitionKind, max_returned_objs int32) (CORBA_Container_DescriptionSeq, error)

	//line CORBA_InterfaceRepository.idl:150
	Create_module(id CORBA_RepositoryId, version CORBA_VersionSpec) (CORBA_ModuleDef, error)

	//line CORBA_InterfaceRepository.idl:155
	Create_constant(id CORBA_RepositoryId, value CorbaAny) (CORBA_ConstantDef, error)

	//line CORBA_InterfaceRepository.idl:162
	Create_struct(id CORBA_RepositoryId, members CORBA_StructMemberSeq) (CORBA_StructDef, error)

	//line CORBA_InterfaceRepository.idl:168
	Create_union(id CORBA_RepositoryId, members CORBA_UnionMemberSeq) (CORBA_UnionDef, error)

	//line CORBA_InterfaceRepository.idl:175
	Create_enum(id CORBA_RepositoryId, members CORBA_EnumMemberSeq) (CORBA_EnumDef, error)

	//line CORBA_InterfaceRepository.idl:181
	Create_alias(id CORBA_RepositoryId, original_type CORBA_IDLType) (CORBA_AliasDef, error)

	//line CORBA_InterfaceRepository.idl:187
	Create_interface(id CORBA_RepositoryId, is_abstract bool) (CORBA_InterfaceDef, error)

	//line CORBA_InterfaceRepository.idl:194
	Create_value(id CORBA_RepositoryId, initializers CORBA_InitializerSeq) (CORBA_ValueDef, error)

	//line CORBA_InterfaceRepository.idl:206
	Create_value_box(id CORBA_RepositoryId, original_type_def CORBA_IDLType) (CORBA_ValueBoxDef, error)

	//line CORBA_InterfaceRepository.idl:212
	Create_exception(id CORBA_RepositoryId, members CORBA_StructMemberSeq) (CORBA_ExceptionDef, error)

	//line CORBA_InterfaceRepository.idl:218
	Create_native(id CORBA_RepositoryId, version CORBA_VersionSpec) (CORBA_NativeDef, error)

	//line CORBA_InterfaceRepository.idl:223
	Create_abstract_interface(id CORBA_RepositoryId, base_interfaces CORBA_AbstractInterfaceDefSeq) (CORBA_AbstractInterfaceDef, error)

	//line CORBA_InterfaceRepository.idl:229
	Create_local_interface(id CORBA_RepositoryId, base_interfaces CORBA_InterfaceDefSeq) (CORBA_LocalInterfaceDef, error)

	//line CORBA_InterfaceRepository.idl:235
	Create_ext_value(id CORBA_RepositoryId, initializers CORBA_ExtInitializerSeq) (CORBA_ExtValueDef, error)
}

//line CORBA_InterfaceRepository.idl:248
//Interface Decl: CORBA_IDLType
//Usage Count: 17
type CORBA_IDLType interface {

	//line CORBA_InterfaceRepository.idl:249
	GetType() CORBA_TypeCode
}

//line CORBA_InterfaceRepository.idl:252
//Usage Count: 2
type CORBA_PrimitiveKind int

const (
	CORBA_PrimitiveKind_pk_null = iota
	CORBA_PrimitiveKind_pk_void
	CORBA_PrimitiveKind_pk_short
	CORBA_PrimitiveKind_pk_long
	CORBA_PrimitiveKind_pk_ushort
	CORBA_PrimitiveKind_pk_ulong
	CORBA_PrimitiveKind_pk_float
	CORBA_PrimitiveKind_pk_double
	CORBA_PrimitiveKind_pk_boolean
	CORBA_PrimitiveKind_pk_char
	CORBA_PrimitiveKind_pk_octet
	CORBA_PrimitiveKind_pk_any
	CORBA_PrimitiveKind_pk_TypeCode
	CORBA_PrimitiveKind_pk_Principal
	CORBA_PrimitiveKind_pk_string
	CORBA_PrimitiveKind_pk_objref
	CORBA_PrimitiveKind_pk_longlong
	CORBA_PrimitiveKind_pk_ulonglong
	CORBA_PrimitiveKind_pk_longdouble
	CORBA_PrimitiveKind_pk_wchar
	CORBA_PrimitiveKind_pk_wstring
	CORBA_PrimitiveKind_pk_value_base
)

//line CORBA_InterfaceRepository.idl:260
//Interface Decl: CORBA_Repository
//Usage Count: 1
type CORBA_Repository interface {

	//line CORBA_InterfaceRepository.idl:262
	Lookup_id(search_id CORBA_RepositoryId) (CORBA_Contained, error)

	//line CORBA_InterfaceRepository.idl:263
	Get_canonical_typecode(tc CORBA_TypeCode) (CORBA_TypeCode, error)

	//line CORBA_InterfaceRepository.idl:264
	Get_primitive(kind CORBA_PrimitiveKind) (CORBA_PrimitiveDef, error)

	//line CORBA_InterfaceRepository.idl:266
	Create_string(bound uint32) (CORBA_StringDef, error)

	//line CORBA_InterfaceRepository.idl:267
	Create_wstring(bound uint32) (CORBA_WstringDef, error)

	//line CORBA_InterfaceRepository.idl:268
	Create_sequence(bound uint32, element_type CORBA_IDLType) (CORBA_SequenceDef, error)

	//line CORBA_InterfaceRepository.idl:271
	Create_array(length uint32, element_type CORBA_IDLType) (CORBA_ArrayDef, error)

	//line CORBA_InterfaceRepository.idl:274
	Create_fixed(digits uint16, scale int16) (CORBA_FixedDef, error)
}

//line CORBA_InterfaceRepository.idl:278
//Interface Decl: CORBA_ModuleDef
//Usage Count: 1
type CORBA_ModuleDef interface {
}

//line CORBA_InterfaceRepository.idl:281
//Struct Decl: CORBA_ModuleDescription
//Usage Count: 0
type CORBA_ModuleDescription struct {
	Name       CORBA_Identifier
	Id         CORBA_RepositoryId
	Defined_in CORBA_RepositoryId
	Version    CORBA_VersionSpec
}

//Constructors
func NewCORBA_ModuleDescriptionDefaultPointer() (*CORBA_ModuleDescription, error) {
	return &CORBA_ModuleDescription{}, nil
}

func NewCORBA_ModuleDescriptionDefaultValue() (CORBA_ModuleDescription, error) {
	return CORBA_ModuleDescription{}, nil
}

func NewCORBA_ModuleDescriptionValue(
	name CORBA_Identifier,
	id CORBA_RepositoryId,
	defined_in CORBA_RepositoryId,
	version CORBA_VersionSpec) (CORBA_ModuleDescription, error) {
	return CORBA_ModuleDescription{
		Name:       name,
		Id:         id,
		Defined_in: defined_in,
		Version:    version,
	}, nil
}

//line CORBA_InterfaceRepository.idl:288
//Interface Decl: CORBA_ConstantDef
//Usage Count: 1
type CORBA_ConstantDef interface {

	//line CORBA_InterfaceRepository.idl:289
	GetType() CORBA_TypeCode

	//line CORBA_InterfaceRepository.idl:290
	GetType_def() CORBA_IDLType
	SetType_def(value CORBA_IDLType)

	//line CORBA_InterfaceRepository.idl:291
	GetValue() CorbaAny
	SetValue(value CorbaAny)
}

//line CORBA_InterfaceRepository.idl:293
//Struct Decl: CORBA_ConstantDescription
//Usage Count: 0
type CORBA_ConstantDescription struct {
	Name       CORBA_Identifier
	Id         CORBA_RepositoryId
	Defined_in CORBA_RepositoryId
	Version    CORBA_VersionSpec
	Type       CORBA_TypeCode
	Value      CorbaAny
}

//Constructors
func NewCORBA_ConstantDescriptionDefaultPointer() (*CORBA_ConstantDescription, error) {
	return &CORBA_ConstantDescription{}, nil
}

func NewCORBA_ConstantDescriptionDefaultValue() (CORBA_ConstantDescription, error) {
	return CORBA_ConstantDescription{}, nil
}

func NewCORBA_ConstantDescriptionValue(
	name CORBA_Identifier,
	id CORBA_RepositoryId,
	defined_in CORBA_RepositoryId,
	version CORBA_VersionSpec,
	type_ CORBA_TypeCode,
	value CorbaAny) (CORBA_ConstantDescription, error) {
	return CORBA_ConstantDescription{
		Name:       name,
		Id:         id,
		Defined_in: defined_in,
		Version:    version,
		Type:       type_,
		Value:      value,
	}, nil
}

//line CORBA_InterfaceRepository.idl:302
//Interface Decl: CORBA_TypedefDef
//Usage Count: 0
type CORBA_TypedefDef interface {
}

//line CORBA_InterfaceRepository.idl:305
//Struct Decl: CORBA_TypeDescription
//Usage Count: 0
type CORBA_TypeDescription struct {
	Name       CORBA_Identifier
	Id         CORBA_RepositoryId
	Defined_in CORBA_RepositoryId
	Version    CORBA_VersionSpec
	Type       CORBA_TypeCode
}

//Constructors
func NewCORBA_TypeDescriptionDefaultPointer() (*CORBA_TypeDescription, error) {
	return &CORBA_TypeDescription{}, nil
}

func NewCORBA_TypeDescriptionDefaultValue() (CORBA_TypeDescription, error) {
	return CORBA_TypeDescription{}, nil
}

func NewCORBA_TypeDescriptionValue(
	name CORBA_Identifier,
	id CORBA_RepositoryId,
	defined_in CORBA_RepositoryId,
	version CORBA_VersionSpec,
	type_ CORBA_TypeCode) (CORBA_TypeDescription, error) {
	return CORBA_TypeDescription{
		Name:       name,
		Id:         id,
		Defined_in: defined_in,
		Version:    version,
		Type:       type_,
	}, nil
}

//line CORBA_InterfaceRepository.idl:313
//Interface Decl: CORBA_StructDef
//Usage Count: 1
type CORBA_StructDef interface {

	//line CORBA_InterfaceRepository.idl:314
	GetMembers() CORBA_StructMemberSeq
	SetMembers(value CORBA_StructMemberSeq)
}

//line CORBA_InterfaceRepository.idl:317
//Interface Decl: CORBA_UnionDef
//Usage Count: 1
type CORBA_UnionDef interface {

	//line CORBA_InterfaceRepository.idl:318
	GetDiscriminator_type() CORBA_TypeCode

	//line CORBA_InterfaceRepository.idl:319
	GetDiscriminator_type_def() CORBA_IDLType
	SetDiscriminator_type_def(value CORBA_IDLType)

	//line CORBA_InterfaceRepository.idl:320
	GetMembers() CORBA_UnionMemberSeq
	SetMembers(value CORBA_UnionMemberSeq)
}

//line CORBA_InterfaceRepository.idl:323
//Interface Decl: CORBA_EnumDef
//Usage Count: 1
type CORBA_EnumDef interface {

	//line CORBA_InterfaceRepository.idl:324
	GetMembers() CORBA_EnumMemberSeq
	SetMembers(value CORBA_EnumMemberSeq)
}

//line CORBA_InterfaceRepository.idl:326
//Interface Decl: CORBA_AliasDef
//Usage Count: 1
type CORBA_AliasDef interface {

	//line CORBA_InterfaceRepository.idl:327
	GetOriginal_type_def() CORBA_IDLType
	SetOriginal_type_def(value CORBA_IDLType)
}

//line CORBA_InterfaceRepository.idl:329
//Interface Decl: CORBA_NativeDef
//Usage Count: 1
type CORBA_NativeDef interface {
}

//line CORBA_InterfaceRepository.idl:331
//Interface Decl: CORBA_PrimitiveDef
//Usage Count: 1
type CORBA_PrimitiveDef interface {

	//line CORBA_InterfaceRepository.idl:332
	GetKind() CORBA_PrimitiveKind
}

//line CORBA_InterfaceRepository.idl:334
//Interface Decl: CORBA_StringDef
//Usage Count: 1
type CORBA_StringDef interface {

	//line CORBA_InterfaceRepository.idl:335
	GetBound() uint32
	SetBound(value uint32)
}

//line CORBA_InterfaceRepository.idl:337
//Interface Decl: CORBA_WstringDef
//Usage Count: 1
type CORBA_WstringDef interface {

	//line CORBA_InterfaceRepository.idl:338
	GetBound() uint32
	SetBound(value uint32)
}

//line CORBA_InterfaceRepository.idl:340
//Interface Decl: CORBA_FixedDef
//Usage Count: 1
type CORBA_FixedDef interface {

	//line CORBA_InterfaceRepository.idl:341
	GetDigits() uint16
	SetDigits(value uint16)

	//line CORBA_InterfaceRepository.idl:342
	GetScale() int16
	SetScale(value int16)
}

//line CORBA_InterfaceRepository.idl:344
//Interface Decl: CORBA_SequenceDef
//Usage Count: 1
type CORBA_SequenceDef interface {

	//line CORBA_InterfaceRepository.idl:345
	GetBound() uint32
	SetBound(value uint32)

	//line CORBA_InterfaceRepository.idl:346
	GetElement_type() CORBA_TypeCode

	//line CORBA_InterfaceRepository.idl:347
	GetElement_type_def() CORBA_IDLType
	SetElement_type_def(value CORBA_IDLType)
}

//line CORBA_InterfaceRepository.idl:349
//Interface Decl: CORBA_ArrayDef
//Usage Count: 1
type CORBA_ArrayDef interface {

	//line CORBA_InterfaceRepository.idl:350
	GetLength() uint32
	SetLength(value uint32)

	//line CORBA_InterfaceRepository.idl:351
	GetElement_type() CORBA_TypeCode

	//line CORBA_InterfaceRepository.idl:352
	GetElement_type_def() CORBA_IDLType
	SetElement_type_def(value CORBA_IDLType)
}

//line CORBA_InterfaceRepository.idl:354
//Interface Decl: CORBA_ExceptionDef
//Usage Count: 1
type CORBA_ExceptionDef interface {

	//line CORBA_InterfaceRepository.idl:355
	GetType() CORBA_TypeCode

	//line CORBA_InterfaceRepository.idl:356
	GetMembers() CORBA_StructMemberSeq
	SetMembers(value CORBA_StructMemberSeq)
}

//line CORBA_InterfaceRepository.idl:358
//Usage Count: 5
type CORBA_AttributeMode int

const (
	CORBA_AttributeMode_ATTR_NORMAL = iota
	CORBA_AttributeMode_ATTR_READONLY
)

//line CORBA_InterfaceRepository.idl:359
//Interface Decl: CORBA_AttributeDef
//Usage Count: 2
type CORBA_AttributeDef interface {

	//line CORBA_InterfaceRepository.idl:360
	GetType() CORBA_TypeCode

	//line CORBA_InterfaceRepository.idl:361
	GetType_def() CORBA_IDLType
	SetType_def(value CORBA_IDLType)

	//line CORBA_InterfaceRepository.idl:362
	GetMode() CORBA_AttributeMode
	SetMode(value CORBA_AttributeMode)
}

//line CORBA_InterfaceRepository.idl:364
//Struct Decl: CORBA_AttributeDescription
//Usage Count: 0
type CORBA_AttributeDescription struct {
	Name       CORBA_Identifier
	Id         CORBA_RepositoryId
	Defined_in CORBA_RepositoryId
	Version    CORBA_VersionSpec
	Type       CORBA_TypeCode
	Mode       CORBA_AttributeMode
}

//Constructors
func NewCORBA_AttributeDescriptionDefaultPointer() (*CORBA_AttributeDescription, error) {
	return &CORBA_AttributeDescription{}, nil
}

func NewCORBA_AttributeDescriptionDefaultValue() (CORBA_AttributeDescription, error) {
	return CORBA_AttributeDescription{}, nil
}

func NewCORBA_AttributeDescriptionValue(
	name CORBA_Identifier,
	id CORBA_RepositoryId,
	defined_in CORBA_RepositoryId,
	version CORBA_VersionSpec,
	type_ CORBA_TypeCode,
	mode CORBA_AttributeMode) (CORBA_AttributeDescription, error) {
	return CORBA_AttributeDescription{
		Name:       name,
		Id:         id,
		Defined_in: defined_in,
		Version:    version,
		Type:       type_,
		Mode:       mode,
	}, nil
}

//line CORBA_InterfaceRepository.idl:372
//Struct Decl: CORBA_ExtAttributeDescription
//Usage Count: 1
type CORBA_ExtAttributeDescription struct {
	Name           CORBA_Identifier
	Id             CORBA_RepositoryId
	Defined_in     CORBA_RepositoryId
	Version        CORBA_VersionSpec
	Type           CORBA_TypeCode
	Mode           CORBA_AttributeMode
	Get_exceptions CORBA_ExcDescriptionSeq
	Put_exceptions CORBA_ExcDescriptionSeq
}

//Constructors
func NewCORBA_ExtAttributeDescriptionDefaultPointer() (*CORBA_ExtAttributeDescription, error) {
	return &CORBA_ExtAttributeDescription{}, nil
}

func NewCORBA_ExtAttributeDescriptionDefaultValue() (CORBA_ExtAttributeDescription, error) {
	return CORBA_ExtAttributeDescription{}, nil
}

func NewCORBA_ExtAttributeDescriptionValue(
	name CORBA_Identifier,
	id CORBA_RepositoryId,
	defined_in CORBA_RepositoryId,
	version CORBA_VersionSpec,
	type_ CORBA_TypeCode,
	mode CORBA_AttributeMode,
	get_exceptions CORBA_ExcDescriptionSeq,
	put_exceptions CORBA_ExcDescriptionSeq) (CORBA_ExtAttributeDescription, error) {
	return CORBA_ExtAttributeDescription{
		Name:           name,
		Id:             id,
		Defined_in:     defined_in,
		Version:        version,
		Type:           type_,
		Mode:           mode,
		Get_exceptions: get_exceptions,
		Put_exceptions: put_exceptions,
	}, nil
}

//line CORBA_InterfaceRepository.idl:382
//Interface Decl: CORBA_ExtAttributeDef
//Usage Count: 2
type CORBA_ExtAttributeDef interface {

	//line CORBA_InterfaceRepository.idl:384
	GetGet_exceptions() CORBA_ExcDescriptionSeq
	SetGet_exceptions(value CORBA_ExcDescriptionSeq)

	//line CORBA_InterfaceRepository.idl:385
	GetSet_exceptions() CORBA_ExcDescriptionSeq
	SetSet_exceptions(value CORBA_ExcDescriptionSeq)

	//line CORBA_InterfaceRepository.idl:387
	Describe_attribute() (CORBA_ExtAttributeDescription, error)
}

//line CORBA_InterfaceRepository.idl:389
//Usage Count: 2
type CORBA_OperationMode int

const (
	CORBA_OperationMode_OP_NORMAL = iota
	CORBA_OperationMode_OP_ONEWAY
)

//line CORBA_InterfaceRepository.idl:390
//Usage Count: 1
type CORBA_ParameterMode int

const (
	CORBA_ParameterMode_PARAM_IN = iota
	CORBA_ParameterMode_PARAM_OUT
	CORBA_ParameterMode_PARAM_INOUT
)

//line CORBA_InterfaceRepository.idl:391
//Struct Decl: CORBA_ParameterDescription
//Usage Count: 0
type CORBA_ParameterDescription struct {
	Name     CORBA_Identifier
	Type     CORBA_TypeCode
	Type_def CORBA_IDLType
	Mode     CORBA_ParameterMode
}

//Constructors
func NewCORBA_ParameterDescriptionDefaultPointer() (*CORBA_ParameterDescription, error) {
	return &CORBA_ParameterDescription{}, nil
}

func NewCORBA_ParameterDescriptionDefaultValue() (CORBA_ParameterDescription, error) {
	return CORBA_ParameterDescription{}, nil
}

func NewCORBA_ParameterDescriptionValue(
	name CORBA_Identifier,
	type_ CORBA_TypeCode,
	type_def CORBA_IDLType,
	mode CORBA_ParameterMode) (CORBA_ParameterDescription, error) {
	return CORBA_ParameterDescription{
		Name:     name,
		Type:     type_,
		Type_def: type_def,
		Mode:     mode,
	}, nil
}

//line CORBA_InterfaceRepository.idl:397
//Sequence Decl: Sequence_ParameterDescription
type Sequence_ParameterDescription interface{}

//line CORBA_InterfaceRepository.idl:397
//Typedef Decl: CORBA_ParDescriptionSeq
type CORBA_ParDescriptionSeq Sequence_ParameterDescription

//line CORBA_InterfaceRepository.idl:399
//Sequence Decl: Sequence_ContextIdentifier
type Sequence_ContextIdentifier interface{}

//line CORBA_InterfaceRepository.idl:399
//Typedef Decl: CORBA_ContextIdSeq
type CORBA_ContextIdSeq Sequence_ContextIdentifier

//line CORBA_InterfaceRepository.idl:400
//Sequence Decl: Sequence_ExceptionDef
type Sequence_ExceptionDef interface{}

//line CORBA_InterfaceRepository.idl:400
//Typedef Decl: CORBA_ExceptionDefSeq
type CORBA_ExceptionDefSeq Sequence_ExceptionDef

//line CORBA_InterfaceRepository.idl:402
//Interface Decl: CORBA_OperationDef
//Usage Count: 2
type CORBA_OperationDef interface {

	//line CORBA_InterfaceRepository.idl:403
	GetResult() CORBA_TypeCode

	//line CORBA_InterfaceRepository.idl:404
	GetResult_def() CORBA_IDLType
	SetResult_def(value CORBA_IDLType)

	//line CORBA_InterfaceRepository.idl:405
	GetParams() CORBA_ParDescriptionSeq
	SetParams(value CORBA_ParDescriptionSeq)

	//line CORBA_InterfaceRepository.idl:406
	GetMode() CORBA_OperationMode
	SetMode(value CORBA_OperationMode)

	//line CORBA_InterfaceRepository.idl:407
	GetContexts() CORBA_ContextIdSeq
	SetContexts(value CORBA_ContextIdSeq)

	//line CORBA_InterfaceRepository.idl:408
	GetExceptions() CORBA_ExceptionDefSeq
	SetExceptions(value CORBA_ExceptionDefSeq)
}

//line CORBA_InterfaceRepository.idl:411
//Struct Decl: CORBA_OperationDescription
//Usage Count: 0
type CORBA_OperationDescription struct {
	Name       CORBA_Identifier
	Id         CORBA_RepositoryId
	Defined_in CORBA_RepositoryId
	Version    CORBA_VersionSpec
	Result     CORBA_TypeCode
	Mode       CORBA_OperationMode
	Contexts   CORBA_ContextIdSeq
	Parameters CORBA_ParDescriptionSeq
	Exceptions CORBA_ExcDescriptionSeq
}

//Constructors
func NewCORBA_OperationDescriptionDefaultPointer() (*CORBA_OperationDescription, error) {
	return &CORBA_OperationDescription{}, nil
}

func NewCORBA_OperationDescriptionDefaultValue() (CORBA_OperationDescription, error) {
	return CORBA_OperationDescription{}, nil
}

func NewCORBA_OperationDescriptionValue(
	name CORBA_Identifier,
	id CORBA_RepositoryId,
	defined_in CORBA_RepositoryId,
	version CORBA_VersionSpec,
	result CORBA_TypeCode,
	mode CORBA_OperationMode,
	contexts CORBA_ContextIdSeq,
	parameters CORBA_ParDescriptionSeq,
	exceptions CORBA_ExcDescriptionSeq) (CORBA_OperationDescription, error) {
	return CORBA_OperationDescription{
		Name:       name,
		Id:         id,
		Defined_in: defined_in,
		Version:    version,
		Result:     result,
		Mode:       mode,
		Contexts:   contexts,
		Parameters: parameters,
		Exceptions: exceptions,
	}, nil
}

//line CORBA_InterfaceRepository.idl:422
//Sequence Decl: Sequence_RepositoryId
type Sequence_RepositoryId interface{}

//line CORBA_InterfaceRepository.idl:422
//Typedef Decl: CORBA_RepositoryIdSeq
type CORBA_RepositoryIdSeq Sequence_RepositoryId

//line CORBA_InterfaceRepository.idl:423
//Sequence Decl: Sequence_OperationDescription
type Sequence_OperationDescription interface{}

//line CORBA_InterfaceRepository.idl:423
//Typedef Decl: CORBA_OpDescriptionSeq
type CORBA_OpDescriptionSeq Sequence_OperationDescription

//line CORBA_InterfaceRepository.idl:424
//Sequence Decl: Sequence_AttributeDescription
type Sequence_AttributeDescription interface{}

//line CORBA_InterfaceRepository.idl:424
//Typedef Decl: CORBA_AttrDescriptionSeq
type CORBA_AttrDescriptionSeq Sequence_AttributeDescription

//line CORBA_InterfaceRepository.idl:425
//Sequence Decl: Sequence_ExtAttributeDescription
type Sequence_ExtAttributeDescription interface{}

//line CORBA_InterfaceRepository.idl:425
//Typedef Decl: CORBA_ExtAttrDescriptionSeq
type CORBA_ExtAttrDescriptionSeq Sequence_ExtAttributeDescription

//line CORBA_InterfaceRepository.idl:434
//Struct Decl: CORBA_InterfaceDef_FullInterfaceDescription
//Usage Count: 1
type CORBA_InterfaceDef_FullInterfaceDescription struct {
	Name            CORBA_Identifier
	Id              CORBA_RepositoryId
	Defined_in      CORBA_RepositoryId
	Version         CORBA_VersionSpec
	Operations      CORBA_OpDescriptionSeq
	Attributes      CORBA_AttrDescriptionSeq
	Base_interfaces CORBA_RepositoryIdSeq
	Type            CORBA_TypeCode
	Is_abstract     bool
}

//Constructors
func NewCORBA_InterfaceDef_FullInterfaceDescriptionDefaultPointer() (*CORBA_InterfaceDef_FullInterfaceDescription, error) {
	return &CORBA_InterfaceDef_FullInterfaceDescription{}, nil
}

func NewCORBA_InterfaceDef_FullInterfaceDescriptionDefaultValue() (CORBA_InterfaceDef_FullInterfaceDescription, error) {
	return CORBA_InterfaceDef_FullInterfaceDescription{}, nil
}

func NewCORBA_InterfaceDef_FullInterfaceDescriptionValue(
	name CORBA_Identifier,
	id CORBA_RepositoryId,
	defined_in CORBA_RepositoryId,
	version CORBA_VersionSpec,
	operations CORBA_OpDescriptionSeq,
	attributes CORBA_AttrDescriptionSeq,
	base_interfaces CORBA_RepositoryIdSeq,
	type_ CORBA_TypeCode,
	is_abstract bool) (CORBA_InterfaceDef_FullInterfaceDescription, error) {
	return CORBA_InterfaceDef_FullInterfaceDescription{
		Name:            name,
		Id:              id,
		Defined_in:      defined_in,
		Version:         version,
		Operations:      operations,
		Attributes:      attributes,
		Base_interfaces: base_interfaces,
		Type:            type_,
		Is_abstract:     is_abstract,
	}, nil
}

//line CORBA_InterfaceRepository.idl:427
//Interface Decl: CORBA_InterfaceDef
//Usage Count: 5
type CORBA_InterfaceDef interface {

	//line CORBA_InterfaceRepository.idl:429
	GetBase_interfaces() CORBA_InterfaceDefSeq
	SetBase_interfaces(value CORBA_InterfaceDefSeq)

	//line CORBA_InterfaceRepository.idl:430
	GetIs_abstract() bool
	SetIs_abstract(value bool)

	//line CORBA_InterfaceRepository.idl:432
	Is_a(interface_id CORBA_RepositoryId) (bool, error)

	//line CORBA_InterfaceRepository.idl:445
	Describe_interface() (CORBA_InterfaceDef_FullInterfaceDescription, error)

	//line CORBA_InterfaceRepository.idl:447
	Create_attribute(id CORBA_RepositoryId, mode CORBA_AttributeMode) (CORBA_AttributeDef, error)

	//line CORBA_InterfaceRepository.idl:454
	Create_operation(id CORBA_RepositoryId, contexts CORBA_ContextIdSeq) (CORBA_OperationDef, error)
}

//line CORBA_InterfaceRepository.idl:465
//Struct Decl: CORBA_InterfaceDescription
//Usage Count: 0
type CORBA_InterfaceDescription struct {
	Name            CORBA_Identifier
	Id              CORBA_RepositoryId
	Defined_in      CORBA_RepositoryId
	Version         CORBA_VersionSpec
	Base_interfaces CORBA_RepositoryIdSeq
	Is_abstract     bool
}

//Constructors
func NewCORBA_InterfaceDescriptionDefaultPointer() (*CORBA_InterfaceDescription, error) {
	return &CORBA_InterfaceDescription{}, nil
}

func NewCORBA_InterfaceDescriptionDefaultValue() (CORBA_InterfaceDescription, error) {
	return CORBA_InterfaceDescription{}, nil
}

func NewCORBA_InterfaceDescriptionValue(
	name CORBA_Identifier,
	id CORBA_RepositoryId,
	defined_in CORBA_RepositoryId,
	version CORBA_VersionSpec,
	base_interfaces CORBA_RepositoryIdSeq,
	is_abstract bool) (CORBA_InterfaceDescription, error) {
	return CORBA_InterfaceDescription{
		Name:            name,
		Id:              id,
		Defined_in:      defined_in,
		Version:         version,
		Base_interfaces: base_interfaces,
		Is_abstract:     is_abstract,
	}, nil
}

//line CORBA_InterfaceRepository.idl:476
//Struct Decl: CORBA_InterfaceAttrExtension_ExtFullInterfaceDescription
//Usage Count: 1
type CORBA_InterfaceAttrExtension_ExtFullInterfaceDescription struct {
	Name            CORBA_Identifier
	Id              CORBA_RepositoryId
	Defined_in      CORBA_RepositoryId
	Version         CORBA_VersionSpec
	Operations      CORBA_OpDescriptionSeq
	Attributes      CORBA_ExtAttrDescriptionSeq
	Base_interfaces CORBA_RepositoryIdSeq
	Type            CORBA_TypeCode
}

//Constructors
func NewCORBA_InterfaceAttrExtension_ExtFullInterfaceDescriptionDefaultPointer() (*CORBA_InterfaceAttrExtension_ExtFullInterfaceDescription, error) {
	return &CORBA_InterfaceAttrExtension_ExtFullInterfaceDescription{}, nil
}

func NewCORBA_InterfaceAttrExtension_ExtFullInterfaceDescriptionDefaultValue() (CORBA_InterfaceAttrExtension_ExtFullInterfaceDescription, error) {
	return CORBA_InterfaceAttrExtension_ExtFullInterfaceDescription{}, nil
}

func NewCORBA_InterfaceAttrExtension_ExtFullInterfaceDescriptionValue(
	name CORBA_Identifier,
	id CORBA_RepositoryId,
	defined_in CORBA_RepositoryId,
	version CORBA_VersionSpec,
	operations CORBA_OpDescriptionSeq,
	attributes CORBA_ExtAttrDescriptionSeq,
	base_interfaces CORBA_RepositoryIdSeq,
	type_ CORBA_TypeCode) (CORBA_InterfaceAttrExtension_ExtFullInterfaceDescription, error) {
	return CORBA_InterfaceAttrExtension_ExtFullInterfaceDescription{
		Name:            name,
		Id:              id,
		Defined_in:      defined_in,
		Version:         version,
		Operations:      operations,
		Attributes:      attributes,
		Base_interfaces: base_interfaces,
		Type:            type_,
	}, nil
}

//line CORBA_InterfaceRepository.idl:474
//Interface Decl: CORBA_InterfaceAttrExtension
//Usage Count: 0
type CORBA_InterfaceAttrExtension interface {

	//line CORBA_InterfaceRepository.idl:486
	Describe_ext_interface() (CORBA_InterfaceAttrExtension_ExtFullInterfaceDescription, error)

	//line CORBA_InterfaceRepository.idl:488
	Create_ext_attribute(id CORBA_RepositoryId, set_exceptions CORBA_ExceptionDefSeq) (CORBA_ExtAttributeDef, error)
}

//line CORBA_InterfaceRepository.idl:499
//Interface Decl: CORBA_ExtInterfaceDef
//Usage Count: 0
type CORBA_ExtInterfaceDef interface {
}

//line CORBA_InterfaceRepository.idl:501
type CORBA_Visibility int16

//line CORBA_InterfaceRepository.idl:502

//line CORBA_InterfaceRepository.idl:503

//line CORBA_InterfaceRepository.idl:505
//Struct Decl: CORBA_ValueMember
//Usage Count: 0
type CORBA_ValueMember struct {
	Name       CORBA_Identifier
	Id         CORBA_RepositoryId
	Defined_in CORBA_RepositoryId
	Version    CORBA_VersionSpec
	Type       CORBA_TypeCode
	Type_def   CORBA_IDLType
	Access     CORBA_Visibility
}

//Constructors
func NewCORBA_ValueMemberDefaultPointer() (*CORBA_ValueMember, error) {
	return &CORBA_ValueMember{}, nil
}

func NewCORBA_ValueMemberDefaultValue() (CORBA_ValueMember, error) {
	return CORBA_ValueMember{}, nil
}

func NewCORBA_ValueMemberValue(
	name CORBA_Identifier,
	id CORBA_RepositoryId,
	defined_in CORBA_RepositoryId,
	version CORBA_VersionSpec,
	type_ CORBA_TypeCode,
	type_def CORBA_IDLType,
	access CORBA_Visibility) (CORBA_ValueMember, error) {
	return CORBA_ValueMember{
		Name:       name,
		Id:         id,
		Defined_in: defined_in,
		Version:    version,
		Type:       type_,
		Type_def:   type_def,
		Access:     access,
	}, nil
}

//line CORBA_InterfaceRepository.idl:514
//Sequence Decl: Sequence_ValueMember
type Sequence_ValueMember interface{}

//line CORBA_InterfaceRepository.idl:514
//Typedef Decl: CORBA_ValueMemberSeq
type CORBA_ValueMemberSeq Sequence_ValueMember

//line CORBA_InterfaceRepository.idl:515
//Interface Decl: CORBA_ValueMemberDef
//Usage Count: 1
type CORBA_ValueMemberDef interface {

	//line CORBA_InterfaceRepository.idl:516
	GetType() CORBA_TypeCode

	//line CORBA_InterfaceRepository.idl:517
	GetType_def() CORBA_IDLType
	SetType_def(value CORBA_IDLType)

	//line CORBA_InterfaceRepository.idl:518
	GetAccess() CORBA_Visibility
	SetAccess(value CORBA_Visibility)
}

//line CORBA_InterfaceRepository.idl:531
//Struct Decl: CORBA_ValueDef_FullValueDescription
//Usage Count: 1
type CORBA_ValueDef_FullValueDescription struct {
	Name                 CORBA_Identifier
	Id                   CORBA_RepositoryId
	Is_abstract          bool
	Is_custom            bool
	Defined_in           CORBA_RepositoryId
	Version              CORBA_VersionSpec
	Operations           CORBA_OpDescriptionSeq
	Attributes           CORBA_AttrDescriptionSeq
	Members              CORBA_ValueMemberSeq
	Initializers         CORBA_InitializerSeq
	Supported_interfaces CORBA_RepositoryIdSeq
	Abstract_base_values CORBA_RepositoryIdSeq
	Is_truncatable       bool
	Base_value           CORBA_RepositoryId
	Type                 CORBA_TypeCode
}

//Constructors
func NewCORBA_ValueDef_FullValueDescriptionDefaultPointer() (*CORBA_ValueDef_FullValueDescription, error) {
	return &CORBA_ValueDef_FullValueDescription{}, nil
}

func NewCORBA_ValueDef_FullValueDescriptionDefaultValue() (CORBA_ValueDef_FullValueDescription, error) {
	return CORBA_ValueDef_FullValueDescription{}, nil
}

func NewCORBA_ValueDef_FullValueDescriptionValue(
	name CORBA_Identifier,
	id CORBA_RepositoryId,
	is_abstract bool,
	is_custom bool,
	defined_in CORBA_RepositoryId,
	version CORBA_VersionSpec,
	operations CORBA_OpDescriptionSeq,
	attributes CORBA_AttrDescriptionSeq,
	members CORBA_ValueMemberSeq,
	initializers CORBA_InitializerSeq,
	supported_interfaces CORBA_RepositoryIdSeq,
	abstract_base_values CORBA_RepositoryIdSeq,
	is_truncatable bool,
	base_value CORBA_RepositoryId,
	type_ CORBA_TypeCode) (CORBA_ValueDef_FullValueDescription, error) {
	return CORBA_ValueDef_FullValueDescription{
		Name:                 name,
		Id:                   id,
		Is_abstract:          is_abstract,
		Is_custom:            is_custom,
		Defined_in:           defined_in,
		Version:              version,
		Operations:           operations,
		Attributes:           attributes,
		Members:              members,
		Initializers:         initializers,
		Supported_interfaces: supported_interfaces,
		Abstract_base_values: abstract_base_values,
		Is_truncatable:       is_truncatable,
		Base_value:           base_value,
		Type:                 type_,
	}, nil
}

//line CORBA_InterfaceRepository.idl:520
//Interface Decl: CORBA_ValueDef
//Usage Count: 4
type CORBA_ValueDef interface {

	//line CORBA_InterfaceRepository.idl:522
	GetSupported_interfaces() CORBA_InterfaceDefSeq
	SetSupported_interfaces(value CORBA_InterfaceDefSeq)

	//line CORBA_InterfaceRepository.idl:523
	GetInitializers() CORBA_InitializerSeq
	SetInitializers(value CORBA_InitializerSeq)

	//line CORBA_InterfaceRepository.idl:524
	GetBase_value() CORBA_ValueDef
	SetBase_value(value CORBA_ValueDef)

	//line CORBA_InterfaceRepository.idl:525
	GetAbstract_base_values() CORBA_ValueDefSeq
	SetAbstract_base_values(value CORBA_ValueDefSeq)

	//line CORBA_InterfaceRepository.idl:526
	GetIs_abstract() bool
	SetIs_abstract(value bool)

	//line CORBA_InterfaceRepository.idl:527
	GetIs_custom() bool
	SetIs_custom(value bool)

	//line CORBA_InterfaceRepository.idl:528
	GetIs_truncatable() bool
	SetIs_truncatable(value bool)

	//line CORBA_InterfaceRepository.idl:530
	Is_a(id CORBA_RepositoryId) (bool, error)

	//line CORBA_InterfaceRepository.idl:548
	Describe_value() (CORBA_ValueDef_FullValueDescription, error)

	//line CORBA_InterfaceRepository.idl:549
	Create_value_member(id CORBA_RepositoryId, access CORBA_Visibility) (CORBA_ValueMemberDef, error)

	//line CORBA_InterfaceRepository.idl:556
	Create_attribute(id CORBA_RepositoryId, mode CORBA_AttributeMode) (CORBA_AttributeDef, error)

	//line CORBA_InterfaceRepository.idl:563
	Create_operation(id CORBA_RepositoryId, contexts CORBA_ContextIdSeq) (CORBA_OperationDef, error)
}

//line CORBA_InterfaceRepository.idl:574
//Struct Decl: CORBA_ValueDescription
//Usage Count: 1
type CORBA_ValueDescription struct {
	Name                 CORBA_Identifier
	Id                   CORBA_RepositoryId
	Is_abstract          bool
	Is_custom            bool
	Defined_in           CORBA_RepositoryId
	Version              CORBA_VersionSpec
	Supported_interfaces CORBA_RepositoryIdSeq
	Abstract_base_values CORBA_RepositoryIdSeq
	Is_truncatable       bool
	Base_value           CORBA_RepositoryId
}

//Constructors
func NewCORBA_ValueDescriptionDefaultPointer() (*CORBA_ValueDescription, error) {
	return &CORBA_ValueDescription{}, nil
}

func NewCORBA_ValueDescriptionDefaultValue() (CORBA_ValueDescription, error) {
	return CORBA_ValueDescription{}, nil
}

func NewCORBA_ValueDescriptionValue(
	name CORBA_Identifier,
	id CORBA_RepositoryId,
	is_abstract bool,
	is_custom bool,
	defined_in CORBA_RepositoryId,
	version CORBA_VersionSpec,
	supported_interfaces CORBA_RepositoryIdSeq,
	abstract_base_values CORBA_RepositoryIdSeq,
	is_truncatable bool,
	base_value CORBA_RepositoryId) (CORBA_ValueDescription, error) {
	return CORBA_ValueDescription{
		Name:                 name,
		Id:                   id,
		Is_abstract:          is_abstract,
		Is_custom:            is_custom,
		Defined_in:           defined_in,
		Version:              version,
		Supported_interfaces: supported_interfaces,
		Abstract_base_values: abstract_base_values,
		Is_truncatable:       is_truncatable,
		Base_value:           base_value,
	}, nil
}

//line CORBA_InterfaceRepository.idl:591
//Struct Decl: CORBA_ExtValueDef_ExtFullValueDescription
//Usage Count: 1
type CORBA_ExtValueDef_ExtFullValueDescription struct {
	Name                 CORBA_Identifier
	Id                   CORBA_RepositoryId
	Is_abstract          bool
	Is_custom            bool
	Defined_in           CORBA_RepositoryId
	Version              CORBA_VersionSpec
	Operations           CORBA_OpDescriptionSeq
	Attributes           CORBA_ExtAttrDescriptionSeq
	Members              CORBA_ValueMemberSeq
	Initializers         CORBA_ExtInitializerSeq
	Supported_interfaces CORBA_RepositoryIdSeq
	Abstract_base_values CORBA_RepositoryIdSeq
	Is_truncatable       bool
	Base_value           CORBA_RepositoryId
	Type                 CORBA_TypeCode
}

//Constructors
func NewCORBA_ExtValueDef_ExtFullValueDescriptionDefaultPointer() (*CORBA_ExtValueDef_ExtFullValueDescription, error) {
	return &CORBA_ExtValueDef_ExtFullValueDescription{}, nil
}

func NewCORBA_ExtValueDef_ExtFullValueDescriptionDefaultValue() (CORBA_ExtValueDef_ExtFullValueDescription, error) {
	return CORBA_ExtValueDef_ExtFullValueDescription{}, nil
}

func NewCORBA_ExtValueDef_ExtFullValueDescriptionValue(
	name CORBA_Identifier,
	id CORBA_RepositoryId,
	is_abstract bool,
	is_custom bool,
	defined_in CORBA_RepositoryId,
	version CORBA_VersionSpec,
	operations CORBA_OpDescriptionSeq,
	attributes CORBA_ExtAttrDescriptionSeq,
	members CORBA_ValueMemberSeq,
	initializers CORBA_ExtInitializerSeq,
	supported_interfaces CORBA_RepositoryIdSeq,
	abstract_base_values CORBA_RepositoryIdSeq,
	is_truncatable bool,
	base_value CORBA_RepositoryId,
	type_ CORBA_TypeCode) (CORBA_ExtValueDef_ExtFullValueDescription, error) {
	return CORBA_ExtValueDef_ExtFullValueDescription{
		Name:                 name,
		Id:                   id,
		Is_abstract:          is_abstract,
		Is_custom:            is_custom,
		Defined_in:           defined_in,
		Version:              version,
		Operations:           operations,
		Attributes:           attributes,
		Members:              members,
		Initializers:         initializers,
		Supported_interfaces: supported_interfaces,
		Abstract_base_values: abstract_base_values,
		Is_truncatable:       is_truncatable,
		Base_value:           base_value,
		Type:                 type_,
	}, nil
}

//line CORBA_InterfaceRepository.idl:587
//Interface Decl: CORBA_ExtValueDef
//Usage Count: 1
type CORBA_ExtValueDef interface {

	//line CORBA_InterfaceRepository.idl:589
	GetExt_initializers() CORBA_ExtInitializerSeq
	SetExt_initializers(value CORBA_ExtInitializerSeq)

	//line CORBA_InterfaceRepository.idl:608
	Describe_ext_value() (CORBA_ExtValueDef_ExtFullValueDescription, error)

	//line CORBA_InterfaceRepository.idl:610
	Create_ext_attribute(id CORBA_RepositoryId, set_exceptions CORBA_ExceptionDefSeq) (CORBA_ExtAttributeDef, error)
}

//line CORBA_InterfaceRepository.idl:621
//Interface Decl: CORBA_ValueBoxDef
//Usage Count: 1
type CORBA_ValueBoxDef interface {

	//line CORBA_InterfaceRepository.idl:622
	GetOriginal_type_def() CORBA_IDLType
	SetOriginal_type_def(value CORBA_IDLType)
}

//line CORBA_InterfaceRepository.idl:624
//Interface Decl: CORBA_AbstractInterfaceDef
//Usage Count: 1
type CORBA_AbstractInterfaceDef interface {
}

//line CORBA_InterfaceRepository.idl:626
//Interface Decl: CORBA_ExtAbstractInterfaceDef
//Usage Count: 0
type CORBA_ExtAbstractInterfaceDef interface {
}

//line CORBA_InterfaceRepository.idl:629
//Interface Decl: CORBA_LocalInterfaceDef
//Usage Count: 1
type CORBA_LocalInterfaceDef interface {
}

//line CORBA_InterfaceRepository.idl:631
//Interface Decl: CORBA_ExtLocalInterfaceDef
//Usage Count: 0
type CORBA_ExtLocalInterfaceDef interface {
}

//line CORBA_InterfaceRepository.idl:637

//line CORBA_InterfaceRepository.idl:641
//Interface Decl: CORBA_ComponentIR_EventDef
//Usage Count: 5
type CORBA_ComponentIR_EventDef interface {
}

//line CORBA_InterfaceRepository.idl:642
//Interface Decl: CORBA_ComponentIR_Container
//Usage Count: 0
type CORBA_ComponentIR_Container interface {

	//line CORBA_InterfaceRepository.idl:643
	Create_component(id CORBA_RepositoryId, supports_interfaces CORBA_InterfaceDefSeq) (CORBA_ComponentIR_ComponentDef, error)

	//line CORBA_InterfaceRepository.idl:650
	Create_home(id CORBA_RepositoryId, primary_key CORBA_ValueDef) (CORBA_ComponentIR_HomeDef, error)

	//line CORBA_InterfaceRepository.idl:659
	Create_event(id CORBA_RepositoryId, initializers CORBA_ExtInitializerSeq) (CORBA_ComponentIR_EventDef, error)
}

//line CORBA_InterfaceRepository.idl:672
//Interface Decl: CORBA_ComponentIR_ModuleDef
//Usage Count: 0
type CORBA_ComponentIR_ModuleDef interface {
}

//line CORBA_InterfaceRepository.idl:673
//Interface Decl: CORBA_ComponentIR_Repository
//Usage Count: 0
type CORBA_ComponentIR_Repository interface {
}

//line CORBA_InterfaceRepository.idl:674
//Interface Decl: CORBA_ComponentIR_ProvidesDef
//Usage Count: 1
type CORBA_ComponentIR_ProvidesDef interface {

	//line CORBA_InterfaceRepository.idl:675
	GetInterface_type() CORBA_InterfaceDef
	SetInterface_type(value CORBA_InterfaceDef)
}

//line CORBA_InterfaceRepository.idl:677
//Struct Decl: CORBA_ComponentIR_ProvidesDescription
//Usage Count: 0
type CORBA_ComponentIR_ProvidesDescription struct {
	Name           CORBA_Identifier
	Id             CORBA_RepositoryId
	Defined_in     CORBA_RepositoryId
	Version        CORBA_VersionSpec
	Interface_type CORBA_RepositoryId
}

//Constructors
func NewCORBA_ComponentIR_ProvidesDescriptionDefaultPointer() (*CORBA_ComponentIR_ProvidesDescription, error) {
	return &CORBA_ComponentIR_ProvidesDescription{}, nil
}

func NewCORBA_ComponentIR_ProvidesDescriptionDefaultValue() (CORBA_ComponentIR_ProvidesDescription, error) {
	return CORBA_ComponentIR_ProvidesDescription{}, nil
}

func NewCORBA_ComponentIR_ProvidesDescriptionValue(
	name CORBA_Identifier,
	id CORBA_RepositoryId,
	defined_in CORBA_RepositoryId,
	version CORBA_VersionSpec,
	interface_type CORBA_RepositoryId) (CORBA_ComponentIR_ProvidesDescription, error) {
	return CORBA_ComponentIR_ProvidesDescription{
		Name:           name,
		Id:             id,
		Defined_in:     defined_in,
		Version:        version,
		Interface_type: interface_type,
	}, nil
}

//line CORBA_InterfaceRepository.idl:684
//Interface Decl: CORBA_ComponentIR_UsesDef
//Usage Count: 1
type CORBA_ComponentIR_UsesDef interface {

	//line CORBA_InterfaceRepository.idl:685
	GetInterface_type() CORBA_InterfaceDef
	SetInterface_type(value CORBA_InterfaceDef)

	//line CORBA_InterfaceRepository.idl:686
	GetIs_multiple() bool
	SetIs_multiple(value bool)
}

//line CORBA_InterfaceRepository.idl:688
//Struct Decl: CORBA_ComponentIR_UsesDescription
//Usage Count: 0
type CORBA_ComponentIR_UsesDescription struct {
	Name           CORBA_Identifier
	Id             CORBA_RepositoryId
	Defined_in     CORBA_RepositoryId
	Version        CORBA_VersionSpec
	Interface_type CORBA_RepositoryId
	Is_multiple    bool
}

//Constructors
func NewCORBA_ComponentIR_UsesDescriptionDefaultPointer() (*CORBA_ComponentIR_UsesDescription, error) {
	return &CORBA_ComponentIR_UsesDescription{}, nil
}

func NewCORBA_ComponentIR_UsesDescriptionDefaultValue() (CORBA_ComponentIR_UsesDescription, error) {
	return CORBA_ComponentIR_UsesDescription{}, nil
}

func NewCORBA_ComponentIR_UsesDescriptionValue(
	name CORBA_Identifier,
	id CORBA_RepositoryId,
	defined_in CORBA_RepositoryId,
	version CORBA_VersionSpec,
	interface_type CORBA_RepositoryId,
	is_multiple bool) (CORBA_ComponentIR_UsesDescription, error) {
	return CORBA_ComponentIR_UsesDescription{
		Name:           name,
		Id:             id,
		Defined_in:     defined_in,
		Version:        version,
		Interface_type: interface_type,
		Is_multiple:    is_multiple,
	}, nil
}

//line CORBA_InterfaceRepository.idl:696
//Interface Decl: CORBA_ComponentIR_EventPortDef
//Usage Count: 0
type CORBA_ComponentIR_EventPortDef interface {

	//line CORBA_InterfaceRepository.idl:698
	GetEvent() CORBA_ComponentIR_EventDef
	SetEvent(value CORBA_ComponentIR_EventDef)

	//line CORBA_InterfaceRepository.idl:700
	Is_a(event_id CORBA_RepositoryId) (bool, error)
}

//line CORBA_InterfaceRepository.idl:702
//Struct Decl: CORBA_ComponentIR_EventPortDescription
//Usage Count: 0
type CORBA_ComponentIR_EventPortDescription struct {
	Name       CORBA_Identifier
	Id         CORBA_RepositoryId
	Defined_in CORBA_RepositoryId
	Version    CORBA_VersionSpec
	Event      CORBA_RepositoryId
}

//Constructors
func NewCORBA_ComponentIR_EventPortDescriptionDefaultPointer() (*CORBA_ComponentIR_EventPortDescription, error) {
	return &CORBA_ComponentIR_EventPortDescription{}, nil
}

func NewCORBA_ComponentIR_EventPortDescriptionDefaultValue() (CORBA_ComponentIR_EventPortDescription, error) {
	return CORBA_ComponentIR_EventPortDescription{}, nil
}

func NewCORBA_ComponentIR_EventPortDescriptionValue(
	name CORBA_Identifier,
	id CORBA_RepositoryId,
	defined_in CORBA_RepositoryId,
	version CORBA_VersionSpec,
	event CORBA_RepositoryId) (CORBA_ComponentIR_EventPortDescription, error) {
	return CORBA_ComponentIR_EventPortDescription{
		Name:       name,
		Id:         id,
		Defined_in: defined_in,
		Version:    version,
		Event:      event,
	}, nil
}

//line CORBA_InterfaceRepository.idl:709
//Interface Decl: CORBA_ComponentIR_EmitsDef
//Usage Count: 1
type CORBA_ComponentIR_EmitsDef interface {
}

//line CORBA_InterfaceRepository.idl:710
//Interface Decl: CORBA_ComponentIR_PublishesDef
//Usage Count: 1
type CORBA_ComponentIR_PublishesDef interface {
}

//line CORBA_InterfaceRepository.idl:711
//Interface Decl: CORBA_ComponentIR_ConsumesDef
//Usage Count: 1
type CORBA_ComponentIR_ConsumesDef interface {
}

//line CORBA_InterfaceRepository.idl:712
//Interface Decl: CORBA_ComponentIR_ComponentDef
//Usage Count: 3
type CORBA_ComponentIR_ComponentDef interface {

	//line CORBA_InterfaceRepository.idl:714
	GetBase_component() CORBA_ComponentIR_ComponentDef
	SetBase_component(value CORBA_ComponentIR_ComponentDef)

	//line CORBA_InterfaceRepository.idl:715
	GetSupported_interfaces() CORBA_InterfaceDefSeq
	SetSupported_interfaces(value CORBA_InterfaceDefSeq)

	//line CORBA_InterfaceRepository.idl:717
	Create_provides(id CORBA_RepositoryId, interface_type CORBA_InterfaceDef) (CORBA_ComponentIR_ProvidesDef, error)

	//line CORBA_InterfaceRepository.idl:723
	Create_uses(id CORBA_RepositoryId, is_multiple bool) (CORBA_ComponentIR_UsesDef, error)

	//line CORBA_InterfaceRepository.idl:730
	Create_emits(id CORBA_RepositoryId, event CORBA_ComponentIR_EventDef) (CORBA_ComponentIR_EmitsDef, error)

	//line CORBA_InterfaceRepository.idl:736
	Create_publishes(id CORBA_RepositoryId, event CORBA_ComponentIR_EventDef) (CORBA_ComponentIR_PublishesDef, error)

	//line CORBA_InterfaceRepository.idl:742
	Create_consumes(id CORBA_RepositoryId, event CORBA_ComponentIR_EventDef) (CORBA_ComponentIR_ConsumesDef, error)
}

//line CORBA_InterfaceRepository.idl:749
//Sequence Decl: Sequence_ProvidesDescription
type Sequence_ProvidesDescription interface{}

//line CORBA_InterfaceRepository.idl:750
//Typedef Decl: CORBA_ComponentIR_ProvidesDescriptionSeq
type CORBA_ComponentIR_ProvidesDescriptionSeq Sequence_ProvidesDescription

//line CORBA_InterfaceRepository.idl:751
//Sequence Decl: Sequence_UsesDescription
type Sequence_UsesDescription interface{}

//line CORBA_InterfaceRepository.idl:751
//Typedef Decl: CORBA_ComponentIR_UsesDescriptionSeq
type CORBA_ComponentIR_UsesDescriptionSeq Sequence_UsesDescription

//line CORBA_InterfaceRepository.idl:752
//Sequence Decl: Sequence_EventPortDescription
type Sequence_EventPortDescription interface{}

//line CORBA_InterfaceRepository.idl:753
//Typedef Decl: CORBA_ComponentIR_EventPortDescriptionSeq
type CORBA_ComponentIR_EventPortDescriptionSeq Sequence_EventPortDescription

//line CORBA_InterfaceRepository.idl:754
//Struct Decl: CORBA_ComponentIR_ComponentDescription
//Usage Count: 0
type CORBA_ComponentIR_ComponentDescription struct {
	Name                 CORBA_Identifier
	Id                   CORBA_RepositoryId
	Defined_in           CORBA_RepositoryId
	Version              CORBA_VersionSpec
	Base_component       CORBA_RepositoryId
	Supported_interfaces CORBA_RepositoryIdSeq
	Provided_interfaces  CORBA_ComponentIR_ProvidesDescriptionSeq
	Used_interfaces      CORBA_ComponentIR_UsesDescriptionSeq
	Emits_events         CORBA_ComponentIR_EventPortDescriptionSeq
	Publishes_events     CORBA_ComponentIR_EventPortDescriptionSeq
	Consumes_events      CORBA_ComponentIR_EventPortDescriptionSeq
	Attributes           CORBA_ExtAttrDescriptionSeq
	Type                 CORBA_TypeCode
}

//Constructors
func NewCORBA_ComponentIR_ComponentDescriptionDefaultPointer() (*CORBA_ComponentIR_ComponentDescription, error) {
	return &CORBA_ComponentIR_ComponentDescription{}, nil
}

func NewCORBA_ComponentIR_ComponentDescriptionDefaultValue() (CORBA_ComponentIR_ComponentDescription, error) {
	return CORBA_ComponentIR_ComponentDescription{}, nil
}

func NewCORBA_ComponentIR_ComponentDescriptionValue(
	name CORBA_Identifier,
	id CORBA_RepositoryId,
	defined_in CORBA_RepositoryId,
	version CORBA_VersionSpec,
	base_component CORBA_RepositoryId,
	supported_interfaces CORBA_RepositoryIdSeq,
	provided_interfaces CORBA_ComponentIR_ProvidesDescriptionSeq,
	used_interfaces CORBA_ComponentIR_UsesDescriptionSeq,
	emits_events CORBA_ComponentIR_EventPortDescriptionSeq,
	publishes_events CORBA_ComponentIR_EventPortDescriptionSeq,
	consumes_events CORBA_ComponentIR_EventPortDescriptionSeq,
	attributes CORBA_ExtAttrDescriptionSeq,
	type_ CORBA_TypeCode) (CORBA_ComponentIR_ComponentDescription, error) {
	return CORBA_ComponentIR_ComponentDescription{
		Name:                 name,
		Id:                   id,
		Defined_in:           defined_in,
		Version:              version,
		Base_component:       base_component,
		Supported_interfaces: supported_interfaces,
		Provided_interfaces:  provided_interfaces,
		Used_interfaces:      used_interfaces,
		Emits_events:         emits_events,
		Publishes_events:     publishes_events,
		Consumes_events:      consumes_events,
		Attributes:           attributes,
		Type:                 type_,
	}, nil
}

//line CORBA_InterfaceRepository.idl:769
//Interface Decl: CORBA_ComponentIR_FactoryDef
//Usage Count: 1
type CORBA_ComponentIR_FactoryDef interface {
}

//line CORBA_InterfaceRepository.idl:770
//Interface Decl: CORBA_ComponentIR_FinderDef
//Usage Count: 1
type CORBA_ComponentIR_FinderDef interface {
}

//line CORBA_InterfaceRepository.idl:771
//Interface Decl: CORBA_ComponentIR_HomeDef
//Usage Count: 2
type CORBA_ComponentIR_HomeDef interface {

	//line CORBA_InterfaceRepository.idl:773
	GetBase_home() CORBA_ComponentIR_HomeDef
	SetBase_home(value CORBA_ComponentIR_HomeDef)

	//line CORBA_InterfaceRepository.idl:774
	GetSupported_interfaces() CORBA_InterfaceDefSeq
	SetSupported_interfaces(value CORBA_InterfaceDefSeq)

	//line CORBA_InterfaceRepository.idl:775
	GetManaged_component() CORBA_ComponentIR_ComponentDef
	SetManaged_component(value CORBA_ComponentIR_ComponentDef)

	//line CORBA_InterfaceRepository.idl:776
	GetPrimary_key() CORBA_ValueDef
	SetPrimary_key(value CORBA_ValueDef)

	//line CORBA_InterfaceRepository.idl:778
	Create_factory(id CORBA_RepositoryId, exceptions CORBA_ExceptionDefSeq) (CORBA_ComponentIR_FactoryDef, error)

	//line CORBA_InterfaceRepository.idl:785
	Create_finder(id CORBA_RepositoryId, exceptions CORBA_ExceptionDefSeq) (CORBA_ComponentIR_FinderDef, error)
}

//line CORBA_InterfaceRepository.idl:793
//Struct Decl: CORBA_ComponentIR_HomeDescription
//Usage Count: 0
type CORBA_ComponentIR_HomeDescription struct {
	Name              CORBA_Identifier
	Id                CORBA_RepositoryId
	Defined_in        CORBA_RepositoryId
	Version           CORBA_VersionSpec
	Base_home         CORBA_RepositoryId
	Managed_component CORBA_RepositoryId
	Primary_key       CORBA_ValueDescription
	Factories         CORBA_OpDescriptionSeq
	Finders           CORBA_OpDescriptionSeq
	Operations        CORBA_OpDescriptionSeq
	Attributes        CORBA_ExtAttrDescriptionSeq
	Type              CORBA_TypeCode
}

//Constructors
func NewCORBA_ComponentIR_HomeDescriptionDefaultPointer() (*CORBA_ComponentIR_HomeDescription, error) {
	return &CORBA_ComponentIR_HomeDescription{}, nil
}

func NewCORBA_ComponentIR_HomeDescriptionDefaultValue() (CORBA_ComponentIR_HomeDescription, error) {
	return CORBA_ComponentIR_HomeDescription{}, nil
}

func NewCORBA_ComponentIR_HomeDescriptionValue(
	name CORBA_Identifier,
	id CORBA_RepositoryId,
	defined_in CORBA_RepositoryId,
	version CORBA_VersionSpec,
	base_home CORBA_RepositoryId,
	managed_component CORBA_RepositoryId,
	primary_key CORBA_ValueDescription,
	factories CORBA_OpDescriptionSeq,
	finders CORBA_OpDescriptionSeq,
	operations CORBA_OpDescriptionSeq,
	attributes CORBA_ExtAttrDescriptionSeq,
	type_ CORBA_TypeCode) (CORBA_ComponentIR_HomeDescription, error) {
	return CORBA_ComponentIR_HomeDescription{
		Name:              name,
		Id:                id,
		Defined_in:        defined_in,
		Version:           version,
		Base_home:         base_home,
		Managed_component: managed_component,
		Primary_key:       primary_key,
		Factories:         factories,
		Finders:           finders,
		Operations:        operations,
		Attributes:        attributes,
		Type:              type_,
	}, nil
}
