package corbaFiles

//Code generated by  DO NOT EDIT.
//line CORBA_TypeCode.idl:10
//Usage Count: 0
type CORBA_TCKind int

//noinspection ALL
const (
	CORBA_TCKind_tk_null = iota
	CORBA_TCKind_tk_void
	CORBA_TCKind_tk_short
	CORBA_TCKind_tk_long
	CORBA_TCKind_tk_ushort
	CORBA_TCKind_tk_ulong
	CORBA_TCKind_tk_float
	CORBA_TCKind_tk_double
	CORBA_TCKind_tk_boolean
	CORBA_TCKind_tk_char
	CORBA_TCKind_tk_octet
	CORBA_TCKind_tk_any
	CORBA_TCKind_tk_TypeCode
	CORBA_TCKind_tk_Principal
	CORBA_TCKind_tk_objref
	CORBA_TCKind_tk_struct
	CORBA_TCKind_tk_union
	CORBA_TCKind_tk_enum
	CORBA_TCKind_tk_string
	CORBA_TCKind_tk_sequence
	CORBA_TCKind_tk_array
	CORBA_TCKind_tk_alias
	CORBA_TCKind_tk_except
	CORBA_TCKind_tk_longlong
	CORBA_TCKind_tk_ulonglong
	CORBA_TCKind_tk_longdouble
	CORBA_TCKind_tk_wchar
	CORBA_TCKind_tk_wstring
	CORBA_TCKind_tk_fixed
	CORBA_TCKind_tk_value
	CORBA_TCKind_tk_value_box
	CORBA_TCKind_tk_native
	CORBA_TCKind_tk_abstract_interface
	CORBA_TCKind_tk_local_interface
	CORBA_TCKind_tk_component
	CORBA_TCKind_tk_home
	CORBA_TCKind_tk_event
)

//line CORBA_TypeCode.idl:33
//Exception Decl: CORBA_TypeCode_Bounds
//Usage Count: 0
type CORBA_TypeCode_Bounds struct {
}

//Constructors
func NewCORBA_TypeCode_BoundsDefaultPointer() (*CORBA_TypeCode_Bounds, error) {
}

func NewCORBA_TypeCode_BoundsDefaultValue() (CORBA_TypeCode_Bounds, error) {
}

//line CORBA_TypeCode.idl:34
//Exception Decl: CORBA_TypeCode_BadKind
//Usage Count: 0
type CORBA_TypeCode_BadKind struct {
}

//Constructors
func NewCORBA_TypeCode_BadKindDefaultPointer() (*CORBA_TypeCode_BadKind, error) {
}

func NewCORBA_TypeCode_BadKindDefaultValue() (CORBA_TypeCode_BadKind, error) {
}

//line CORBA_TypeCode.idl:32
//Interface Decl: TypeCode
//Usage Count: 0
type TypeCode interface {
	//line CORBA_TypeCode.idl:36
	Equal(tc TypeCode) (bool, error)
	//line CORBA_TypeCode.idl:37
	Equivalent(tc TypeCode) (bool, error)
	//line CORBA_TypeCode.idl:38
	Get_compact_typecode() (TypeCode, error)
	//line CORBA_TypeCode.idl:39
	Kind() (TCKind, error)
	//line CORBA_TypeCode.idl:43
	Id() (RepositoryId, error)
	//line CORBA_TypeCode.idl:47
	Name() (Identifier, error)
	//line CORBA_TypeCode.idl:50
	Member_count() (uint32, error)
	//line CORBA_TypeCode.idl:51
	Member_name(index uint32) (Identifier, error)
	//line CORBA_TypeCode.idl:54
	Member_type(index uint32) (TypeCode, error)
	//line CORBA_TypeCode.idl:57
	Member_label(index uint32) (CorbaAny, error)
	//line CORBA_TypeCode.idl:59
	Discriminator_type() (TypeCode, error)
	//line CORBA_TypeCode.idl:60
	Default_index() (int32, error)
	//line CORBA_TypeCode.idl:62
	Length() (uint32, error)
	//line CORBA_TypeCode.idl:64
	Content_type() (TypeCode, error)
	//line CORBA_TypeCode.idl:66
	Fixed_digits() (uint16, error)
	//line CORBA_TypeCode.idl:67
	Fixed_scale() (int16, error)
	//line CORBA_TypeCode.idl:69
	Member_visibility(index uint32) (Visibility, error)
	//line CORBA_TypeCode.idl:71
	Type_modifier() (ValueModifier, error)
	//line CORBA_TypeCode.idl:72
	Concrete_base_type() (TypeCode, error)
}
