// Code generated by abc. DO NOT EDIT.

package corbaFiles

//line CORBA_Stream.idl:3
//Sequence Decl: Sequence_CorbaAny
type Sequence_CorbaAny interface{}

//line CORBA_Stream.idl:3
//Typedef Decl: CORBA_AnySeq
type CORBA_AnySeq Sequence_CorbaAny

//line CORBA_Stream.idl:5
//Sequence Decl: Sequence_bool
type Sequence_bool interface{}

//line CORBA_Stream.idl:5
//Typedef Decl: CORBA_BooleanSeq
type CORBA_BooleanSeq Sequence_bool

//line CORBA_Stream.idl:6
//Sequence Decl: Sequence_AnsiChar
type Sequence_AnsiChar interface{}

//line CORBA_Stream.idl:6
//Typedef Decl: CORBA_CharSeq
type CORBA_CharSeq Sequence_AnsiChar

//line CORBA_Stream.idl:7
//Sequence Decl: Sequence_WideChar
type Sequence_WideChar interface{}

//line CORBA_Stream.idl:7
//Typedef Decl: CORBA_WCharSeq
type CORBA_WCharSeq Sequence_WideChar

//line CORBA_Stream.idl:8
//Sequence Decl: Sequence_int
type Sequence_int interface{}

//line CORBA_Stream.idl:8
//Typedef Decl: CORBA_OctetSeq
type CORBA_OctetSeq Sequence_int

//line CORBA_Stream.idl:9
//Sequence Decl: Sequence_int16
type Sequence_int16 interface{}

//line CORBA_Stream.idl:9
//Typedef Decl: CORBA_ShortSeq
type CORBA_ShortSeq Sequence_int16

//line CORBA_Stream.idl:10
//Sequence Decl: Sequence_uint16
type Sequence_uint16 interface{}

//line CORBA_Stream.idl:10
//Typedef Decl: CORBA_UShortSeq
type CORBA_UShortSeq Sequence_uint16

//line CORBA_Stream.idl:11
//Sequence Decl: Sequence_int32
type Sequence_int32 interface{}

//line CORBA_Stream.idl:11
//Typedef Decl: CORBA_LongSeq
type CORBA_LongSeq Sequence_int32

//line CORBA_Stream.idl:12
//Sequence Decl: Sequence_uint32
type Sequence_uint32 interface{}

//line CORBA_Stream.idl:12
//Typedef Decl: CORBA_ULongSeq
type CORBA_ULongSeq Sequence_uint32

//line CORBA_Stream.idl:13
//Sequence Decl: Sequence_int64
type Sequence_int64 interface{}

//line CORBA_Stream.idl:13
//Typedef Decl: CORBA_LongLongSeq
type CORBA_LongLongSeq Sequence_int64

//line CORBA_Stream.idl:14
//Sequence Decl: Sequence_uint64
type Sequence_uint64 interface{}

//line CORBA_Stream.idl:14
//Typedef Decl: CORBA_ULongLongSeq
type CORBA_ULongLongSeq Sequence_uint64

//line CORBA_Stream.idl:15
//Sequence Decl: Sequence_CorbaFloat
type Sequence_CorbaFloat interface{}

//line CORBA_Stream.idl:15
//Typedef Decl: CORBA_FloatSeq
type CORBA_FloatSeq Sequence_CorbaFloat

//line CORBA_Stream.idl:16
//Sequence Decl: Sequence_CorbaDouble
type Sequence_CorbaDouble interface{}

//line CORBA_Stream.idl:16
//Typedef Decl: CORBA_DoubleSeq
type CORBA_DoubleSeq Sequence_CorbaDouble

//line CORBA_Stream.idl:17
//Sequence Decl: Sequence_CorbaLongDouble
type Sequence_CorbaLongDouble interface{}

//line CORBA_Stream.idl:17
//Typedef Decl: CORBA_LongDoubleSeq
type CORBA_LongDoubleSeq Sequence_CorbaLongDouble

//line CORBA_Stream.idl:18
//Sequence Decl: Sequence_AnsiString
type Sequence_AnsiString interface{}

//line CORBA_Stream.idl:18
//Typedef Decl: CORBA_StringSeq
type CORBA_StringSeq Sequence_AnsiString

//line CORBA_Stream.idl:19
//Sequence Decl: Sequence_WideString
type Sequence_WideString interface{}

//line CORBA_Stream.idl:19
//Typedef Decl: CORBA_WStringSeq
type CORBA_WStringSeq Sequence_WideString

//line CORBA_Stream.idl:21
//Exception Decl: CORBA_BadFixedValueException
//Usage Count: 0
type CORBA_BadFixedValueException struct {
	Offset uint32
}

//Constructors
func NewCORBA_BadFixedValueExceptionDefaultPointer() (*CORBA_BadFixedValueException, error) {
	return &CORBA_BadFixedValueException{}, nil
}

func NewCORBA_BadFixedValueExceptionDefaultValue() (CORBA_BadFixedValueException, error) {
	return CORBA_BadFixedValueException{}, nil
}

func NewCORBA_BadFixedValueExceptionValue(
	offset uint32) (CORBA_BadFixedValueException, error) {
	return CORBA_BadFixedValueException{
		Offset: offset,
	}, nil
}
