// Code generated by abc. DO NOT EDIT.

package corbaFiles

//line CORBA_NVList.idl:4
//Interface Decl: NVList
//Usage Count: 0
type NVList interface {

	//line CORBA_NVList.idl:5
	Add_item(item_name Identifier, item_flags Flags) error

	//line CORBA_NVList.idl:12
	Free() error

	//line CORBA_NVList.idl:13
	Free_memory() error

	//line CORBA_NVList.idl:14
	Get_count(count int32) error
}
