package corbaFiles

//Code generated by  DO NOT EDIT.
//line CORBA_Stream.idl:21
//Exception Decl: CORBA_BadFixedValue
type CORBA_BadFixedValue struct {
	Offset uint32
}

//Constructors
func NewCORBA_BadFixedValueDefaultPointer() (*CORBA_BadFixedValue, error) {
	return &CORBA_BadFixedValue {
		Offset: 0,
	}, nil
}

func NewCORBA_BadFixedValueDefaultValue() (CORBA_BadFixedValue, error) {
	return CORBA_BadFixedValue {
		Offset: 0,
	}, nil
}

func NewCORBA_BadFixedValueValue(
	offset uint32) (CORBA_BadFixedValue, error) {
	return CORBA_BadFixedValue {
		Offset: offset,
	}, nil
}
//line CORBA_Stream.idl:25
//ValueAbsolute Decl: DataOutputStream
type DataOutputStream interface {
	//line CORBA_Stream.idl:26
	Write_any(value CorbaAny) (void, error)
	//line CORBA_Stream.idl:27
	Write_boolean(value bool) (void, error)
	//line CORBA_Stream.idl:28
	Write_char(value rune) (void, error)
	//line CORBA_Stream.idl:29
	Write_wchar(value rune) (void, error)
	//line CORBA_Stream.idl:30
	Write_octet(value int) (void, error)
	//line CORBA_Stream.idl:31
	Write_short(value int16) (void, error)
	//line CORBA_Stream.idl:32
	Write_ushort(value uint16) (void, error)
	//line CORBA_Stream.idl:33
	Write_long(value int32) (void, error)
	//line CORBA_Stream.idl:34
	Write_ulong(value uint32) (void, error)
	//line CORBA_Stream.idl:35
	Write_longlong(value int64) (void, error)
	//line CORBA_Stream.idl:36
	Write_ulonglong(value uint63) (void, error)
	//line CORBA_Stream.idl:37
	Write_float(value float) (void, error)
	//line CORBA_Stream.idl:38
	Write_double(value float64) (void, error)
	//line CORBA_Stream.idl:39
	Write_longdouble(value float64) (void, error)
	//line CORBA_Stream.idl:40
	Write_string(value string) (void, error)
	//line CORBA_Stream.idl:41
	Write_wstring(value string) (void, error)
	//line CORBA_Stream.idl:42
	Write_Object(value CorbaObject) (void, error)
	//line CORBA_Stream.idl:43
	Write_Abstract(value AbstractBase) (void, error)
	//line CORBA_Stream.idl:44
	Write_Value(value valuebase) (void, error)
	//line CORBA_Stream.idl:45
	Write_TypeCode(value TypeCode) (void, error)
	//line CORBA_Stream.idl:46
	Write_any_array(seq AnySeq,length uint32) (void, error)
	//line CORBA_Stream.idl:49
	Write_boolean_array(seq BooleanSeq,length uint32) (void, error)
	//line CORBA_Stream.idl:52
	Write_char_array(seq CharSeq,length uint32) (void, error)
	//line CORBA_Stream.idl:55
	Write_wchar_array(seq WCharSeq,length uint32) (void, error)
	//line CORBA_Stream.idl:58
	Write_octet_array(seq OctetSeq,length uint32) (void, error)
	//line CORBA_Stream.idl:61
	Write_short_array(seq ShortSeq,length uint32) (void, error)
	//line CORBA_Stream.idl:64
	Write_ushort_array(seq UShortSeq,length uint32) (void, error)
	//line CORBA_Stream.idl:67
	Write_long_array(seq LongSeq,length uint32) (void, error)
	//line CORBA_Stream.idl:70
	Write_ulong_array(seq ULongSeq,length uint32) (void, error)
	//line CORBA_Stream.idl:73
	Write_ulonglong_array(seq ULongLongSeq,length uint32) (void, error)
	//line CORBA_Stream.idl:76
	Write_longlong_array(seq LongLongSeq,length uint32) (void, error)
	//line CORBA_Stream.idl:79
	Write_float_array(seq FloatSeq,length uint32) (void, error)
	//line CORBA_Stream.idl:82
	Write_double_array(seq DoubleSeq,length uint32) (void, error)
	//line CORBA_Stream.idl:85
	Write_long_double_array(seq LongDoubleSeq,length uint32) (void, error)
	//line CORBA_Stream.idl:89
	Write_fixed(fixed_value CorbaAny) (void, error)
	//line CORBA_Stream.idl:92
	Write_fixed_array(seq AnySeq,length uint32) (void, error)
}
//line CORBA_Stream.idl:99
//ValueAbsolute Decl: DataInputStream
type DataInputStream interface {
	//line CORBA_Stream.idl:100
	Read_any() (CorbaAny, error)
	//line CORBA_Stream.idl:101
	Read_boolean() (bool, error)
	//line CORBA_Stream.idl:102
	Read_char() (rune, error)
	//line CORBA_Stream.idl:103
	Read_wchar() (rune, error)
	//line CORBA_Stream.idl:104
	Read_octet() (int, error)
	//line CORBA_Stream.idl:105
	Read_short() (int16, error)
	//line CORBA_Stream.idl:106
	Read_ushort() (uint16, error)
	//line CORBA_Stream.idl:107
	Read_long() (int32, error)
	//line CORBA_Stream.idl:108
	Read_ulong() (uint32, error)
	//line CORBA_Stream.idl:109
	Read_longlong() (int64, error)
	//line CORBA_Stream.idl:110
	Read_ulonglong() (uint63, error)
	//line CORBA_Stream.idl:111
	Read_float() (float, error)
	//line CORBA_Stream.idl:112
	Read_double() (float64, error)
	//line CORBA_Stream.idl:113
	Read_longdouble() (float64, error)
	//line CORBA_Stream.idl:114
	Read_string() (string, error)
	//line CORBA_Stream.idl:115
	Read_wstring() (string, error)
	//line CORBA_Stream.idl:116
	Read_Object() (CorbaObject, error)
	//line CORBA_Stream.idl:117
	Read_Abstract() (AbstractBase, error)
	//line CORBA_Stream.idl:118
	Read_Value() (valuebase, error)
	//line CORBA_Stream.idl:119
	Read_TypeCode() (TypeCode, error)
	//line CORBA_Stream.idl:121
	Read_any_array(seq AnySeq,length uint32) (void, error)
	//line CORBA_Stream.idl:125
	Read_boolean_array(seq BooleanSeq,length uint32) (void, error)
	//line CORBA_Stream.idl:129
	Read_char_array(seq CharSeq,length uint32) (void, error)
	//line CORBA_Stream.idl:133
	Read_wchar_array(seq WCharSeq,length uint32) (void, error)
	//line CORBA_Stream.idl:137
	Read_octet_array(seq OctetSeq,length uint32) (void, error)
	//line CORBA_Stream.idl:141
	Read_short_array(seq ShortSeq,length uint32) (void, error)
	//line CORBA_Stream.idl:145
	Read_ushort_array(seq UShortSeq,length uint32) (void, error)
	//line CORBA_Stream.idl:149
	Read_long_array(seq LongSeq,length uint32) (void, error)
	//line CORBA_Stream.idl:153
	Read_ulong_array(seq ULongSeq,length uint32) (void, error)
	//line CORBA_Stream.idl:157
	Read_ulonglong_array(seq ULongLongSeq,length uint32) (void, error)
	//line CORBA_Stream.idl:161
	Read_longlong_array(seq LongLongSeq,length uint32) (void, error)
	//line CORBA_Stream.idl:165
	Read_float_array(seq FloatSeq,length uint32) (void, error)
	//line CORBA_Stream.idl:169
	Read_double_array(seq DoubleSeq,length uint32) (void, error)
	//line CORBA_Stream.idl:173
	Read_long_double_array(seq DoubleSeq,length uint32) (void, error)
	//line CORBA_Stream.idl:177
	Read_fixed(digits uint16,scale int16) (CorbaAny, error)
	//line CORBA_Stream.idl:181
	Read_fixed_array(seq AnySeq,scale int16) (void, error)
}
