// Code generated by abc. DO NOT EDIT.

package corbaFiles

//line Dynamic.idl:19
//Struct Decl: Dynamic_Parameter
//Usage Count: 0
type Dynamic_Parameter struct {
	Argument CorbaAny
	Mode     CORBA_ParameterMode
}

//Constructors
func NewDynamic_ParameterDefaultPointer() (*Dynamic_Parameter, error) {
	return &Dynamic_Parameter{}, nil
}

func NewDynamic_ParameterDefaultValue() (Dynamic_Parameter, error) {
	return Dynamic_Parameter{}, nil
}

func NewDynamic_ParameterValue(
	argument CorbaAny,
	mode CORBA_ParameterMode) (Dynamic_Parameter, error) {
	return Dynamic_Parameter{
		Argument: argument,
		Mode:     mode,
	}, nil
}

//line Dynamic.idl:24
//Sequence Decl: Sequence_Parameter
type Sequence_Parameter interface{}

//line Dynamic.idl:24
//Typedef Decl: Dynamic_ParameterList
type Dynamic_ParameterList Sequence_Parameter

//line Dynamic.idl:26
//Sequence Decl: Sequence_CORBA_TypeCode
type Sequence_CORBA_TypeCode interface{}

//line Dynamic.idl:26
//Typedef Decl: Dynamic_ExceptionList
type Dynamic_ExceptionList Sequence_CORBA_TypeCode
