// Code generated by abc. DO NOT EDIT.

package corbaFiles

//line IOP.idl:23
type IOP_ProfileId uint32

//line IOP.idl:30
//Struct Decl: IOP_TaggedProfile
//Usage Count: 0
type IOP_TaggedProfile struct {
	Tag          IOP_ProfileId
	Profile_data IOP_ProfileData
}

//Constructors
func NewIOP_TaggedProfileDefaultPointer() (*IOP_TaggedProfile, error) {
	return &IOP_TaggedProfile{}, nil
}

func NewIOP_TaggedProfileDefaultValue() (IOP_TaggedProfile, error) {
	return IOP_TaggedProfile{}, nil
}

func NewIOP_TaggedProfileValue(
	tag IOP_ProfileId,
	profile_data IOP_ProfileData) (IOP_TaggedProfile, error) {
	return IOP_TaggedProfile{
		Tag:          tag,
		Profile_data: profile_data,
	}, nil
}

//line IOP.idl:35
//Sequence Decl: Sequence_TaggedProfile
type Sequence_TaggedProfile interface{}

//line IOP.idl:35
//Typedef Decl: IOP_TaggedProfileSeq
type IOP_TaggedProfileSeq Sequence_TaggedProfile

//line IOP.idl:41
//Struct Decl: IOP_IOR
//Usage Count: 0
type IOP_IOR struct {
	Type_id  AnsiString
	Profiles IOP_TaggedProfileSeq
}

//Constructors
func NewIOP_IORDefaultPointer() (*IOP_IOR, error) {
	return &IOP_IOR{}, nil
}

func NewIOP_IORDefaultValue() (IOP_IOR, error) {
	return IOP_IOR{}, nil
}

func NewIOP_IORValue(
	type_id AnsiString,
	profiles IOP_TaggedProfileSeq) (IOP_IOR, error) {
	return IOP_IOR{
		Type_id:  type_id,
		Profiles: profiles,
	}, nil
}

//line IOP.idl:52
type IOP_ComponentId uint32

//line IOP.idl:56
//Struct Decl: IOP_TaggedComponent
//Usage Count: 0
type IOP_TaggedComponent struct {
	Tag            IOP_ComponentId
	Component_data IOP_ComponentData
}

//Constructors
func NewIOP_TaggedComponentDefaultPointer() (*IOP_TaggedComponent, error) {
	return &IOP_TaggedComponent{}, nil
}

func NewIOP_TaggedComponentDefaultValue() (IOP_TaggedComponent, error) {
	return IOP_TaggedComponent{}, nil
}

func NewIOP_TaggedComponentValue(
	tag IOP_ComponentId,
	component_data IOP_ComponentData) (IOP_TaggedComponent, error) {
	return IOP_TaggedComponent{
		Tag:            tag,
		Component_data: component_data,
	}, nil
}

//line IOP.idl:61
//Sequence Decl: Sequence_TaggedComponent
type Sequence_TaggedComponent interface{}

//line IOP.idl:61
//Typedef Decl: IOP_TaggedComponentSeq
type IOP_TaggedComponentSeq Sequence_TaggedComponent

//line IOP.idl:62
//Sequence Decl: Sequence_TaggedComponent
type Sequence_TaggedComponent interface{}

//line IOP.idl:62
//Typedef Decl: IOP_MultipleComponentProfile
type IOP_MultipleComponentProfile Sequence_TaggedComponent

//line IOP.idl:111
type IOP_ServiceId uint32

//line IOP.idl:114
//Sequence Decl: Sequence_int
type Sequence_int interface{}

//line IOP.idl:112
//Struct Decl: IOP_ServiceContext
//Usage Count: 0
type IOP_ServiceContext struct {
	Context_id   IOP_ServiceId
	Context_data Sequence_int
}

//Constructors
func NewIOP_ServiceContextDefaultPointer() (*IOP_ServiceContext, error) {
	return &IOP_ServiceContext{}, nil
}

func NewIOP_ServiceContextDefaultValue() (IOP_ServiceContext, error) {
	return IOP_ServiceContext{}, nil
}

func NewIOP_ServiceContextValue(
	context_id IOP_ServiceId,
	context_data Sequence_int) (IOP_ServiceContext, error) {
	return IOP_ServiceContext{
		Context_id:   context_id,
		Context_data: context_data,
	}, nil
}

//line IOP.idl:116
//Sequence Decl: Sequence_ServiceContext
type Sequence_ServiceContext interface{}

//line IOP.idl:116
//Typedef Decl: IOP_ServiceContextList
type IOP_ServiceContextList Sequence_ServiceContext

//line IOP.idl:138
//Exception Decl: IOP_Codec_InvalidTypeForEncodingException
//Usage Count: 0
type IOP_Codec_InvalidTypeForEncodingException struct {
}

//Constructors
func NewIOP_Codec_InvalidTypeForEncodingExceptionDefaultPointer() (*IOP_Codec_InvalidTypeForEncodingException, error) {
	return &IOP_Codec_InvalidTypeForEncodingException{}, nil
}

func NewIOP_Codec_InvalidTypeForEncodingExceptionDefaultValue() (IOP_Codec_InvalidTypeForEncodingException, error) {
	return IOP_Codec_InvalidTypeForEncodingException{}, nil
}

//line IOP.idl:139
//Exception Decl: IOP_Codec_FormatMismatchException
//Usage Count: 0
type IOP_Codec_FormatMismatchException struct {
}

//Constructors
func NewIOP_Codec_FormatMismatchExceptionDefaultPointer() (*IOP_Codec_FormatMismatchException, error) {
	return &IOP_Codec_FormatMismatchException{}, nil
}

func NewIOP_Codec_FormatMismatchExceptionDefaultValue() (IOP_Codec_FormatMismatchException, error) {
	return IOP_Codec_FormatMismatchException{}, nil
}

//line IOP.idl:140
//Exception Decl: IOP_Codec_TypeMismatchException
//Usage Count: 0
type IOP_Codec_TypeMismatchException struct {
}

//Constructors
func NewIOP_Codec_TypeMismatchExceptionDefaultPointer() (*IOP_Codec_TypeMismatchException, error) {
	return &IOP_Codec_TypeMismatchException{}, nil
}

func NewIOP_Codec_TypeMismatchExceptionDefaultValue() (IOP_Codec_TypeMismatchException, error) {
	return IOP_Codec_TypeMismatchException{}, nil
}

//line IOP.idl:137
//Interface Decl: IOP_Codec
//Usage Count: 1
type IOP_Codec interface {

	//line IOP.idl:142
	Encode(data CorbaAny) (CORBA_OctetSeq, error)

	//line IOP.idl:144
	Decode(data CORBA_OctetSeq) (CorbaAny, error)

	//line IOP.idl:146
	Encode_value(data CorbaAny) (CORBA_OctetSeq, error)

	//line IOP.idl:148
	Decode_value(data CORBA_OctetSeq, tc CORBA_TypeCode) (CorbaAny, error)
}

//line IOP.idl:156
type IOP_EncodingFormat int16

//line IOP.idl:159
//Struct Decl: IOP_Encoding
//Usage Count: 1
type IOP_Encoding struct {
	Format        IOP_EncodingFormat
	Major_version int
	Minor_version int
}

//Constructors
func NewIOP_EncodingDefaultPointer() (*IOP_Encoding, error) {
	return &IOP_Encoding{}, nil
}

func NewIOP_EncodingDefaultValue() (IOP_Encoding, error) {
	return IOP_Encoding{}, nil
}

func NewIOP_EncodingValue(
	format IOP_EncodingFormat,
	major_version int,
	minor_version int) (IOP_Encoding, error) {
	return IOP_Encoding{
		Format:        format,
		Major_version: major_version,
		Minor_version: minor_version,
	}, nil
}

//line IOP.idl:166
//Exception Decl: IOP_CodecFactory_UnknownEncodingException
//Usage Count: 0
type IOP_CodecFactory_UnknownEncodingException struct {
}

//Constructors
func NewIOP_CodecFactory_UnknownEncodingExceptionDefaultPointer() (*IOP_CodecFactory_UnknownEncodingException, error) {
	return &IOP_CodecFactory_UnknownEncodingException{}, nil
}

func NewIOP_CodecFactory_UnknownEncodingExceptionDefaultValue() (IOP_CodecFactory_UnknownEncodingException, error) {
	return IOP_CodecFactory_UnknownEncodingException{}, nil
}

//line IOP.idl:165
//Interface Decl: IOP_CodecFactory
//Usage Count: 0
type IOP_CodecFactory interface {

	//line IOP.idl:167
	Create_codec(enc IOP_Encoding) (IOP_Codec, error)
}
