// Code generated by abc. DO NOT EDIT.

package corbaFiles

//line IOP_DCE.idl:12
//Struct Decl: IOP_EndpointIdPositionComponent
//Usage Count: 0
type IOP_EndpointIdPositionComponent struct {
	Begin uint16
	End   uint16
}

//Constructors
func NewIOP_EndpointIdPositionComponentDefaultPointer() (*IOP_EndpointIdPositionComponent, error) {
	return &IOP_EndpointIdPositionComponent{}, nil
}

func NewIOP_EndpointIdPositionComponentDefaultValue() (IOP_EndpointIdPositionComponent, error) {
	return IOP_EndpointIdPositionComponent{}, nil
}

func NewIOP_EndpointIdPositionComponentValue(
	begin uint16,
	end uint16) (IOP_EndpointIdPositionComponent, error) {
	return IOP_EndpointIdPositionComponent{
		Begin: begin,
		End:   end,
	}, nil
}
