package corbaFiles

//Code generated by  DO NOT EDIT.
//line orb.idl:45
//Forward Interface Decl: CORBA_ConstructionPolicy
//line orb.idl:46
//Forward Interface Decl: CORBA_Current
//line orb.idl:47
//Forward Interface Decl: CORBA_DomainManager
//line orb.idl:48
//Forward Interface Decl: CORBA_Policy
//line orb.idl:49
//Forward Interface Decl: CORBA_PollableSet
//line orb.idl:50
//Forward ValueAbsolute Decl: CustomMarshal
//line orb.idl:51
//Forward ValueAbsolute Decl: DataInputStream
//line orb.idl:52
//Forward ValueAbsolute Decl: DataOutputStream
//line orb.idl:55
//Forward Interface Decl: CORBA_AbstractInterfaceDef
//line orb.idl:56
//Forward Interface Decl: CORBA_AliasDef
//line orb.idl:57
//Forward Interface Decl: CORBA_ArrayDef
//line orb.idl:58
//Forward Interface Decl: CORBA_AttributeDef
//line orb.idl:59
//Forward Interface Decl: CORBA_ConstantDef
//line orb.idl:60
//Forward Interface Decl: CORBA_Contained
//line orb.idl:61
//Forward Interface Decl: CORBA_Container
//line orb.idl:62
//Forward Interface Decl: CORBA_EnumDef
//line orb.idl:63
//Forward Interface Decl: CORBA_ExceptionDef
//line orb.idl:64
//Forward Interface Decl: CORBA_ExtInterfaceDef
//line orb.idl:65
//Forward Interface Decl: CORBA_ExtValueDef
//line orb.idl:66
//Forward Interface Decl: CORBA_ExtAbstractInterfaceDef
//line orb.idl:67
//Forward Interface Decl: CORBA_ExtLocalInterfaceDef
//line orb.idl:68
//Forward Interface Decl: CORBA_FixedDef
//line orb.idl:69
//Forward Interface Decl: CORBA_IDLType
//line orb.idl:70
//Forward Interface Decl: CORBA_InterfaceDef
//line orb.idl:71
//Forward Interface Decl: CORBA_IRObject
//line orb.idl:72
//Forward Interface Decl: CORBA_LocalInterfaceDef
//line orb.idl:73
//Forward Interface Decl: CORBA_ModuleDef
//line orb.idl:74
//Forward Interface Decl: CORBA_NativeDef
//line orb.idl:75
//Forward Interface Decl: CORBA_OperationDef
//line orb.idl:76
//Forward Interface Decl: CORBA_PrimitiveDef
//line orb.idl:77
//Forward Interface Decl: CORBA_Repository
//line orb.idl:78
//Forward Interface Decl: CORBA_SequenceDef
//line orb.idl:79
//Forward Interface Decl: CORBA_StringDef
//line orb.idl:80
//Forward Interface Decl: CORBA_StructDef
//line orb.idl:81
//Forward Interface Decl: CORBA_TypeCode
//line orb.idl:82
//Forward Interface Decl: CORBA_TypedefDef
//line orb.idl:83
//Forward Interface Decl: CORBA_UnionDef
//line orb.idl:84
//Forward Interface Decl: CORBA_ValueDef
//line orb.idl:85
//Forward Interface Decl: CORBA_ValueBoxDef
//line orb.idl:86
//Forward Interface Decl: CORBA_ValueMemberDef
//line orb.idl:87
//Forward Interface Decl: CORBA_WstringDef
