// Code generated by abc. DO NOT EDIT.

package corbaFiles

//line SendingContext.idl:20
//Interface Decl: SendingContext_RunTime
//Usage Count: 0
type SendingContext_RunTime interface {
}

//line SendingContext.idl:25
type SendingContext_CodeBase_URL AnsiString

//line SendingContext.idl:26
//Sequence Decl: Sequence_URL
type Sequence_URL interface{}

//line SendingContext.idl:26
//Typedef Decl: SendingContext_CodeBase_URLSeq
type SendingContext_CodeBase_URLSeq Sequence_URL

//line SendingContext.idl:27
//Sequence Decl: Sequence_CORBA_ValueDef_FullValueDescription
type Sequence_CORBA_ValueDef_FullValueDescription interface{}

//line SendingContext.idl:27
//Typedef Decl: SendingContext_CodeBase_ValueDescSeq
type SendingContext_CodeBase_ValueDescSeq Sequence_CORBA_ValueDef_FullValueDescription

//line SendingContext.idl:24
//Interface Decl: SendingContext_CodeBase
//Usage Count: 0
type SendingContext_CodeBase interface {

	//line SendingContext.idl:30
	Get_ir() (CORBA_Repository, error)

	//line SendingContext.idl:33
	Implementation(x CORBA_RepositoryId) (SendingContext_CodeBase_URL, error)

	//line SendingContext.idl:34
	Implementationx(x CORBA_RepositoryId) (SendingContext_CodeBase_URL, error)

	//line SendingContext.idl:35
	Implementations(x CORBA_RepositoryIdSeq) (SendingContext_CodeBase_URLSeq, error)

	//line SendingContext.idl:40
	Meta(x CORBA_RepositoryId) (CORBA_ValueDef_FullValueDescription, error)

	//line SendingContext.idl:41
	Metas(x CORBA_RepositoryIdSeq) (SendingContext_CodeBase_ValueDescSeq, error)

	//line SendingContext.idl:46
	Bases(x CORBA_RepositoryId) (CORBA_RepositoryIdSeq, error)
}
