package testFiles

//Code generated by  DO NOT EDIT.
//line third.idl:5
//Exception Decl: E
type E struct {
	Abc int32
}

//Constructors
func NewEDefaultPointer() (*E, error) {
	return &E {
		Abc: 0,
	}, nil
}

func NewEDefaultValue() (E, error) {
	return E {
		Abc: 0,
	}, nil
}

func NewEValue(
	abc int32) (E, error) {
	return E {
		Abc: abc,
	}, nil
}
