package common

//Code generated by  DO NOT EDIT.
//line common.idl:1
//Struct Decl: Common
type Common struct {
	ABC int32
}

//Constructors
func NewCommonDefaultPointer() (*Common, error) {
	return &Common {
		ABC: 0,
	}, nil
}

func NewCommonDefaultValue() (Common, error) {
	return Common {
		ABC: 0,
	}, nil
}

func NewCommonValue(
	aBC int32) (Common, error) {
	return Common {
		ABC: aBC,
	}, nil
}
